
import type { Product } from './types';

// This is a mock database for CBD products to be used locally.
// In a real application, this data would come from a CMS or a database.

export const cbdProducts: Product[] = [
  {
    id: 'cbd_prod_001',
    sku: 'PAB2C3',
    name: 'Aceite CBD 10%',
    price: 3999,
    description: 'Nuestro aceite de espectro completo más popular, ideal para el bienestar diario.',
    longDescription: '<p>Descubre la pureza de nuestro Aceite de CBD al 10%, extraído mediante CO2 para garantizar la máxima calidad. Es un aceite de espectro completo, lo que significa que contiene todos los cannabinoides y terpenos de la planta para un efecto séquito superior.</p><ul><li>100% Orgánico</li><li>Sin pesticidas ni herbicidas</li><li>Probado en laboratorio</li></ul>',
    imageUrl: 'https://picsum.photos/seed/cbd1/400/400',
    imageHint: 'cbd oil bottle',
    tags: ['Best Seller'],
    internalTags: ['aceite', 'bienestar', 'mas-vendido', 'popper'],
    stock: 25,
    brand: 'CBD King',
    size: '10ml',
    composition: '10% CBD',
    productDetails: 'Concentración: 10%\nTipo: Espectro Completo\nBase: Aceite de Oliva',
    url: 'https://comprarcbdonline.com/producto/aceite-cbd-10/'
  },
  {
    id: 'cbd_prod_002',
    sku: 'PD4E5F',
    name: 'Flores CBD "Amnesia"',
    price: 999,
    description: 'Flores aromáticas con un perfil cítrico y terroso. Cultivo interior.',
    longDescription: '<p>Las flores "Amnesia" son famosas por su aroma penetrante y fresco, con notas cítricas y un fondo terroso. Cultivadas en interior bajo condiciones controladas para asegurar la máxima calidad y potencia.</p>',
    imageUrl: 'https://picsum.photos/seed/cbd2/400/400',
    imageHint: 'cbd flower jar',
    tags: ['Nuevo'],
    internalTags: ['flores', 'novedad', 'popper'],
    stock: 50,
    brand: 'Green House',
    size: '1g',
    composition: '15% CBD',
    productDetails: 'Cultivo: Interior\nAroma: Cítrico, Terroso\nCBD: ~15%',
    url: 'https://comprarcbdonline.com/producto/flores-amnesia/'
  },
  {
    id: 'cbd_prod_003',
    sku: 'PG7H8I',
    name: 'Crema CBD Efecto Frío',
    price: 2499,
    description: 'Crema tópica para alivio muscular con mentol y CBD.',
    longDescription: '<p>Formulada para deportistas y personas con molestias musculares, nuestra crema combina 500mg de CBD con el poder refrescante del mentol para proporcionar un alivio rápido y localizado.</p>',
    imageUrl: 'https://picsum.photos/seed/cbd3/400/400',
    imageHint: 'cbd cream tube',
    tags: [],
    internalTags: ['topicos', 'alivio', 'accesorio', 'popper'],
    stock: 15,
    brand: 'CBD Skin',
    size: '50ml',
    composition: '500mg CBD',
    productDetails: 'Aplicación: Tópica\nEfecto: Frío\nIngredientes Clave: Mentol, CBD',
    url: 'https://comprarcbdonline.com/producto/crema-cbd-frio/'
  },
  {
    id: 'cbd_prod_004',
    sku: 'PJ1K2L',
    name: 'Vape Desechable CBD',
    price: 1999,
    description: 'Vape listo para usar con sabor a frutos rojos. Sin nicotina.',
    longDescription: '<p>La forma más fácil y cómoda de disfrutar de los beneficios del CBD. Este vape desechable no requiere carga ni recambios. Simplemente inhala y disfruta de su delicioso sabor a frutos rojos.</p>',
    imageUrl: 'https://picsum.photos/seed/cbd4/400/400',
    imageHint: 'cbd vape pen',
    tags: ['Oferta'],
    internalTags: ['vape', 'oferta', 'popper'],
    stock: 30,
    brand: 'VapeLife',
    size: '1ml',
    composition: '200mg CBD',
    productDetails: 'Sabor: Frutos Rojos\nNicotina: 0%\nBatería: 280mAh',
    url: 'https://comprarcbdonline.com/producto/vape-desechable/'
  },
  {
    id: 'cbd_prod_005',
    sku: 'PM4N5P',
    name: 'Aceite CBD 20%',
    price: 5999,
    description: 'Doble concentración para usuarios que buscan un efecto más potente.',
    longDescription: '<p>Nuestro aceite más potente, con una concentración del 20% de CBD. Ideal para usuarios experimentados o aquellos que necesitan una dosis más alta para alcanzar sus objetivos de bienestar. Misma calidad, doble potencia.</p>',
    imageUrl: 'https://picsum.photos/seed/cbd5/400/400',
    imageHint: 'premium cbd oil',
    tags: [],
    internalTags: ['aceite', 'potente', 'popper'],
    stock: 10,
    brand: 'CBD King',
    size: '10ml',
    composition: '20% CBD',
    productDetails: 'Concentración: 20%\nTipo: Espectro Completo\nBase: Aceite de Oliva',
    url: 'https://comprarcbdonline.com/producto/aceite-cbd-20/'
  },
   {
    id: 'cbd_prod_006',
    sku: 'PQ7R8S',
    name: 'Flores CBD "Gelato"',
    price: 1099,
    description: 'Aroma dulce y cremoso que recuerda al postre italiano. Cultivo hidropónico.',
    longDescription: '<p>Una variedad que enamora por su perfil de terpenos dulce y cremoso. "Gelato" es perfecta para una tarde de relajación. Cultivada hidropónicamente para un control total sobre su desarrollo y calidad.</p>',
    imageUrl: 'https://picsum.photos/seed/cbd6/400/400',
    imageHint: 'cbd flower bud',
    tags: [],
    internalTags: ['flores', 'popper'],
    stock: 0, // Out of stock example
    brand: 'Green House',
    size: '1g',
    composition: '18% CBD',
    productDetails: 'Cultivo: Hidropónico\nAroma: Dulce, Cremoso\nCBD: ~18%',
    url: 'https://comprarcbdonline.com/producto/flores-gelato/'
  },
];
