
import type { Product } from './types';

// This is a mock database for CBD products to be used locally.
// In a real application, this data would come from a CMS or a database.

export const cbdProducts: Product[] = [
  {
    id: 'cbd_prod_001',
    sku: 'PROD-A1B2C3',
    name: 'Aceite CBD 10%',
    price: 3999,
    description: 'Nuestro aceite de espectro completo más popular, ideal para el bienestar diario.',
    imageUrl: 'https://picsum.photos/seed/cbd1/400/400',
    imageHint: 'cbd oil bottle',
    tags: ['Aceite', 'Bienestar'],
    stock: 25,
    brand: 'CBD King',
    size: '10ml',
    composition: '10% CBD',
  },
  {
    id: 'cbd_prod_002',
    sku: 'PROD-D4E5F6',
    name: 'Flores CBD "Amnesia"',
    price: 999,
    description: 'Flores aromáticas con un perfil cítrico y terroso. Cultivo interior.',
    imageUrl: 'https://picsum.photos/seed/cbd2/400/400',
    imageHint: 'cbd flower jar',
    tags: ['Flores'],
    stock: 50,
    brand: 'Green House',
    size: '1g',
    composition: '15% CBD',
  },
  {
    id: 'cbd_prod_003',
    sku: 'PROD-G7H8I9',
    name: 'Crema CBD Efecto Frío',
    price: 2499,
    description: 'Crema tópica para alivio muscular con mentol y CBD.',
    imageUrl: 'https://picsum.photos/seed/cbd3/400/400',
    imageHint: 'cbd cream tube',
    tags: ['Tópicos', 'Alivio'],
    stock: 15,
    brand: 'CBD Skin',
    size: '50ml',
    composition: '500mg CBD',
  },
  {
    id: 'cbd_prod_004',
    sku: 'PROD-J1K2L3',
    name: 'Vape Desechable CBD',
    price: 1999,
    description: 'Vape listo para usar con sabor a frutos rojos. Sin nicotina.',
    imageUrl: 'https://picsum.photos/seed/cbd4/400/400',
    imageHint: 'cbd vape pen',
    tags: ['Vape'],
    stock: 30,
    brand: 'VapeLife',
    size: '1ml',
    composition: '200mg CBD',
  },
  {
    id: 'cbd_prod_005',
    sku: 'PROD-M4N5P6',
    name: 'Aceite CBD 20%',
    price: 5999,
    description: 'Doble concentración para usuarios que buscan un efecto más potente.',
    imageUrl: 'https://picsum.photos/seed/cbd5/400/400',
    imageHint: 'premium cbd oil',
    tags: ['Aceite', 'Potente'],
    stock: 10,
    brand: 'CBD King',
    size: '10ml',
    composition: '20% CBD',
  },
   {
    id: 'cbd_prod_006',
    sku: 'PROD-Q7R8S9',
    name: 'Flores CBD "Gelato"',
    price: 1099,
    description: 'Aroma dulce y cremoso que recuerda al postre italiano. Cultivo hidropónico.',
    imageUrl: 'https://picsum.photos/seed/cbd6/400/400',
    imageHint: 'cbd flower bud',
    tags: ['Flores'],
    stock: 0, // Out of stock example
    brand: 'Green House',
    size: '1g',
    composition: '18% CBD',
  },
];
