
'use client';

import React, { createContext, useContext, useState, ReactNode, useMemo, useCallback } from 'react';

type Language = 'es' | 'en' | 'fr' | 'de' | 'it' | 'pt';

// Define a nested structure for translations
type Translations = {
  [key: string]: string | Translations;
};

// Simplified dictionary for now
const translations: Record<Language, Translations> = {
  es: {
    header: {
      free_shipping: 'GRATIS +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Menú de Navegación',
      products: 'Productos',
      create_pack: 'Crea tu Pack',
      monthly_dose: 'Dosis Mensual'
    },
    cart: {
        title: "Carrito de la Compra",
        empty_title: "Tu carrito está vacío",
        empty_subtitle: "Parece que aún no has añadido nada.",
        subtotal: "Subtotal",
        volume_discount: "Descuento por volumen (con pago anticipado)",
        shipping_estimate: "Envío (estimado)",
        total_estimate: "Total Estimado:",
        free_shipping_banner: "¡Disfrutas de Envío GRATIS!",
        free_shipping_threshold: "Envío gratis en pedidos superiores a {price}",
        checkout_button: "Finalizar Reserva",
        discreet_packaging: "Embalaje 100% discreto.",
        notes: "El descuento por volumen y los gastos de envío finales se aplicarán en la pantalla de pago según el método elegido.",
        item_added: "Añadido al carrito",
        item_removed: "Producto eliminado",
        item_unavailable: "Agotado",
        stock_limit_reached: "Límite de stock alcanzado",
    },
    account: {
        layout_title: "Mi Cuenta",
        layout_description: "Gestiona tu información personal, pedidos y direcciones.",
        sidebar_admin_panel: "Panel de Admin",
        sidebar_dashboard: "Panel de Usuario",
        sidebar_orders: "Pedidos",
        sidebar_addresses: "Direcciones",
        sidebar_subscription: "Dosis Mensual",
        sidebar_logout: "Cerrar Sesión",
        dashboard_title: "Panel de Usuario",
        dashboard_welcome: "Bienvenido de nuevo, {name}.",
        dashboard_profile_title: "Información de Perfil",
        dashboard_profile_subtitle: "Tus datos personales.",
        dashboard_profile_name: "Nombre:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Puntos de Fidelidad",
        dashboard_loyalty_subtitle: "Gana puntos con cada compra.",
        dashboard_loyalty_points: "Puntos Acumulados",
        dashboard_loyalty_value: "Tu saldo equivale a un descuento de {price}.",
    },
    products: {
        title: "Nuestro Catálogo",
        subtitle: "Encuentra tu aroma perfecto. Usa los filtros para descubrir nuestra selección."
    },
    filters: {
        title: "Filtros",
        clear: "Limpiar",
        search: "Búsqueda",
        search_placeholder: "Buscar productos...",
        sort_by: "Ordenar por",
        sort_placeholder: "Seleccionar orden",
        sort_options: {
            name_asc: "Nombre (A-Z)",
            name_desc: "Nombre (Z-A)",
            price_asc: "Precio (Menor a Mayor)",
            price_desc: "Precio (Mayor a Menor)"
        },
        categories: "Categorías",
        category_options: {
            novedad: "Novedades",
            oferta: "Ofertas",
            "mas-vendido": "Más Vendidos",
            pack: "Packs",
            accesorio: "Accesorios"
        },
        brands: "Marcas",
        size: "Tamaño",
        composition: "Composición"
    },
    product_card: {
        sold_out: "Agotado",
        offer: "OFERTA",
        notify_me: "Avísame",
        add_to_cart: "Añadir"
    },
    product_info: {
        secure_payment: "Compra segura y pago discreto garantizado.",
        fast_shipping: "Envío rápido en 24/48h a toda la península.",
        discreet_packaging: "Embalaje 100% discreto sin marcas externas."
    },
    product_details: {
        description_tab: "Descripción",
        details_tab: "Detalles del producto"
    },
    related_products: {
        title: "Productos Relacionados"
    },
    stock_notification: {
        dialog_title: "Notificación de Stock",
        dialog_description: "Recibirás un único correo cuando {product_name} vuelva a estar disponible.",
        error_title: "Error",
        error_missing_info: "Falta información del producto o el email. Inténtalo de nuevo.",
        error_generic: "No se pudo procesar tu solicitud.",
        error_unexpected: "Ocurrió un error inesperado.",
        success_title: "¡Te avisaremos!",
        success_description: "Recibirás un correo en {email} en cuanto {product_name} vuelva a estar disponible.",
        cancel_button: "Cancelar",
        submit_button: "Solicitar Notificación",
        sending_button: "Enviando..."
    },
    auth: {
      login_title: "Iniciar Sesión",
      login_subtitle: "Accede a tu cuenta para ver tus pedidos.",
      login_button: "Iniciar Sesión",
      logging_in_button: "Iniciando...",
      forgot_password_link: "¿Has olvidado tu contraseña?",
      no_account_prompt: "¿No tienes una cuenta?",
      register_link: "Regístrate",
      email_label: "Email",
      password_label: "Contraseña",
      register_title: "Crear Cuenta",
      register_subtitle: "Regístrate para una experiencia de compra más rápida.",
      register_button: "Registrarse",
      registering_button: "Creando cuenta...",
      confirm_password_label: "Confirmar Contraseña",
      password_strength_8_chars: "Al menos 8 caracteres",
      password_strength_uppercase: "Una letra mayúscula",
      password_strength_lowercase: "Una letra minúscula",
      password_strength_number: "Un número",
      password_strength_special: "Un carácter especial (!@#$...)",
      have_account_prompt: "¿Ya tienes una cuenta?",
      login_link: "Inicia Sesión",
      forgot_password_title: "Recuperar Contraseña",
      forgot_password_subtitle: "Introduce tu email y te enviaremos un enlace para restablecer tu contraseña.",
      forgot_password_success_subtitle: "Revisa tu bandeja de entrada (y la carpeta de spam).",
      send_recovery_link_button: "Enviar enlace de recuperación",
      sending_button: "Enviando...",
      back_to_login_button: "Volver a Iniciar Sesión",
      register_success_title: "¡Registro Completado!",
      register_success_subtitle: "¡Bienvenido/a, {name}! Tu cuenta ha sido creada con éxito.",
      register_success_description: "¿Qué te gustaría hacer ahora?",
      go_to_account_button: "Ir a mi Cuenta",
      continue_shopping_button: "Seguir Comprando"
    },
    pack_builder: {
      page_title: 'Crea tu Pack Personalizado',
      page_subtitle: 'Elige tus aromas favoritos de nuestro catálogo y construye el pack perfecto para ti.',
      step1_title: '1. Elige tus productos',
      products_in_pack: 'productos en tu pack',
      add_button: 'Añadir',
      step2_title: '2. Revisa tu pack',
      summary_title: 'Resumen del Pack',
      empty_pack_message: 'Selecciona productos de la izquierda para empezar a crear tu pack.',
      total_units: 'Unidades Totales',
      calculating_discount: 'Calculando descuento...',
      processing_payment: 'Procesando pago...',
      original_price: 'Precio Original',
      your_savings: 'Tu Ahorro',
      pack_total: 'Total del Pack',
      unlock_discount_message: 'Añade productos hasta superar 70€ para desbloquear descuentos.',
      buy_now_button: 'Comprar Pack Ahora',
      redirecting_button: 'Redirigiendo...',
      product_limit_title: 'Límite por producto',
      product_limit_desc: 'No puedes añadir más de {max} unidades del mismo producto.',
      sold_out_title: 'Producto Agotado',
      sold_out_desc: '{name} no está disponible actualmente.',
      stock_insufficient_title: 'Stock insuficiente',
      stock_insufficient_desc: 'Solo quedan {stock} unidades de {name}.',
      pack_limit_title: 'Límite del pack alcanzado',
      pack_limit_desc: 'No puedes añadir más de {max} productos a tu pack.',
      empty_pack_title: 'Pack vacío',
      empty_pack_desc: 'Añade al menos un producto para crear tu pack.',
      redirect_title: 'Redirigiendo al pago...',
      redirect_desc: 'Por favor, espera mientras preparamos tu compra segura.',
      checkout_error_title: 'Error en el Pago',
      checkout_error_desc: 'Ocurrió un error. Por favor, inténtalo de nuevo.',
    },
    popups: {
      age_verification_title: 'Verificación de Edad',
      age_verification_subtitle: 'Introduce tu fecha de nacimiento para continuar.',
      age_verification_exit_button: 'Salir',
      age_verification_enter_button: 'Entrar',
      age_verification_error_invalid: 'Por favor, introduce una fecha válida.',
      age_verification_error_underage: 'Debes ser mayor de {min_age} años para entrar.',
      welcome_title: '¡Bienvenido/a!',
      welcome_subtitle_part1: 'Suscríbete a nuestro boletín y obtén un',
      welcome_subtitle_discount: '10% de descuento',
      welcome_subtitle_part2: 'en tu primera compra.',
      welcome_open_offer_aria: 'Abrir oferta de suscripción',
    },
    notifications: {
      recent_purchase_title: '¡Compra Reciente!',
      recent_purchase_desc: '{name} de {location} acaba de comprar {quantity} x {product_name}.',
      real_order_title: '¡Pedido Real Confirmado!',
      a_city: 'una ciudad'
    },
    footer: {
      slogan: 'Tu tienda de confianza para aromas de calidad superior.',
      column_info: 'Información',
      column_guides: 'Guías',
      column_legal: 'Legal',
      column_help: 'Ayuda',
      link_legal_info: 'Información legal',
      link_terms: 'Términos y Condiciones',
      link_popper_sale: 'Venta de Popper',
      link_secure_payments: 'Pagos seguros',
      link_popper_info: 'Popper: todo lo que debes saber',
      link_leather_cleaners: 'Leather Cleaners Información',
      link_popper_shop: 'Tienda Popper',
      link_privacy: 'Privacidad y protección de datos',
      link_disputes: 'Resolución de litigios',
      link_cookies: 'Política de cookies',
      link_shipping: 'Envío y tarifas',
      link_contact: 'Contacte con nosotros',
      link_blog: 'Blog',
      link_docs: 'Docs del Sitio',
      copyright: 'Todos los derechos reservados.'
    },
    contact_page: {
        title: "Contacta con Nosotros",
        subtitle: "¿Tienes alguna pregunta o necesitas ayuda? Rellena el formulario y nuestro equipo se pondrá en contacto contigo.",
        email_card_title: "Email de Contacto",
        email_card_description: "Para consultas generales, envíanos un correo a:",
        legal_card_title: "Información Legal",
        legal_owner: "Titular",
        legal_address: "Dirección",
        form_card_title: "Enviar un mensaje",
        form_name: "Tu Nombre",
        form_name_placeholder: "John Doe",
        form_email: "Tu Email",
        form_email_placeholder: "tu@email.com",
        form_subject: "Asunto",
        form_subject_placeholder: "Consulta sobre un pedido",
        form_message: "Mensaje",
        form_message_placeholder: "Escribe tu consulta aquí...",
        form_submit_button: "Enviar Mensaje",
        form_sending_button: "Enviando...",
        success_toast_title: "¡Mensaje Enviado!",
        success_toast_description: "Gracias por contactarnos. Te responderemos lo antes posible.",
    },
     blog_page: {
      comments_title: 'Comentarios',
      no_comments: 'Sé el primero en comentar.',
      leave_comment_title: 'Deja un comentario',
      form_name_placeholder: 'Tu nombre',
      form_comment_placeholder: 'Escribe tu comentario...',
      form_submit_button: 'Enviar comentario'
    },
    shipping_page: {
      title: 'Envío y Tarifas',
      subtitle: 'En Popper Online nos esforzamos para que recibas tu pedido lo antes posible, con la máxima discreción y seguridad.',
      policy_title: 'Envío de tu Paquete',
      policy_desc: 'Hacemos todo lo posible para que recibas tu pedido rápidamente. Ten en cuenta los siguientes puntos:',
      policy_item1: 'Los pedidos realizados antes de las 12:00h se expiden el mismo día (excepto en periodos promocionales, festivos en Francia o alto volumen de pedidos).',
      policy_item2: 'Todos los pedidos se envían en un plazo de 24 horas laborables (L-V), excluyendo festivos.',
      policy_item3: 'Nuestros envíos son siempre discretos y anónimos, sin ninguna referencia al contenido o a nuestra tienda en el exterior del paquete.',
      rates_alert_title: 'Aviso Importante Sobre las Tarifas',
      rates_alert_desc: 'Las tarifas y transportistas que se muestran a continuación son orientativos y se basan en nuestros socios logísticos de referencia. El coste final del envío se calculará durante el proceso de pago y puede variar según las condiciones específicas del transportista en el momento de la compra.',
      rates_title: 'Tarifas de Envío',
      rates_subtitle: 'Gratis a partir de 39€ para Península Ibérica, Francia, Portugal, Alemania, Italia, Bélgica, Luxemburgo y Países Bajos.',
      domestic_title: 'España (Península), Francia, Portugal, Alemania, Italia, etc.',
      home_delivery: 'Envío a domicilio:',
      carrier: 'Transportista',
      rate: 'Tarifa',
      delivery_time: 'Plazo de Entrega',
      pickup_points: 'A puntos de recogida:',
      islands_title: 'Islas Baleares, Canarias, Ceuta y Melilla',
      islands_desc: 'Plazos sujetos a procedimientos aduaneros.',
      europe_title: 'Resto de Europa',
      europe_desc: 'A domicilio y puntos de recogida.',
      world_title: 'Envíos al Resto del Mundo',
      zone: 'Zona',
      world_rate: 'Tarifa (a domicilio con Chrono Express)',
      additional_info_title: 'Información Adicional',
      tracking_title: 'Seguimiento y Aviso de Entrega',
      tracking_desc: 'Recibirás un email con el número de seguimiento cuando tu pedido sea enviado. Si no estás en casa, el transportista dejará un aviso para organizar una nueva entrega o indicará el punto de recogida más cercano.',
      customs_title: 'Envíos Internacionales y Aduanas',
      customs_desc: 'Para pedidos fuera de la UE, es posible que se apliquen costes aduaneros. Popper Online no se hace responsable de estas tarifas, impuestos o derechos adicionales. Como cliente, actúas como importador y asumes la responsabilidad de estos costes.',
      final_note: 'Atención: Los plazos son indicativos y dependen del transportista. Direcciones incorrectas o causas de fuerza mayor (huelgas, etc.) pueden causar retrasos. Los costes de reenvío por dirección incorrecta o no recogida del paquete correrán a cargo del cliente.',
      explore_button: 'Explorar Catálogo'
    }
  },
  en: {
    header: {
      free_shipping: 'FREE +€40',
      fast_delivery: '24/48h',
      nav_menu: 'Navigation Menu',
      products: 'Products',
      create_pack: 'Create your Pack',
      monthly_dose: 'Monthly Dose'
    },
    cart: {
        title: "Shopping Cart",
        empty_title: "Your cart is empty",
        empty_subtitle: "Looks like you haven't added anything yet.",
        subtotal: "Subtotal",
        volume_discount: "Volume discount (with prepayment)",
        shipping_estimate: "Shipping (estimated)",
        total_estimate: "Estimated Total:",
        free_shipping_banner: "You have FREE shipping!",
        free_shipping_threshold: "Free shipping on orders over {price}",
        checkout_button: "Finalize Reservation",
        discreet_packaging: "100% discreet packaging.",
        notes: "Volume discount and final shipping costs will be applied on the checkout screen based on the chosen method.",
        item_added: "Added to cart",
        item_removed: "Product removed",
        item_unavailable: "Sold out",
        stock_limit_reached: "Stock limit reached",
    },
     account: {
        layout_title: "My Account",
        layout_description: "Manage your personal information, orders, and addresses.",
        sidebar_admin_panel: "Admin Panel",
        sidebar_dashboard: "User Dashboard",
        sidebar_orders: "Orders",
        sidebar_addresses: "Addresses",
        sidebar_subscription: "Monthly Dose",
        sidebar_logout: "Log Out",
        dashboard_title: "User Dashboard",
        dashboard_welcome: "Welcome back, {name}.",
        dashboard_profile_title: "Profile Information",
        dashboard_profile_subtitle: "Your personal data.",
        dashboard_profile_name: "Name:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Loyalty Points",
        dashboard_loyalty_subtitle: "Earn points with every purchase.",
        dashboard_loyalty_points: "Accumulated Points",
        dashboard_loyalty_value: "Your balance is equivalent to a discount of {price}.",
    },
    products: {
        title: "Our Catalog",
        subtitle: "Find your perfect scent. Use the filters to discover our selection."
    },
    filters: {
        title: "Filters",
        clear: "Clear",
        search: "Search",
        search_placeholder: "Search products...",
        sort_by: "Sort by",
        sort_placeholder: "Select order",
        sort_options: {
            name_asc: "Name (A-Z)",
            name_desc: "Name (Z-A)",
            price_asc: "Price (Low to High)",
            price_desc: "Price (High to Low)"
        },
        categories: "Categories",
        category_options: {
            novedad: "New Arrivals",
            oferta: "Offers",
            "mas-vendido": "Best Sellers",
            pack: "Packs",
            accesorio: "Accessories"
        },
        brands: "Brands",
        size: "Size",
        composition: "Composition"
    },
    product_card: {
        sold_out: "Sold Out",
        offer: "OFFER",
        notify_me: "Notify Me",
        add_to_cart: "Add"
    },
    product_info: {
        secure_payment: "Secure purchase and guaranteed discreet payment.",
        fast_shipping: "Fast shipping in 24/48h to the entire peninsula.",
        discreet_packaging: "100% discreet packaging with no external markings."
    },
    product_details: {
        description_tab: "Description",
        details_tab: "Product Details"
    },
    related_products: {
        title: "Related Products"
    },
    stock_notification: {
        dialog_title: "Stock Notification",
        dialog_description: "You will receive a single email when {product_name} is back in stock.",
        error_title: "Error",
        error_missing_info: "Missing product information or email. Please try again.",
        error_generic: "Could not process your request.",
        error_unexpected: "An unexpected error occurred.",
        success_title: "We'll notify you!",
        success_description: "You will receive an email at {email} as soon as {product_name} is available again.",
        cancel_button: "Cancel",
        submit_button: "Request Notification",
        sending_button: "Sending..."
    },
    auth: {
      login_title: "Login",
      login_subtitle: "Access your account to view your orders.",
      login_button: "Login",
      logging_in_button: "Logging in...",
      forgot_password_link: "Forgot your password?",
      no_account_prompt: "Don't have an account?",
      register_link: "Register",
      email_label: "Email",
      password_label: "Password",
      register_title: "Create Account",
      register_subtitle: "Register for a faster shopping experience.",
      register_button: "Register",
      registering_button: "Creating account...",
      confirm_password_label: "Confirm Password",
      password_strength_8_chars: "At least 8 characters",
      password_strength_uppercase: "One uppercase letter",
      password_strength_lowercase: "One lowercase letter",
      password_strength_number: "One number",
      password_strength_special: "One special character (!@#$...)",
      have_account_prompt: "Already have an account?",
      login_link: "Login",
      forgot_password_title: "Recover Password",
      forgot_password_subtitle: "Enter your email and we'll send you a link to reset your password.",
      forgot_password_success_subtitle: "Check your inbox (and spam folder).",
      send_recovery_link_button: "Send recovery link",
      sending_button: "Sending...",
      back_to_login_button: "Back to Login",
      register_success_title: "Registration Complete!",
      register_success_subtitle: "Welcome, {name}! Your account has been created successfully.",
      register_success_description: "What would you like to do now?",
      go_to_account_button: "Go to My Account",
      continue_shopping_button: "Continue Shopping"
    },
    pack_builder: {
      page_title: 'Create Your Custom Pack',
      page_subtitle: 'Choose your favorite scents from our catalog and build the perfect pack for you.',
      step1_title: '1. Choose your products',
      products_in_pack: 'products in your pack',
      add_button: 'Add',
      step2_title: '2. Review your pack',
      summary_title: 'Pack Summary',
      empty_pack_message: 'Select products from the left to start building your pack.',
      total_units: 'Total Units',
      calculating_discount: 'Calculating discount...',
      processing_payment: 'Processing payment...',
      original_price: 'Original Price',
      your_savings: 'Your Savings',
      pack_total: 'Pack Total',
      unlock_discount_message: 'Add products to exceed €70 to unlock discounts.',
      buy_now_button: 'Buy Pack Now',
      redirecting_button: 'Redirecting...',
      product_limit_title: 'Product Limit',
      product_limit_desc: 'You cannot add more than {max} units of the same product.',
      sold_out_title: 'Product Sold Out',
      sold_out_desc: '{name} is currently unavailable.',
      stock_insufficient_title: 'Insufficient Stock',
      stock_insufficient_desc: 'Only {stock} units of {name} are left.',
      pack_limit_title: 'Pack Limit Reached',
      pack_limit_desc: 'You cannot add more than {max} products to your pack.',
      empty_pack_title: 'Empty Pack',
      empty_pack_desc: 'Add at least one product to create your pack.',
      redirect_title: 'Redirecting to payment...',
      redirect_desc: 'Please wait while we prepare your secure purchase.',
      checkout_error_title: 'Payment Error',
      checkout_error_desc: 'An error occurred. Please try again.',
    },
    popups: {
      age_verification_title: 'Age Verification',
      age_verification_subtitle: 'Enter your date of birth to continue.',
      age_verification_exit_button: 'Exit',
      age_verification_enter_button: 'Enter',
      age_verification_error_invalid: 'Please enter a valid date.',
      age_verification_error_underage: 'You must be over {min_age} years old to enter.',
      welcome_title: 'Welcome!',
      welcome_subtitle_part1: 'Subscribe to our newsletter and get a',
      welcome_subtitle_discount: '10% discount',
      welcome_subtitle_part2: 'on your first purchase.',
      welcome_open_offer_aria: 'Open subscription offer',
    },
    notifications: {
      recent_purchase_title: 'Recent Purchase!',
      recent_purchase_desc: '{name} from {location} just bought {quantity} x {product_name}.',
      real_order_title: 'Real Order Confirmed!',
      a_city: 'a city'
    },
     footer: {
      slogan: 'Your trusted shop for premium quality aromas.',
      column_info: 'Information',
      column_guides: 'Guides',
      column_legal: 'Legal',
      column_help: 'Help',
      link_legal_info: 'Legal Information',
      link_terms: 'General Terms and Conditions',
      link_popper_sale: 'Popper Sale',
      link_secure_payments: 'Secure Payments',
      link_popper_info: 'Poppers: all you need to know',
      link_leather_cleaners: 'Leather Cleaners Information',
      link_popper_shop: 'Popper Shop',
      link_privacy: 'Privacy and Data Protection',
      link_disputes: 'Dispute Resolution',
      link_cookies: 'Cookie Policy',
      link_shipping: 'Shipping and Rates',
      link_contact: 'Contact Us',
      link_blog: 'Blog',
      link_docs: 'Site Docs',
      copyright: 'All rights reserved.'
    },
    contact_page: {
        title: "Contact Us",
        subtitle: "Have a question or need help? Fill out the form and our team will get in touch with you.",
        email_card_title: "Contact Email",
        email_card_description: "For general inquiries, send us an email at:",
        legal_card_title: "Legal Information",
        legal_owner: "Owner",
        legal_address: "Address",
        form_card_title: "Send a message",
        form_name: "Your Name",
        form_name_placeholder: "John Doe",
        form_email: "Your Email",
        form_email_placeholder: "you@email.com",
        form_subject: "Subject",
        form_subject_placeholder: "Inquiry about an order",
        form_message: "Message",
        form_message_placeholder: "Write your inquiry here...",
        form_submit_button: "Send Message",
        form_sending_button: "Sending...",
        success_toast_title: "Message Sent!",
        success_toast_description: "Thank you for contacting us. We will get back to you as soon as possible.",
    },
     blog_page: {
      comments_title: 'Comments',
      no_comments: 'Be the first to comment.',
      leave_comment_title: 'Leave a comment',
      form_name_placeholder: 'Your name',
      form_comment_placeholder: 'Write your comment...',
      form_submit_button: 'Post Comment'
    },
    shipping_page: {
      title: 'Shipping and Rates',
      subtitle: 'At Popper Online, we strive to get your order to you as quickly as possible, with maximum discretion and security.',
      policy_title: 'Your Package Shipment',
      policy_desc: 'We do our best to get your order to you quickly. Please note the following points:',
      policy_item1: 'Orders placed before 12:00 PM are shipped the same day (except during promotional periods, holidays in France, or high order volume).',
      policy_item2: 'All orders are shipped within 24 business hours (M-F), excluding holidays.',
      policy_item3: 'Our shipments are always discreet and anonymous, with no reference to the contents or our store on the outside of the package.',
      rates_alert_title: 'Important Notice About Rates',
      rates_alert_desc: 'The rates and carriers shown below are indicative and based on our reference logistics partners. The final shipping cost will be calculated during checkout and may vary depending on the specific conditions of the carrier at the time of purchase.',
      rates_title: 'Shipping Rates',
      rates_subtitle: 'Free from €39 for the Iberian Peninsula, France, Portugal, Germany, Italy, Belgium, Luxembourg, and the Netherlands.',
      domestic_title: 'Spain (Peninsula), France, Portugal, Germany, Italy, etc.',
      home_delivery: 'Home delivery:',
      carrier: 'Carrier',
      rate: 'Rate',
      delivery_time: 'Delivery Time',
      pickup_points: 'To pickup points:',
      islands_title: 'Balearic Islands, Canary Islands, Ceuta and Melilla',
      islands_desc: 'Times subject to customs procedures.',
      europe_title: 'Rest of Europe',
      europe_desc: 'Home and pickup point delivery.',
      world_title: 'Shipments to the Rest of the World',
      zone: 'Zone',
      world_rate: 'Rate (home delivery with Chrono Express)',
      additional_info_title: 'Additional Information',
      tracking_title: 'Tracking and Delivery Notice',
      tracking_desc: 'You will receive an email with the tracking number when your order is shipped. If you are not at home, the carrier will leave a notice to arrange a new delivery or indicate the nearest pickup point.',
      customs_title: 'International Shipments and Customs',
      customs_desc: 'For orders outside the EU, customs costs may apply. Popper Online is not responsible for these additional fees, taxes, or duties. As a customer, you act as the importer and assume responsibility for these costs.',
      final_note: 'Attention: Delivery times are indicative and depend on the carrier. Incorrect addresses or force majeure (strikes, etc.) can cause delays. The costs of reshipment due to an incorrect address or failure to pick up the package will be borne by the customer.',
      explore_button: 'Explore Catalog'
    }
  },
  fr: {
    header: {
      free_shipping: 'GRATUIT +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Menu de Navigation',
      products: 'Produits',
      create_pack: 'Créez votre Pack',
      monthly_dose: 'Dose Mensuelle'
    },
    cart: {
        title: "Panier d'achat",
        empty_title: "Votre panier est vide",
        empty_subtitle: "Il semble que vous n'ayez encore rien ajouté.",
        subtotal: "Sous-total",
        volume_discount: "Remise sur volume (avec prépaiement)",
        shipping_estimate: "Livraison (estimée)",
        total_estimate: "Total Estimé:",
        free_shipping_banner: "Vous bénéficiez de la livraison GRATUITE!",
        free_shipping_threshold: "Livraison gratuite pour les commandes de plus de {price}",
        checkout_button: "Finaliser la réservation",
        discreet_packaging: "Emballage 100% discret.",
        notes: "La remise sur le volume et les frais de port finaux seront appliqués sur l'écran de paiement en fonction de la méthode choisie.",
        item_added: "Ajouté au panier",
        item_removed: "Produit supprimé",
        item_unavailable: "Épuisé",
        stock_limit_reached: "Limite de stock atteinte",
    },
     account: {
        layout_title: "Mon Compte",
        layout_description: "Gérez vos informations personnelles, commandes et adresses.",
        sidebar_admin_panel: "Panel d'administration",
        sidebar_dashboard: "Tableau de bord",
        sidebar_orders: "Commandes",
        sidebar_addresses: "Adresses",
        sidebar_subscription: "Dose Mensuelle",
        sidebar_logout: "Se déconnecter",
        dashboard_title: "Tableau de bord",
        dashboard_welcome: "Content de vous revoir, {name}.",
        dashboard_profile_title: "Informations sur le profil",
        dashboard_profile_subtitle: "Vos données personnelles.",
        dashboard_profile_name: "Nom:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Points de fidélité",
        dashboard_loyalty_subtitle: "Gagnez des points à chaque achat.",
        dashboard_loyalty_points: "Points accumulés",
        dashboard_loyalty_value: "Votre solde équivaut à une remise de {price}.",
    },
    products: {
        title: "Notre Catalogue",
        subtitle: "Trouvez votre parfum parfait. Utilisez les filtres pour découvrir notre sélection."
    },
    filters: {
        title: "Filtres",
        clear: "Effacer",
        search: "Recherche",
        search_placeholder: "Rechercher des produits...",
        sort_by: "Trier par",
        sort_placeholder: "Sélectionner l'ordre",
        sort_options: {
            name_asc: "Nom (A-Z)",
            name_desc: "Nom (Z-A)",
            price_asc: "Prix (Croissant)",
            price_desc: "Prix (Décroissant)"
        },
        categories: "Catégories",
        category_options: {
            novedad: "Nouveautés",
            oferta: "Offres",
            "mas-vendido": "Meilleures ventes",
            pack: "Packs",
            accesorio: "Accessoires"
        },
        brands: "Marques",
        size: "Taille",
        composition: "Composition"
    },
    product_card: {
        sold_out: "Épuisé",
        offer: "OFFRE",
        notify_me: "Prévenez-moi",
        add_to_cart: "Ajouter"
    },
    product_info: {
        secure_payment: "Achat sécurisé et paiement discret garanti.",
        fast_shipping: "Livraison rapide en 24/48h dans toute la péninsule.",
        discreet_packaging: "Emballage 100% discret sans marques extérieures."
    },
    product_details: {
        description_tab: "Description",
        details_tab: "Détails du produit"
    },
    related_products: {
        title: "Produits Connexes"
    },
    stock_notification: {
        dialog_title: "Notification de Stock",
        dialog_description: "Vous recevrez un único e-mail lorsque {product_name} sera de nouveau disponible.",
        error_title: "Erreur",
        error_missing_info: "Informations sur le produit ou e-mail manquantes. Veuillez réessayer.",
        error_generic: "Impossible de traiter votre demande.",
        error_unexpected: "Une erreur inattendue s'est produite.",
        success_title: "Nous vous préviendrons!",
        success_description: "Vous recevrez un e-mail à {email} dès que {product_name} sera de nouveau disponible.",
        cancel_button: "Annuler",
        submit_button: "Demander une notification",
        sending_button: "Envoi en cours..."
    },
    auth: {
      login_title: "Se connecter",
      login_subtitle: "Accédez à votre compte pour voir vos commandes.",
      login_button: "Se connecter",
      logging_in_button: "Connexion en cours...",
      forgot_password_link: "Mot de passe oublié?",
      no_account_prompt: "Pas de compte?",
      register_link: "S'inscrire",
      email_label: "E-mail",
      password_label: "Mot de passe",
      register_title: "Créer un compte",
      register_subtitle: "Inscrivez-vous pour une expérience d'achat plus rapide.",
      register_button: "S'inscrire",
      registering_button: "Création du compte...",
      confirm_password_label: "Confirmez le mot de passe",
      password_strength_8_chars: "Au moins 8 caractères",
      password_strength_uppercase: "Une lettre majuscule",
      password_strength_lowercase: "Une lettre minuscule",
      password_strength_number: "Un chiffre",
      password_strength_special: "Un caractère spécial (!@#$...)",
      have_account_prompt: "Vous avez déjà un compte?",
      login_link: "Se connecter",
      forgot_password_title: "Récupérer le mot de passe",
      forgot_password_subtitle: "Entrez votre e-mail et nous vous enverrons un lien pour réinitialiser votre mot de passe.",
      forgot_password_success_subtitle: "Vérifiez votre boîte de réception (et le dossier spam).",
      send_recovery_link_button: "Envoyer le lien de récupération",
      sending_button: "Envoi en cours...",
      back_to_login_button: "Retour à la connexion",
      register_success_title: "Inscription terminée!",
      register_success_subtitle: "Bienvenue, {name}! Votre compte a été créé avec succès.",
      register_success_description: "Que souhaitez-vous faire maintenant?",
      go_to_account_button: "Aller à mon compte",
      continue_shopping_button: "Continuer les achats"
    },
    pack_builder: {
      page_title: 'Créez votre Pack Personnalisé',
      page_subtitle: 'Choisissez vos arômes préférés dans notre catalogue et composez le pack parfait pour vous.',
      step1_title: '1. Choisissez vos produits',
      products_in_pack: 'produits dans votre pack',
      add_button: 'Ajouter',
      step2_title: '2. Vérifiez votre pack',
      summary_title: 'Résumé du Pack',
      empty_pack_message: 'Sélectionnez des produits à gauche pour commencer à composer votre pack.',
      total_units: 'Unités Totales',
      calculating_discount: 'Calcul de la réduction...',
      processing_payment: 'Traitement du paiement...',
      original_price: 'Prix Original',
      your_savings: 'Vos Économies',
      pack_total: 'Total du Pack',
      unlock_discount_message: 'Ajoutez des produits pour dépasser 70€ afin de débloquer les réductions.',
      buy_now_button: 'Acheter le Pack Maintenant',
      redirecting_button: 'Redirection...',
      product_limit_title: 'Limite par produit',
      product_limit_desc: 'Vous ne pouvez pas ajouter plus de {max} unités du même produit.',
      sold_out_title: 'Produit Épuisé',
      sold_out_desc: '{name} est actuellement indisponible.',
      stock_insufficient_title: 'Stock insuffisant',
      stock_insufficient_desc: 'Il ne reste que {stock} unités de {name}.',
      pack_limit_title: 'Limite du pack atteinte',
      pack_limit_desc: 'Vous ne pouvez pas ajouter plus de {max} produits à votre pack.',
      empty_pack_title: 'Pack vide',
      empty_pack_desc: 'Ajoutez au moins un produit pour créer votre pack.',
      redirect_title: 'Redirection vers le paiement...',
      redirect_desc: 'Veuillez patienter pendant que nous préparons votre achat sécurisé.',
      checkout_error_title: 'Erreur de Paiement',
      checkout_error_desc: 'Une erreur est survenue. Veuillez réessayer.',
    },
    popups: {
      age_verification_title: 'Vérification de l\'âge',
      age_verification_subtitle: 'Entrez votre date de naissance pour continuer.',
      age_verification_exit_button: 'Sortir',
      age_verification_enter_button: 'Entrer',
      age_verification_error_invalid: 'Veuillez entrer une date valide.',
      age_verification_error_underage: 'Vous devez avoir plus de {min_age} ans pour entrer.',
      welcome_title: 'Bienvenue!',
      welcome_subtitle_part1: 'Abonnez-vous à notre newsletter et obtenez une',
      welcome_subtitle_discount: 'remise de 10%',
      welcome_subtitle_part2: 'sur votre premier achat.',
      welcome_open_offer_aria: 'Ouvrir l\'offre d\'abonnement',
    },
    notifications: {
      recent_purchase_title: 'Achat Récent!',
      recent_purchase_desc: '{name} de {location} vient d\'acheter {quantity} x {product_name}.',
      real_order_title: 'Commande Réelle Confirmée!',
      a_city: 'une ville'
    },
    footer: {
      slogan: 'Votre boutique de confiance pour des arômes de qualité supérieure.',
      column_info: 'Informations',
      column_guides: 'Guides',
      column_legal: 'Légal',
      column_help: 'Aide',
      link_legal_info: 'Informations légales',
      link_terms: 'Conditions Générales',
      link_popper_sale: 'Vente de Popper',
      link_secure_payments: 'Paiements sécurisés',
      link_popper_info: 'Poppers: tout ce que vous devez savoir',
      link_leather_cleaners: 'Informations sur les Nettoyants pour Cuir',
      link_popper_shop: 'Boutique Popper',
      link_privacy: 'Confidentialité et protection des données',
      link_disputes: 'Résolution des litiges',
      link_cookies: 'Politique de cookies',
      link_shipping: 'Expédition et tarifs',
      link_contact: 'Contactez-nous',
      link_blog: 'Blog',
      link_docs: 'Docs du Site',
      copyright: 'Tous droits réservés.'
    },
    contact_page: {
        title: "Contactez-nous",
        subtitle: "Avez-vous une question ou besoin d'aide? Remplissez le formulaire et notre équipe vous contactera.",
        email_card_title: "Email de Contact",
        email_card_description: "Pour des questions générales, envoyez-nous un email à:",
        legal_card_title: "Informations Légales",
        legal_owner: "Propriétaire",
        legal_address: "Adresse",
        form_card_title: "Envoyer un message",
        form_name: "Votre Nom",
        form_name_placeholder: "Jean Dupont",
        form_email: "Votre Email",
        form_email_placeholder: "vous@email.com",
        form_subject: "Sujet",
        form_subject_placeholder: "Question sur une commande",
        form_message: "Message",
        form_message_placeholder: "Écrivez votre question ici...",
        form_submit_button: "Envoyer le Message",
        form_sending_button: "Envoi en cours...",
        success_toast_title: "Message Envoyé!",
        success_toast_description: "Merci de nous avoir contactés. Nous vous répondrons dès que possible.",
    },
     blog_page: {
      comments_title: 'Commentaires',
      no_comments: 'Soyez le premier à commenter.',
      leave_comment_title: 'Laissez un commentaire',
      form_name_placeholder: 'Votre nom',
      form_comment_placeholder: 'Écrivez votre commentaire...',
      form_submit_button: 'Publier le commentaire'
    },
    shipping_page: {
      title: 'Expédition et Tarifs',
      subtitle: 'Chez Popper Online, nous nous efforçons de vous livrer votre commande le plus rapidement possible, avec la plus grande discrétion et sécurité.',
      policy_title: 'Expédition de votre Colis',
      policy_desc: 'Nous mettons tout en œuvre pour que vous receviez votre commande rapidement. Veuillez noter les points suivants :',
      policy_item1: 'Les commandes passées avant 12h00 sont expédiées le jour même (sauf pendant les périodes promotionnelles, les jours fériés en France ou en cas de volume de commandes élevé).',
      policy_item2: 'Toutes les commandes sont expédiées dans les 24 heures ouvrables (L-V), hors jours fériés.',
      policy_item3: 'Nos envois sont toujours discrets et anonymes, sans aucune référence au contenu ou à notre boutique à l\'extérieur du colis.',
      rates_alert_title: 'Avis Important sur les Tarifs',
      rates_alert_desc: 'Les tarifs et transporteurs indiqués ci-dessous sont indicatifs et basés sur nos partenaires logistiques de référence. Le coût final de l\'expédition sera calculé lors du paiement et peut varier en fonction des conditions spécifiques du transporteur au moment de l\'achat.',
      rates_title: 'Tarifs d\'Expédition',
      rates_subtitle: 'Gratuit à partir de 39€ pour la Péninsule Ibérique, la France, le Portugal, l\'Allemagne, l\'Italie, la Belgique, le Luxembourg et les Pays-Bas.',
      domestic_title: 'Espagne (Péninsule), France, Portugal, Allemagne, Italie, etc.',
      home_delivery: 'Livraison à domicile :',
      carrier: 'Transporteur',
      rate: 'Tarif',
      delivery_time: 'Délai de Livraison',
      pickup_points: 'En points de collecte :',
      islands_title: 'Îles Baléares, Canaries, Ceuta et Melilla',
      islands_desc: 'Délais soumis aux procédures douanières.',
      europe_title: 'Reste de l\'Europe',
      europe_desc: 'Livraison à domicile et en points de collecte.',
      world_title: 'Expéditions vers le Reste du Monde',
      zone: 'Zone',
      world_rate: 'Tarif (livraison à domicile avec Chrono Express)',
      additional_info_title: 'Informations Supplémentaires',
      tracking_title: 'Suivi et Avis de Passage',
      tracking_desc: 'Vous recevrez un e-mail avec le numéro de suivi lorsque votre commande sera expédiée. Si vous n\'êtes pas chez vous, le transporteur laissera un avis de passage pour organiser une nouvelle livraison ou indiquera le point de collecte le plus proche.',
      customs_title: 'Envois Internationaux et Douanes',
      customs_desc: 'Pour les commandes hors UE, des frais de douane peuvent s\'appliquer. Popper Online n\'est pas responsable de ces frais, taxes ou droits supplémentaires. En tant que client, vous agissez en tant qu\'importateur et assumez la responsabilité de ces coûts.',
      final_note: 'Attention : Les délais sont indicatifs et dépendent du transporteur. Des adresses incorrectes ou des cas de force majeure (grèves, etc.) peuvent entraîner des retards. Les frais de réexpédition pour une adresse incorrecte ou un colis non réclamé seront à la charge du client.',
      explore_button: 'Explorer le Catalogue'
    }
  },
  de: {
    header: {
      free_shipping: 'GRATIS +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Navigationsmenü',
      products: 'Produkte',
      create_pack: 'Ihr Paket erstellen',
      monthly_dose: 'Monatsdosis'
    },
    cart: {
        title: "Warenkorb",
        empty_title: "Ihr Warenkorb ist leer",
        empty_subtitle: "Sieht aus, als hättest du noch nichts hinzugefügt.",
        subtotal: "Zwischensumme",
        volume_discount: "Mengenrabatt (bei Vorauszahlung)",
        shipping_estimate: "Versand (geschätzt)",
        total_estimate: "Geschätzte Summe:",
        free_shipping_banner: "Sie haben KOSTENLOSEN Versand!",
        free_shipping_threshold: "Kostenloser Versand bei Bestellungen über {price}",
        checkout_button: "Reservierung abschließen",
        discreet_packaging: "100% diskrete Verpackung.",
        notes: "Mengenrabatt und endgültige Versandkosten werden auf dem Checkout-Bildschirm basierend auf der gewählten Methode angewendet.",
        item_added: "Zum Warenkorb hinzugefügt",
        item_removed: "Produkt entfernt",
        item_unavailable: "Ausverkauft",
        stock_limit_reached: "Bestandslimit erreicht",
    },
     account: {
        layout_title: "Mein Konto",
        layout_description: "Verwalten Sie Ihre persönlichen Informationen, Bestellungen und Adressen.",
        sidebar_admin_panel: "Admin-Panel",
        sidebar_dashboard: "Benutzer-Dashboard",
        sidebar_orders: "Bestellungen",
        sidebar_addresses: "Adressen",
        sidebar_subscription: "Monatliche Dosis",
        sidebar_logout: "Ausloggen",
        dashboard_title: "Benutzer-Dashboard",
        dashboard_welcome: "Willkommen zurück, {name}.",
        dashboard_profile_title: "Profilinformationen",
        dashboard_profile_subtitle: "Ihre persönlichen Daten.",
        dashboard_profile_name: "Name:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Treuepunkte",
        dashboard_loyalty_subtitle: "Sammeln Sie bei jedem Einkauf Punkte.",
        dashboard_loyalty_points: "Gesammelte Punkte",
        dashboard_loyalty_value: "Ihr Guthaben entspricht einem Rabatt von {price}.",
    },
    products: {
        title: "Unser Katalog",
        subtitle: "Finden Sie Ihren perfekten Duft. Nutzen Sie die Filter, um unsere Auswahl zu entdecken."
    },
    filters: {
        title: "Filter",
        clear: "Löschen",
        search: "Suchen",
        search_placeholder: "Produkte suchen...",
        sort_by: "Sortieren nach",
        sort_placeholder: "Reihenfolge auswählen",
        sort_options: {
            name_asc: "Name (A-Z)",
            name_desc: "Name (Z-A)",
            price_asc: "Preis (Aufsteigend)",
            price_desc: "Preis (Absteigend)"
        },
        categories: "Kategorien",
        category_options: {
            novedad: "Neuheiten",
            oferta: "Angebote",
            "mas-vendido": "Bestseller",
            pack: "Pakete",
            accesorio: "Zubehör"
        },
        brands: "Marken",
        size: "Größe",
        composition: "Zusammensetzung"
    },
    product_card: {
        sold_out: "Ausverkauft",
        offer: "ANGEBOT",
        notify_me: "Benachrichtigen",
        add_to_cart: "Hinzufügen"
    },
    product_info: {
        secure_payment: "Sicherer Kauf und garantierte diskrete Zahlung.",
        fast_shipping: "Schneller Versand in 24/48h auf die gesamte Halbinsel.",
        discreet_packaging: "100% diskrete Verpackung ohne äußere Kennzeichnungen."
    },
    product_details: {
        description_tab: "Beschreibung",
        details_tab: "Produktdetails"
    },
    related_products: {
        title: "Ähnliche Produkte"
    },
    stock_notification: {
        dialog_title: "Bestandsbenachrichtigung",
        dialog_description: "Sie erhalten eine einzige E-Mail, wenn {product_name} wieder auf Lager ist.",
        error_title: "Fehler",
        error_missing_info: "Fehlende Produktinformationen oder E-Mail. Bitte versuchen Sie es erneut.",
        error_generic: "Ihre Anfrage konnte nicht bearbeitet werden.",
        error_unexpected: "Ein unerwarteter Fehler ist aufgetreten.",
        success_title: "Wir benachrichtigen Sie!",
        success_description: "Sie erhalten eine E-Mail an {email}, sobald {product_name} wieder verfügbar ist.",
        cancel_button: "Abbrechen",
        submit_button: "Benachrichtigung anfordern",
        sending_button: "Senden..."
    },
    auth: {
      login_title: "Anmelden",
      login_subtitle: "Greifen Sie auf Ihr Konto zu, um Ihre Bestellungen anzuzeigen.",
      login_button: "Anmelden",
      logging_in_button: "Anmelden...",
      forgot_password_link: "Passwort vergessen?",
      no_account_prompt: "Kein Konto?",
      register_link: "Registrieren",
      email_label: "E-Mail",
      password_label: "Passwort",
      register_title: "Konto erstellen",
      register_subtitle: "Registrieren Sie sich für ein schnelleres Einkaufserlebnis.",
      register_button: "Registrieren",
      registering_button: "Konto wird erstellt...",
      confirm_password_label: "Passwort bestätigen",
      password_strength_8_chars: "Mindestens 8 Zeichen",
      password_strength_uppercase: "Ein Großbuchstabe",
      password_strength_lowercase: "Ein Kleinbuchstabe",
      password_strength_number: "Eine Zahl",
      password_strength_special: "Ein Sonderzeichen (!@#$...)",
      have_account_prompt: "Haben Sie bereits ein Konto?",
      login_link: "Anmelden",
      forgot_password_title: "Passwort wiederherstellen",
      forgot_password_subtitle: "Geben Sie Ihre E-Mail-Adresse ein und wir senden Ihnen einen Link zum Zurücksetzen Ihres Passworts.",
      forgot_password_success_subtitle: "Überprüfen Sie Ihren Posteingang (und den Spam-Ordner).",
      send_recovery_link_button: "Link zur Wiederherstellung senden",
      sending_button: "Senden...",
      back_to_login_button: "Zurück zur Anmeldung",
      register_success_title: "Registrierung abgeschlossen!",
      register_success_subtitle: "Willkommen, {name}! Ihr Konto wurde erfolgreich erstellt.",
      register_success_description: "Was möchten Sie jetzt tun?",
      go_to_account_button: "Zu meinem Konto",
      continue_shopping_button: "Weiter einkaufen"
    },
    pack_builder: {
      page_title: 'Erstellen Sie Ihr individuelles Paket',
      page_subtitle: 'Wählen Sie Ihre Lieblingsdüfte aus unserem Katalog und stellen Sie sich das perfekte Paket zusammen.',
      step1_title: '1. Wählen Sie Ihre Produkte',
      products_in_pack: 'Produkte in Ihrem Paket',
      add_button: 'Hinzufügen',
      step2_title: '2. Überprüfen Sie Ihr Paket',
      summary_title: 'Paketübersicht',
      empty_pack_message: 'Wählen Sie Produkte von links aus, um mit dem Zusammenstellen Ihres Pakets zu beginnen.',
      total_units: 'Gesamteinheiten',
      calculating_discount: 'Rabatt wird berechnet...',
      processing_payment: 'Zahlung wird verarbeitet...',
      original_price: 'Originalpreis',
      your_savings: 'Ihre Ersparnis',
      pack_total: 'Paket-Gesamtpreis',
      unlock_discount_message: 'Fügen Sie Produkte hinzu, um 70 € zu überschreiten, um Rabatte freizuschalten.',
      buy_now_button: 'Paket jetzt kaufen',
      redirecting_button: 'Weiterleitung...',
      product_limit_title: 'Produktlimit',
      product_limit_desc: 'Sie können nicht mehr als {max} Einheiten desselben Produkts hinzufügen.',
      sold_out_title: 'Produkt ausverkauft',
      sold_out_desc: '{name} ist derzeit nicht verfügbar.',
      stock_insufficient_title: 'Ungenügender Bestand',
      stock_insufficient_desc: 'Es sind nur noch {stock} Einheiten von {name} übrig.',
      pack_limit_title: 'Paketlimit erreicht',
      pack_limit_desc: 'Sie können nicht mehr als {max} Produkte zu Ihrem Paket hinzufügen.',
      empty_pack_title: 'Leeres Paket',
      empty_pack_desc: 'Fügen Sie mindestens ein Produkt hinzu, um Ihr Paket zu erstellen.',
      redirect_title: 'Weiterleitung zur Zahlung...',
      redirect_desc: 'Bitte warten Sie, während wir Ihren sicheren Kauf vorbereiten.',
      checkout_error_title: 'Zahlungsfehler',
      checkout_error_desc: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    },
    popups: {
      age_verification_title: 'Altersüberprüfung',
      age_verification_subtitle: 'Geben Sie Ihr Geburtsdatum ein, um fortzufahren.',
      age_verification_exit_button: 'Verlassen',
      age_verification_enter_button: 'Eintreten',
      age_verification_error_invalid: 'Bitte geben Sie ein gültiges Datum ein.',
      age_verification_error_underage: 'Sie müssen über {min_age} Jahre alt sein, um eintreten zu dürfen.',
      welcome_title: 'Willkommen!',
      welcome_subtitle_part1: 'Abonnieren Sie unseren Newsletter und erhalten Sie einen',
      welcome_subtitle_discount: '10% Rabatt',
      welcome_subtitle_part2: 'auf Ihren ersten Einkauf.',
      welcome_open_offer_aria: 'Abonnementangebot öffnen',
    },
    notifications: {
      recent_purchase_title: 'Neuer Kauf!',
      recent_purchase_desc: '{name} aus {location} hat gerade {quantity} x {product_name} gekauft.',
      real_order_title: 'Echte Bestellung bestätigt!',
      a_city: 'einer Stadt'
    },
     footer: {
      slogan: 'Ihr vertrauenswürdiger Shop für hochwertige Aromen.',
      column_info: 'Informationen',
      column_guides: 'Anleitungen',
      column_legal: 'Rechtliches',
      column_help: 'Hilfe',
      link_legal_info: 'Rechtliche Informationen',
      link_terms: 'Allgemeine Geschäftsbedingungen',
      link_popper_sale: 'Popper-Verkauf',
      link_secure_payments: 'Sichere Zahlungen',
      link_popper_info: 'Poppers: alles, was Sie wissen müssen',
      link_leather_cleaners: 'Informationen zu Lederreinigern',
      link_popper_shop: 'Popper-Shop',
      link_privacy: 'Datenschutz',
      link_disputes: 'Streitbeilegung',
      link_cookies: 'Cookie-Richtlinie',
      link_shipping: 'Versand und Tarife',
      link_contact: 'Kontaktieren Sie uns',
      link_blog: 'Blog',
      link_docs: 'Website-Dokumentation',
      copyright: 'Alle Rechte vorbehalten.'
    },
    contact_page: {
        title: "Kontaktieren Sie uns",
        subtitle: "Haben Sie eine Frage oder benötigen Sie Hilfe? Füllen Sie das Formular aus und unser Team wird sich mit Ihnen in Verbindung setzen.",
        email_card_title: "Kontakt-E-Mail",
        email_card_description: "Für allgemeine Anfragen senden Sie uns eine E-Mail an:",
        legal_card_title: "Rechtliche Informationen",
        legal_owner: "Inhaber",
        legal_address: "Adresse",
        form_card_title: "Eine Nachricht senden",
        form_name: "Ihr Name",
        form_name_placeholder: "Max Mustermann",
        form_email: "Ihre E-Mail",
        form_email_placeholder: "sie@email.de",
        form_subject: "Betreff",
        form_subject_placeholder: "Anfrage zu einer Bestellung",
        form_message: "Nachricht",
        form_message_placeholder: "Schreiben Sie Ihre Anfrage hier...",
        form_submit_button: "Nachricht senden",
        form_sending_button: "Senden...",
        success_toast_title: "Nachricht gesendet!",
        success_toast_description: "Danke, dass Sie uns kontaktiert haben. Wir werden uns so schnell wie möglich bei Ihnen melden.",
    },
     blog_page: {
      comments_title: 'Kommentare',
      no_comments: 'Seien Sie der Erste, der einen Kommentar abgibt.',
      leave_comment_title: 'Einen Kommentar hinterlassen',
      form_name_placeholder: 'Ihr Name',
      form_comment_placeholder: 'Schreiben Sie Ihren Kommentar...',
      form_submit_button: 'Kommentar posten'
    },
    shipping_page: {
      title: 'Versand und Tarife',
      subtitle: 'Bei Popper Online bemühen wir uns, Ihre Bestellung so schnell wie möglich, mit maximaler Diskretion und Sicherheit, zu Ihnen zu bringen.',
      policy_title: 'Versand Ihres Pakets',
      policy_desc: 'Wir tun unser Bestes, um Ihre Bestellung schnell zu Ihnen zu bringen. Bitte beachten Sie die folgenden Punkte:',
      policy_item1: 'Bestellungen, die vor 12:00 Uhr aufgegeben werden, werden noch am selben Tag versendet (außer während Aktionszeiträumen, Feiertagen in Frankreich oder bei hohem Bestellaufkommen).',
      policy_item2: 'Alle Bestellungen werden innerhalb von 24 Geschäftsstunden (Mo-Fr), ausgenommen Feiertage, versendet.',
      policy_item3: 'Unsere Sendungen sind immer diskret und anonym, ohne Hinweis auf den Inhalt oder unseren Shop auf der Außenseite des Pakets.',
      rates_alert_title: 'Wichtiger Hinweis zu den Tarifen',
      rates_alert_desc: 'Die unten gezeigten Tarife und Spediteure sind Richtwerte und basieren auf unseren Referenzlogistikpartnern. Die endgültigen Versandkosten werden während des Bezahlvorgangs berechnet und können je nach den spezifischen Bedingungen des Spediteurs zum Zeitpunkt des Kaufs variieren.',
      rates_title: 'Versandtarife',
      rates_subtitle: 'Kostenlos ab 39 € für die Iberische Halbinsel, Frankreich, Portugal, Deutschland, Italien, Belgien, Luxemburg und die Niederlande.',
      domestic_title: 'Spanien (Festland), Frankreich, Portugal, Deutschland, Italien, etc.',
      home_delivery: 'Hauszustellung:',
      carrier: 'Spediteur',
      rate: 'Tarif',
      delivery_time: 'Lieferzeit',
      pickup_points: 'Zu Abholpunkten:',
      islands_title: 'Balearen, Kanarische Inseln, Ceuta und Melilla',
      islands_desc: 'Zeiten unterliegen den Zollverfahren.',
      europe_title: 'Restliches Europa',
      europe_desc: 'Zustellung nach Hause und zu Abholpunkten.',
      world_title: 'Versand in den Rest der Welt',
      zone: 'Zone',
      world_rate: 'Tarif (Hauszustellung mit Chrono Express)',
      additional_info_title: 'Zusätzliche Informationen',
      tracking_title: 'Sendungsverfolgung und Zustellbenachrichtigung',
      tracking_desc: 'Sie erhalten eine E-Mail mit der Sendungsverfolgungsnummer, wenn Ihre Bestellung versendet wird. Wenn Sie nicht zu Hause sind, hinterlässt der Spediteur eine Benachrichtigung, um eine neue Zustellung zu vereinbaren oder den nächstgelegenen Abholpunkt anzugeben.',
      customs_title: 'Internationale Sendungen und Zoll',
      customs_desc: 'Für Bestellungen außerhalb der EU können Zollkosten anfallen. Popper Online ist nicht verantwortlich für diese zusätzlichen Gebühren, Steuern oder Zölle. Als Kunde handeln Sie als Importeur und übernehmen die Verantwortung für diese Kosten.',
      final_note: 'Achtung: Die Lieferzeiten sind Richtwerte und hängen vom Spediteur ab. Falsche Adressen oder höhere Gewalt (Streiks usw.) können zu Verzögerungen führen. Die Kosten für eine erneute Zustellung aufgrund einer falschen Adresse oder Nichtabholung des Pakets trägt der Kunde.',
      explore_button: 'Katalog durchsuchen'
    }
  },
  it: {
    header: {
      free_shipping: 'GRATIS +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Menu di Navigazione',
      products: 'Prodotti',
      create_pack: 'Crea il tuo Pack',
      monthly_dose: 'Dose Mensile'
    },
    cart: {
        title: "Carrello",
        empty_title: "Il tuo carrello è vuoto",
        empty_subtitle: "Sembra che tu non abbia ancora aggiunto nulla.",
        subtotal: "Subtotale",
        volume_discount: "Sconto volume (con pagamento anticipato)",
        shipping_estimate: "Spedizione (stimata)",
        total_estimate: "Totale Stimato:",
        free_shipping_banner: "Hai la spedizione GRATUITA!",
        free_shipping_threshold: "Spedizione gratuita per ordini superiori a {price}",
        checkout_button: "Finalizza Prenotazione",
        discreet_packaging: "Imballaggio 100% discreto.",
        notes: "Lo sconto sul volume e le spese di spedizione finali verranno applicati nella schermata di pagamento in base al metodo scelto.",
        item_added: "Aggiunto al carrello",
        item_removed: "Prodotto rimosso",
        item_unavailable: "Esaurito",
        stock_limit_reached: "Limite di magazzino raggiunto",
    },
     account: {
        layout_title: "Il mio account",
        layout_description: "Gestisci le tue informazioni personali, ordini e indirizzi.",
        sidebar_admin_panel: "Pannello di amministrazione",
        sidebar_dashboard: "Cruscotto utente",
        sidebar_orders: "Ordini",
        sidebar_addresses: "Indirizzi",
        sidebar_subscription: "Dose mensile",
        sidebar_logout: "Disconnettersi",
        dashboard_title: "Cruscotto utente",
        dashboard_welcome: "Bentornato, {name}.",
        dashboard_profile_title: "Informazioni sul profilo",
        dashboard_profile_subtitle: "I tuoi dati personali.",
        dashboard_profile_name: "Nome:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Punti fedeltà",
        dashboard_loyalty_subtitle: "Guadagna punti con ogni acquisto.",
        dashboard_loyalty_points: "Punti accumulati",
        dashboard_loyalty_value: "Il tuo saldo equivale a uno sconto di {price}.",
    },
    products: {
        title: "Il Nostro Catalogo",
        subtitle: "Trova il tuo profumo perfetto. Usa i filtri per scoprire la nostra selezione."
    },
    filters: {
        title: "Filtri",
        clear: "Cancella",
        search: "Cerca",
        search_placeholder: "Cerca prodotti...",
        sort_by: "Ordina per",
        sort_placeholder: "Seleziona ordine",
        sort_options: {
            name_asc: "Nome (A-Z)",
            name_desc: "Nome (Z-A)",
            price_asc: "Prezzo (Crescente)",
            price_desc: "Prezzo (Decrescente)"
        },
        categories: "Categorie",
        category_options: {
            novedad: "Novità",
            oferta: "Offerte",
            "mas-vendido": "Più venduti",
            pack: "Pack",
            accesorio: "Accessori"
        },
        brands: "Marche",
        size: "Dimensione",
        composition: "Composizione"
    },
    product_card: {
        sold_out: "Esaurito",
        offer: "OFFERTA",
        notify_me: "Avvisami",
        add_to_cart: "Aggiungi"
    },
    product_info: {
        secure_payment: "Acquisto sicuro e pagamento discreto garantito.",
        fast_shipping: "Spedizione rapida in 24/48h in tutta la penisola.",
        discreet_packaging: "Imballaggio 100% discreto senza marchi esterni."
    },
    product_details: {
        description_tab: "Descrizione",
        details_tab: "Dettagli del prodotto"
    },
    related_products: {
        title: "Prodotti Correlati"
    },
    stock_notification: {
        dialog_title: "Notifica di Disponibilità",
        dialog_description: "Riceverai una sola email quando {product_name} tornerà disponibile.",
        error_title: "Errore",
        error_missing_info: "Mancano informazioni sul prodotto o l'email. Riprova.",
        error_generic: "Impossibile elaborare la tua richiesta.",
        error_unexpected: "Si è verificato un errore imprevisto.",
        success_title: "Ti avviseremo!",
        success_description: "Riceverai un'email a {email} non appena {product_name} sarà di nuovo disponibile.",
        cancel_button: "Annulla",
        submit_button: "Richiedi notifica",
        sending_button: "Invio in corso..."
    },
    auth: {
      login_title: "Accedi",
      login_subtitle: "Accedi al tuo account per visualizzare i tuoi ordini.",
      login_button: "Accedi",
      logging_in_button: "Accesso in corso...",
      forgot_password_link: "Password dimenticata?",
      no_account_prompt: "Non hai un account?",
      register_link: "Registrati",
      email_label: "E-mail",
      password_label: "Password",
      register_title: "Crea account",
      register_subtitle: "Registrati per un'esperienza di acquisto più veloce.",
      register_button: "Registrati",
      registering_button: "Creazione account in corso...",
      confirm_password_label: "Conferma password",
      password_strength_8_chars: "Almeno 8 caratteri",
      password_strength_uppercase: "Una lettera maiuscola",
      password_strength_lowercase: "Una lettera minuscola",
      password_strength_number: "Un numero",
      password_strength_special: "Un carattere speciale (!@#$...)",
      have_account_prompt: "Hai già un account?",
      login_link: "Accedi",
      forgot_password_title: "Recupera password",
      forgot_password_subtitle: "Inserisci la tua e-mail e ti invieremo un link per reimpostare la password.",
      forgot_password_success_subtitle: "Controlla la tua casella di posta (e la cartella spam).",
      send_recovery_link_button: "Invia link di recupero",
      sending_button: "Invio in corso...",
      back_to_login_button: "Torna al login",
      register_success_title: "Registrazione completata!",
      register_success_subtitle: "Benvenuto, {name}! Il tuo account è stato creato con successo.",
      register_success_description: "Cosa vorresti fare ora?",
      go_to_account_button: "Vai al mio account",
      continue_shopping_button: "Continua lo shopping"
    },
    pack_builder: {
      page_title: 'Crea il tuo Pack Personalizzato',
      page_subtitle: 'Scegli i tuoi profumi preferiti dal nostro catalogo e componi il pack perfetto per te.',
      step1_title: '1. Scegli i tuoi prodotti',
      products_in_pack: 'prodotti nel tuo pack',
      add_button: 'Aggiungi',
      step2_title: '2. Controlla il tuo pack',
      summary_title: 'Riepilogo del Pack',
      empty_pack_message: 'Seleziona i prodotti a sinistra per iniziare a comporre il tuo pack.',
      total_units: 'Unità Totali',
      calculating_discount: 'Calcolo dello sconto...',
      processing_payment: 'Elaborazione del pagamento...',
      original_price: 'Prezzo Originale',
      your_savings: 'Il Tuo Risparmio',
      pack_total: 'Totale del Pack',
      unlock_discount_message: 'Aggiungi prodotti per superare 70€ e sbloccare gli sconti.',
      buy_now_button: 'Acquista il Pack Ora',
      redirecting_button: 'Reindirizzamento...',
      product_limit_title: 'Limite per prodotto',
      product_limit_desc: 'Non puoi aggiungere più di {max} unità dello stesso prodotto.',
      sold_out_title: 'Prodotto Esaurito',
      sold_out_desc: '{name} non è attualmente disponibile.',
      stock_insufficient_title: 'Scorte insufficienti',
      stock_insufficient_desc: 'Sono rimaste solo {stock} unità di {name}.',
      pack_limit_title: 'Limite del pack raggiunto',
      pack_limit_desc: 'Non puoi aggiungere più di {max} prodotti al tuo pack.',
      empty_pack_title: 'Pack vuoto',
      empty_pack_desc: 'Aggiungi almeno un prodotto per creare il tuo pack.',
      redirect_title: 'Reindirizzamento al pagamento...',
      redirect_desc: 'Attendi mentre prepariamo il tuo acquisto sicuro.',
      checkout_error_title: 'Errore di Pagamento',
      checkout_error_desc: 'Si è verificato un errore. Per favore, riprova.',
    },
    popups: {
      age_verification_title: 'Verifica dell\'età',
      age_verification_subtitle: 'Inserisci la tua data di nascita per continuare.',
      age_verification_exit_button: 'Esci',
      age_verification_enter_button: 'Entra',
      age_verification_error_invalid: 'Inserisci una data valida.',
      age_verification_error_underage: 'Devi avere più di {min_age} anni per entrare.',
      welcome_title: 'Benvenuto!',
      welcome_subtitle_part1: 'Iscriviti alla nostra newsletter e ottieni uno',
      welcome_subtitle_discount: 'sconto del 10%',
      welcome_subtitle_part2: 'sul tuo primo acquisto.',
      welcome_open_offer_aria: 'Apri l\'offerta di iscrizione',
    },
    notifications: {
      recent_purchase_title: 'Acquisto Recente!',
      recent_purchase_desc: '{name} da {location} ha appena comprato {quantity} x {product_name}.',
      real_order_title: 'Ordine Reale Confermato!',
      a_city: 'una città'
    },
     footer: {
      slogan: 'Il tuo negozio di fiducia per aromi di qualità premium.',
      column_info: 'Informazioni',
      column_guides: 'Guide',
      column_legal: 'Legale',
      column_help: 'Aiuto',
      link_legal_info: 'Informazioni legali',
      link_terms: 'Termini e Condizioni Generali',
      link_popper_sale: 'Vendita di Popper',
      link_secure_payments: 'Pagamenti sicuri',
      link_popper_info: 'Popper: tutto quello che devi sapere',
      link_leather_cleaners: 'Informazioni sui pulitori per pelle',
      link_popper_shop: 'Negozio Popper',
      link_privacy: 'Privacy e protezione dei dati',
      link_disputes: 'Risoluzione delle controversie',
      link_cookies: 'Politica sui cookie',
      link_shipping: 'Spedizione e tariffe',
      link_contact: 'Contattaci',
      link_blog: 'Blog',
      link_docs: 'Documenti del sito',
      copyright: 'Tutti i diritti riservati.'
    },
    contact_page: {
        title: "Contattaci",
        subtitle: "Hai una domanda o hai bisogno di aiuto? Compila il modulo e il nostro team si metterà in contatto con te.",
        email_card_title: "Email di Contatto",
        email_card_description: "Per richieste generali, inviaci un'email a:",
        legal_card_title: "Informazioni Legali",
        legal_owner: "Proprietario",
        legal_address: "Indirizzo",
        form_card_title: "Invia un messaggio",
        form_name: "Il Tuo Nome",
        form_name_placeholder: "Mario Rossi",
        form_email: "La Tua Email",
        form_email_placeholder: "tu@email.it",
        form_subject: "Oggetto",
        form_subject_placeholder: "Richiesta su un ordine",
        form_message: "Messaggio",
        form_message_placeholder: "Scrivi qui la tua richiesta...",
        form_submit_button: "Invia Messaggio",
        form_sending_button: "Invio in corso...",
        success_toast_title: "Messaggio Inviato!",
        success_toast_description: "Grazie per averci contattato. Ti risponderemo il prima possibile.",
    },
     blog_page: {
      comments_title: 'Commenti',
      no_comments: 'Sii il primo a commentare.',
      leave_comment_title: 'Lascia un commento',
      form_name_placeholder: 'Il tuo nome',
      form_comment_placeholder: 'Scrivi il tuo commento...',
      form_submit_button: 'Pubblica commento'
    },
    shipping_page: {
      title: 'Spedizione e Tariffe',
      subtitle: 'A Popper Online, ci sforziamo di farti ricevere il tuo ordine il più rapidamente possibile, con la massima discrezione e sicurezza.',
      policy_title: 'Spedizione del tuo Pacco',
      policy_desc: 'Facciamo del nostro meglio per farti ricevere rapidamente il tuo ordine. Si prega di notare i seguenti punti:',
      policy_item1: 'Gli ordini effettuati prima delle 12:00 vengono spediti lo stesso giorno (tranne durante i periodi promozionali, i giorni festivi in Francia o in caso di alto volume di ordini).',
      policy_item2: 'Tutti gli ordini vengono spediti entro 24 ore lavorative (lun-ven), esclusi i giorni festivi.',
      policy_item3: 'Le nostre spedizioni sono sempre discrete e anonime, senza alcun riferimento al contenuto o al nostro negozio all\'esterno del pacco.',
      rates_alert_title: 'Avviso Importante sulle Tariffe',
      rates_alert_desc: 'Le tariffe e i corrieri mostrati di seguito sono indicativi e si basano sui nostri partner logistici di riferimento. Il costo finale della spedizione sarà calcolato durante il checkout e potrebbe variare a seconda delle condizioni specifiche del corriere al momento dell\'acquisto.',
      rates_title: 'Tariffe di Spedizione',
      rates_subtitle: 'Gratuita da 39€ per la Penisola Iberica, Francia, Portogallo, Germania, Italia, Belgio, Lussemburgo e Paesi Bassi.',
      domestic_title: 'Spagna (Penisola), Francia, Portogallo, Germania, Italia, ecc.',
      home_delivery: 'Consegna a domicilio:',
      carrier: 'Corriere',
      rate: 'Tariffa',
      delivery_time: 'Tempi di Consegna',
      pickup_points: 'Presso punti di ritiro:',
      islands_title: 'Isole Baleari, Canarie, Ceuta e Melilla',
      islands_desc: 'Tempi soggetti a procedure doganali.',
      europe_title: 'Resto d\'Europa',
      europe_desc: 'Consegna a domicilio e presso punti di ritiro.',
      world_title: 'Spedizioni nel Resto del Mondo',
      zone: 'Zona',
      world_rate: 'Tariffa (consegna a domicilio con Chrono Express)',
      additional_info_title: 'Informazioni Aggiuntive',
      tracking_title: 'Tracciamento e Avviso di Consegna',
      tracking_desc: 'Riceverai un\'email con il numero di tracciamento quando il tuo ordine verrà spedito. Se non sei a casa, il corriere lascerà un avviso per organizzare una nuova consegna o indicherà il punto di ritiro più vicino.',
      customs_title: 'Spedizioni Internazionali e Dogana',
      customs_desc: 'Per ordini al di fuori dell\'UE, potrebbero essere applicati costi doganali. Popper Online non è responsabile di queste tasse, imposte o dazi aggiuntivi. Come cliente, agisci in qualità di importatore e ti assumi la responsabilità di questi costi.',
      final_note: 'Attenzione: i tempi di consegna sono indicativi e dipendono dal corriere. Indirizzi errati o cause di forza maggiore (scioperi, ecc.) possono causare ritardi. I costi di rispedizione per indirizzo errato o mancato ritiro del pacco saranno a carico del cliente.',
      explore_button: 'Esplora il Catalogo'
    }
  },
  pt: {
     header: {
      free_shipping: 'GRÁTIS +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Menu de Navegação',
      products: 'Produtos',
      create_pack: 'Crie seu Pacote',
      monthly_dose: 'Dose Mensal'
    },
    cart: {
        title: "Carrinho de Compras",
        empty_title: "O seu carrinho está vazio",
        empty_subtitle: "Parece que ainda não adicionou nada.",
        subtotal: "Subtotal",
        volume_discount: "Desconto por volume (com pré-pagamento)",
        shipping_estimate: "Envio (estimado)",
        total_estimate: "Total Estimado:",
        free_shipping_banner: "Você tem frete GRÁTIS!",
        free_shipping_threshold: "Frete grátis em pedidos acima de {price}",
        checkout_button: "Finalizar Reserva",
        discreet_packaging: "Embalagem 100% discreta.",
        notes: "O desconto por volume e os custos finais de envio serão aplicados na tela de checkout com base no método escolhido.",
        item_added: "Adicionado ao carrinho",
        item_removed: "Produto removido",
        item_unavailable: "Esgotado",
        stock_limit_reached: "Limite de estoque atingido",
    },
     account: {
        layout_title: "Minha conta",
        layout_description: "Gerencie suas informações pessoais, pedidos e endereços.",
        sidebar_admin_panel: "Painel de administração",
        sidebar_dashboard: "Painel do usuário",
        sidebar_orders: "Pedidos",
        sidebar_addresses: "Endereços",
        sidebar_subscription: "Dose mensal",
        sidebar_logout: "Sair",
        dashboard_title: "Painel do usuário",
        dashboard_welcome: "Bem-vindo de volta, {name}.",
        dashboard_profile_title: "Informações do perfil",
        dashboard_profile_subtitle: "Os seus dados pessoais.",
        dashboard_profile_name: "Nome:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Pontos de fidelidade",
        dashboard_loyalty_subtitle: "Ganhe pontos a cada compra.",
        dashboard_loyalty_points: "Pontos acumulados",
        dashboard_loyalty_value: "O seu saldo equivale a um desconto de {price}.",
    },
    products: {
        title: "Nosso Catálogo",
        subtitle: "Encontre o seu aroma perfeito. Use os filtros para descobrir a nossa seleção."
    },
    filters: {
        title: "Filtros",
        clear: "Limpar",
        search: "Procurar",
        search_placeholder: "Procurar produtos...",
        sort_by: "Ordenar por",
        sort_placeholder: "Selecionar ordem",
        sort_options: {
            name_asc: "Nome (A-Z)",
            name_desc: "Nome (Z-A)",
            price_asc: "Preço (Crescente)",
            price_desc: "Preço (Decrescente)"
        },
        categories: "Categorias",
        category_options: {
            novedad: "Novidades",
            oferta: "Ofertas",
            "mas-vendido": "Mais vendidos",
            pack: "Packs",
            accesorio: "Acessórios"
        },
        brands: "Marcas",
        size: "Tamanho",
        composition: "Composição"
    },
    product_card: {
        sold_out: "Esgotado",
        offer: "OFERTA",
        notify_me: "Notifique-me",
        add_to_cart: "Adicionar"
    },
    product_info: {
        secure_payment: "Compra segura e pagamento discreto garantido.",
        fast_shipping: "Envio rápido em 24/48h para toda a península.",
        discreet_packaging: "Embalagem 100% discreta sem marcas externas."
    },
    product_details: {
        description_tab: "Descrição",
        details_tab: "Detalhes do produto"
    },
    related_products: {
        title: "Produtos Relacionados"
    },
    stock_notification: {
        dialog_title: "Notificação de Estoque",
        dialog_description: "Você receberá um único e-mail quando {product_name} estiver novamente em estoque.",
        error_title: "Erro",
        error_missing_info: "Faltam informações do produto ou e-mail. Por favor, tente novamente.",
        error_generic: "Não foi possível processar sua solicitação.",
        error_unexpected: "Ocorreu um erro inesperado.",
        success_title: "Nós o notificaremos!",
        success_description: "Você receberá um e-mail em {email} assim que {product_name} estiver disponível novamente.",
        cancel_button: "Cancelar",
        submit_button: "Solicitar Notificação",
        sending_button: "Enviando..."
    },
    auth: {
      login_title: "Iniciar sessão",
      login_subtitle: "Aceda à sua conta para ver os seus pedidos.",
      login_button: "Iniciar sessão",
      logging_in_button: "A iniciar sessão...",
      forgot_password_link: "Esqueceu a sua senha?",
      no_account_prompt: "Não tem uma conta?",
      register_link: "Registe-se",
      email_label: "E-mail",
      password_label: "Senha",
      register_title: "Criar conta",
      register_subtitle: "Registe-se para uma experiência de compra mais rápida.",
      register_button: "Registar",
      registering_button: "A criar conta...",
      confirm_password_label: "Confirmar senha",
      password_strength_8_chars: "Pelo menos 8 caracteres",
      password_strength_uppercase: "Uma letra maiúscula",
      password_strength_lowercase: "Uma letra minúscula",
      password_strength_number: "Um número",
      password_strength_special: "Um carácter especial (!@#$...)",
      have_account_prompt: "Já tem uma conta?",
      login_link: "Iniciar sessão",
      forgot_password_title: "Recuperar senha",
      forgot_password_subtitle: "Introduza o seu e-mail e enviaremos um link para redefinir a sua senha.",
      forgot_password_success_subtitle: "Verifique a sua caixa de entrada (e a pasta de spam).",
      send_recovery_link_button: "Enviar link de recuperação",
      sending_button: "A enviar...",
      back_to_login_button: "Voltar ao início de sessão",
      register_success_title: "Registo concluído!",
      register_success_subtitle: "Bem-vindo, {name}! A sua conta foi criada com sucesso.",
      register_success_description: "O que gostaria de fazer agora?",
      go_to_account_button: "Ir para a minha conta",
      continue_shopping_button: "Continuar a comprar"
    },
    pack_builder: {
      page_title: 'Crie o seu Pacote Personalizado',
      page_subtitle: 'Escolha os seus aromas favoritos do nosso catálogo e monte o pacote perfeito para si.',
      step1_title: '1. Escolha os seus produtos',
      products_in_pack: 'produtos no seu pacote',
      add_button: 'Adicionar',
      step2_title: '2. Reveja o seu pacote',
      summary_title: 'Resumo do Pacote',
      empty_pack_message: 'Selecione produtos à esquerda para começar a montar o seu pacote.',
      total_units: 'Unidades Totais',
      calculating_discount: 'A calcular desconto...',
      processing_payment: 'A processar pagamento...',
      original_price: 'Preço Original',
      your_savings: 'A sua Poupança',
      pack_total: 'Total do Pacote',
      unlock_discount_message: 'Adicione produtos para exceder 70€ para desbloquear descontos.',
      buy_now_button: 'Comprar Pacote Agora',
      redirecting_button: 'A redirecionar...',
      product_limit_title: 'Limite por produto',
      product_limit_desc: 'Não pode adicionar mais de {max} unidades do mesmo produto.',
      sold_out_title: 'Produto Esgotado',
      sold_out_desc: '{name} está atualmente indisponível.',
      stock_insufficient_title: 'Stock insuficiente',
      stock_insufficient_desc: 'Restam apenas {stock} unidades de {name}.',
      pack_limit_title: 'Limite do pacote atingido',
      pack_limit_desc: 'Não pode adicionar mais de {max} produtos ao seu pacote.',
      empty_pack_title: 'Pacote vazio',
      empty_pack_desc: 'Adicione pelo menos um produto para criar o seu pacote.',
      redirect_title: 'A redirecionar para o pagamento...',
      redirect_desc: 'Por favor, aguarde enquanto preparamos a sua compra segura.',
      checkout_error_title: 'Erro no Pagamento',
      checkout_error_desc: 'Ocorreu um erro. Por favor, tente novamente.',
    },
    popups: {
      age_verification_title: 'Verificação de Idade',
      age_verification_subtitle: 'Introduza a sua data de nascimento para continuar.',
      age_verification_exit_button: 'Sair',
      age_verification_enter_button: 'Entrar',
      age_verification_error_invalid: 'Por favor, introduza uma data válida.',
      age_verification_error_underage: 'Tem de ter mais de {min_age} anos para entrar.',
      welcome_title: 'Bem-vindo!',
      welcome_subtitle_part1: 'Subscreva a nossa newsletter e obtenha um',
      welcome_subtitle_discount: 'desconto de 10%',
      welcome_subtitle_part2: 'na sua primeira compra.',
      welcome_open_offer_aria: 'Abrir oferta de subscrição',
    },
    notifications: {
      recent_purchase_title: 'Compra Recente!',
      recent_purchase_desc: '{name} de {location} acabou de comprar {quantity} x {product_name}.',
      real_order_title: 'Pedido Real Confirmado!',
      a_city: 'uma cidade'
    },
     footer: {
      slogan: 'A sua loja de confiança para aromas de qualidade premium.',
      column_info: 'Informações',
      column_guides: 'Guias',
      column_legal: 'Legal',
      column_help: 'Ajuda',
      link_legal_info: 'Informação legal',
      link_terms: 'Termos e Condições Gerais',
      link_popper_sale: 'Venda de Popper',
      link_secure_payments: 'Pagamentos seguros',
      link_popper_info: 'Poppers: tudo o que precisa de saber',
      link_leather_cleaners: 'Informações sobre Limpadores de Couro',
      link_popper_shop: 'Loja Popper',
      link_privacy: 'Privacidade e proteção de dados',
      link_disputes: 'Resolução de litígios',
      link_cookies: 'Política de cookies',
      link_shipping: 'Envio e tarifas',
      link_contact: 'Contacte-nos',
      link_blog: 'Blog',
      link_docs: 'Documentos do Site',
      copyright: 'Todos os direitos reservados.'
    },
    contact_page: {
        title: "Contacte-nos",
        subtitle: "Tem uma pergunta ou precisa de ajuda? Preencha o formulário e a nossa equipa entrará em contacto consigo.",
        email_card_title: "Email de Contacto",
        email_card_description: "Para questões gerais, envie-nos um email para:",
        legal_card_title: "Informação Legal",
        legal_owner: "Proprietário",
        legal_address: "Endereço",
        form_card_title: "Enviar uma mensagem",
        form_name: "O Seu Nome",
        form_name_placeholder: "João Silva",
        form_email: "O Seu Email",
        form_email_placeholder: "voce@email.pt",
        form_subject: "Assunto",
        form_subject_placeholder: "Dúvida sobre um pedido",
        form_message: "Mensagem",
        form_message_placeholder: "Escreva aqui a sua dúvida...",
        form_submit_button: "Enviar Mensagem",
        form_sending_button: "A enviar...",
        success_toast_title: "Mensagem Enviada!",
        success_toast_description: "Obrigado por nos contactar. Responderemos o mais breve possível.",
    },
     blog_page: {
      comments_title: 'Comentários',
      no_comments: 'Seja o primeiro a comentar.',
      leave_comment_title: 'Deixe um comentário',
      form_name_placeholder: 'O seu nome',
      form_comment_placeholder: 'Escreva o seu comentário...',
      form_submit_button: 'Publicar comentário'
    },
    shipping_page: {
      title: 'Envio e Tarifas',
      subtitle: 'Na Popper Online, esforçamo-nos por entregar a sua encomenda o mais rapidamente possível, com a máxima discrição e segurança.',
      policy_title: 'Envio da sua Encomenda',
      policy_desc: 'Fazemos o nosso melhor para que receba a sua encomenda rapidamente. Tenha em atenção os seguintes pontos:',
      policy_item1: 'As encomendas efetuadas antes das 12:00 são enviadas no mesmo dia (exceto em períodos promocionais, feriados em França ou grande volume de encomendas).',
      policy_item2: 'Todas as encomendas são enviadas no prazo de 24 horas úteis (Seg-Sex), excluindo feriados.',
      policy_item3: 'As nossas remessas são sempre discretas e anónimas, sem qualquer referência ao conteúdo ou à nossa loja no exterior da embalagem.',
      rates_alert_title: 'Aviso Importante sobre as Tarifas',
      rates_alert_desc: 'As tarifas e os transportadores apresentados abaixo são indicativos e baseiam-se nos nossos parceiros logísticos de referência. O custo final do envio será calculado durante o checkout e pode variar dependendo das condições específicas do transportador no momento da compra.',
      rates_title: 'Tarifas de Envio',
      rates_subtitle: 'Grátis a partir de 39€ para a Península Ibérica, França, Portugal, Alemanha, Itália, Bélgica, Luxemburgo e Países Baixos.',
      domestic_title: 'Espanha (Península), França, Portugal, Alemanha, Itália, etc.',
      home_delivery: 'Entrega ao domicílio:',
      carrier: 'Transportadora',
      rate: 'Tarifa',
      delivery_time: 'Prazo de Entrega',
      pickup_points: 'Para pontos de recolha:',
      islands_title: 'Ilhas Baleares, Canárias, Ceuta e Melilla',
      islands_desc: 'Prazos sujeitos a procedimentos alfandegários.',
      europe_title: 'Resto da Europa',
      europe_desc: 'Entrega ao domicílio e em pontos de recolha.',
      world_title: 'Envios para o Resto do Mundo',
      zone: 'Zona',
      world_rate: 'Tarifa (entrega ao domicílio com a Chrono Express)',
      additional_info_title: 'Informações Adicionais',
      tracking_title: 'Rastreamento e Aviso de Entrega',
      tracking_desc: 'Receberá um e-mail com o número de rastreamento quando a sua encomenda for enviada. Se não estiver em casa, a transportadora deixará um aviso para agendar uma nova entrega ou indicará o ponto de recolha mais próximo.',
      customs_title: 'Envios Internacionais e Alfândega',
      customs_desc: 'Para encomendas fora da UE, podem ser aplicados custos alfandegários. A Popper Online não se responsabiliza por estas taxas, impostos ou direitos adicionais. Como cliente, atua como importador e assume a responsabilidade por estes custos.',
      final_note: 'Atenção: Os prazos de entrega são indicativos e dependem da transportadora. Endereços incorretos ou motivos de força maior (greves, etc.) podem causar atrasos. Os custos de reenvio por endereço incorreto ou não levantamento da encomenda serão suportados pelo cliente.',
      explore_button: 'Explorar Catálogo'
    }
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const setLanguageCallback = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);
  
  const t = useCallback((key: string, replacements: Record<string, string | number> = {}): string => {
    const keys = key.split('.');
    let result: string | Translations | undefined = translations[language];

    for (const k of keys) {
        if (result && typeof result === 'object' && k in result) {
            result = result[k];
        } else {
            return key;
        }
    }

    let strResult = typeof result === 'string' ? result : key;

    // Handle replacements
    for (const placeholder in replacements) {
        strResult = strResult.replace(`{${placeholder}}`, String(replacements[placeholder]));
    }

    return strResult;
  }, [language]);


  const value = useMemo(() => ({
    language,
    setLanguage: setLanguageCallback,
    t,
  }), [language, setLanguageCallback, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Alias for useLanguage for convenience in components
export const useTranslation = useLanguage;

    
