'use client';

import React, { createContext, useContext, useState, ReactNode, useMemo, useCallback } from 'react';

type Language = 'en';

type Translations = {
  [key: string]: string | Translations;
};

const enTranslations: Translations = {
    home: {
      hero_title: "Premium Quality, Unique Sensations",
      hero_subtitle: "Explore our curated selection of aromas and discover a purity and potency that redefines the experience.",
      section_title_new: "New Arrivals",
      section_title_offers: "Special Offers",
      section_title_bestsellers: "Best Sellers",
      feature_secure_title: "100% Secure Website",
      feature_secure_desc: "Your safety is our priority.",
      feature_discreet_payment_title: "Discreet Payment",
      feature_discreet_payment_desc: "No references on your statement.",
      feature_discreet_packaging_title: "Discreet Packaging",
      feature_discreet_packaging_desc: "Packages without marks or logos.",
      feature_fast_shipping_title: "Fast Delivery",
      feature_fast_shipping_desc: "Receive your order in 24/48h.",
      subscribe_title: "Subscribe to our newsletter",
      subscribe_desc: "Get exclusive offers and news directly in your inbox.",
      subscribe_placeholder: "Enter your email...",
      subscribe_button: "Subscribe",
      subscribe_button_loading: "Subscribing...",
      subscribe_success: "Thanks for subscribing!",
      subscribe_success_desc: "You will soon receive our best offers.",
      subscribe_error: "Subscription error",
      subscribe_error_desc: "The subscription could not be completed. Please try again.",
      subscribe_error_email: "Please enter your email address.",
    },
    header: {
      free_shipping: 'FREE OVER €40',
      fast_delivery: '24/48h',
      nav_menu: 'Navigation Menu',
      products: 'Products',
      create_pack: 'Create your Pack',
      monthly_dose: 'Monthly Dose',
      product_links: {
        all: "ALL PRODUCTS",
        small: "SMALL (10ML)",
        medium: "MEDIUM (15ML)",
        large: "LARGE (25ML)",
        packs: "PACKS",
        accessories: "ACCESSORIES",
        toys: "EROTIC TOYS",
      },
      composition_links: {
        title: "COMPOSITION",
        amyl: "AMYL",
        pentyl: "PENTYL",
        propyl: "PROPYL",
        cbd: "CBD",
        mix: "NITRITE MIX",
      }
    },
    cart: {
        title: "Shopping Cart",
        empty_title: "Your cart is empty",
        empty_subtitle: "It seems you haven't added anything yet.",
        subtotal: "Subtotal",
        volume_discount: "Volume discount",
        free_shipping_banner: "Enjoy FREE Shipping!",
        free_shipping_threshold: "Free shipping on orders over {price}",
        checkout_button: "Checkout",
        discreet_packaging: "100% discreet packaging.",
        notes: "Volume discount and final shipping costs will be applied at checkout.",
        item_added: "Added to cart",
        item_removed: "Product removed",
        item_unavailable: "Out of stock",
        stock_limit_reached: "Stock limit reached",
    },
    checkout: {
      title: "Complete Order",
      confirm_cart_title: "Confirm Your Cart",
      user_details_title: "Your Details",
      user_details_subtitle: "Information for delivery management.",
      user_details_not_logged_in: "Please log in or register to continue.",
      login_required_alert_title: "Access Restricted",
      login_required_alert_desc: "You must be logged in to finish the checkout.",
      login_button: "Login",
      register_button: "Register",
      use_new_address: "Use a new address",
      shipping_address_title: "Shipping Address",
      fullname_label: "Full Name",
      email_label: "Email",
      phone_label: "Phone",
      street_label: "Street Address",
      street_placeholder: "Street name and number",
      city_label: "City",
      state_label: "State / Province",
      zip_label: "Zip Code",
      country_label: "Country",
      save_address_label: "Save this address",
      review_title: "Review & Pay",
      order_summary_title: "Order Summary",
      subtotal: "Subtotal",
      shipping: "Shipping",
      free_shipping: "Free",
      total_payable: "Total to Pay",
      products_title: "Products",
      coupon_placeholder: "Enter coupon code",
      apply_button: "Apply",
      applied_button: "Applied",
      confirming_button: "Confirming...",
      processing_button: "Processing...",
      next_button: "Continue",
      previous_button: "Back",
      continue_shopping: "Continue Shopping",
      stepper: {
        cart: "Cart",
        details: "Details",
        review: "Review",
      },
      form_errors: {
        name_required: "Name is required.",
        email_invalid: "Invalid email.",
        phone_required: "Phone is required.",
        street_required: "Street is required.",
        city_required: "City is required.",
        state_required: "State is required.",
        zip_required: "Zip code is required.",
        country_required: "Country is required.",
      },
      toasts: {
        coupon_applied_title: "Coupon applied!",
        coupon_applied_desc: "You have saved {discount}.",
        coupon_error_title: "Invalid coupon",
        coupon_error_invalid: "Code is not valid.",
        coupon_error_inactive: "Coupon is not active.",
        coupon_error_expired: "Coupon has expired.",
        order_error_title: "Payment Error",
        order_error_desc: "Could not process order. Please try again.",
        login_required_desc: "Login required to complete purchase.",
      },
      hilow_gateway_info_title: "Secure payment (Hilow)",
      hilow_gateway_info_desc:
        "When you confirm, your order is saved and you are redirected to Hilow’s secure payment page. Card details are never entered on this site.",
      payment_error_banner_title: "Could not start payment",
      payment_error_banner_hint:
        "Check the message below. You can go back and try again. Error 403 often means the store domain does not match Hilow settings.",
      payment_error_dismiss: "Dismiss",
      payment_error_local_order_title: "Could not save your order",
      payment_error_local_order_hint:
        "The order was not saved before payment. Check your connection and Firestore rules, then try again.",
    },
    checkout_success: {
      verifying_alert_title: "Confirming payment",
      verifying_alert_desc:
        "We are waiting for confirmation from our system. This usually takes a few seconds after you pay on Hilow.",
      verifying_keep_open: "Please do not close this window.",
      login_alert_title: "Sign in required",
      login_alert_desc: "Sign in with the same account you used for purchase to see the order status.",
      timeout_alert_title: "Confirmation delayed",
      timeout_alert_desc:
        "We could not confirm in real time. If you already paid, the order will appear in My orders within minutes.",
      firestore_error_title: "Could not load order",
      firestore_error_desc: "Connection or permissions error. Check that you are logged in with the correct account.",
      contact_link: "Contact",
    },
    account: {
        layout_title: "My Account",
        layout_description: "Manage your profile, orders, and addresses.",
        sidebar_admin_panel: "Admin Panel",
        sidebar_dashboard: "Dashboard",
        sidebar_orders: "Orders",
        sidebar_addresses: "Addresses",
        sidebar_subscription: "Monthly Dose",
        sidebar_logout: "Logout",
        dashboard_title: "Account Dashboard",
        dashboard_welcome: "Welcome back, {name}.",
        dashboard_profile_title: "Profile Info",
        dashboard_profile_subtitle: "Your account details.",
        dashboard_profile_name: "Name:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Loyalty Points",
        dashboard_loyalty_subtitle: "Earn rewards with every purchase.",
        dashboard_loyalty_points: "Points Balance",
        dashboard_loyalty_value: "Equivalent to {price} discount.",
        orders_title: "Order History",
        orders_subtitle: "Track and manage your orders.",
        orders_empty_title: "No orders yet",
        orders_empty_subtitle: "Your orders will appear here.",
        orders_table_order_no: "Order #",
        orders_table_date: "Date",
        orders_table_status: "Status",
        orders_table_total: "Total",
        orders_table_actions: "Actions",
        orders_view_details_button: "View",
        order_details_title: "Order Details",
        order_details_subtitle: "Order #{orderId}",
        order_details_back_button: "Back to Orders",
        order_details_items_title: "Items",
        order_details_summary_title: "Summary",
        order_details_summary_date: "Placed on {date}",
        order_details_summary_status: "Status:",
        order_details_summary_subtotal: "Subtotal:",
        order_details_summary_total: "TOTAL:",
        order_details_shipping_address_title: "Shipping Address",
        addresses_title: "My Addresses",
        addresses_subtitle: "Manage your saved addresses.",
        addresses_add_button: "Add Address",
        addresses_edit_button: "Edit",
        addresses_delete_button: "Delete",
        addresses_default_badge: "Default",
        addresses_empty_placeholder: "No addresses saved.",
        menu: {
          admin_title: "Admin",
          user_title: "User",
          admin_panel: "Admin Panel",
          user_dashboard: "Dashboard",
          orders: "Orders",
          addresses: "Addresses",
          logout: "Logout"
        },
        subscription: {
          title: "Your Monthly Dose",
          selected_badge: "Selected",
          not_chosen_yet: "Not chosen",
          popper: "Aroma",
          accessory: "Accessory",
          box_on_its_way_title: "Box on its way!",
          box_on_its_way_desc: "Your monthly box is currently being prepared and will be shipped shortly.",
          confirm_selection_button: "Confirm Selection",
          timeline_step1: "Start",
          timeline_step2: "Selection",
          timeline_step3: "Shipping",
          success_title: "Welcome to the Club!",
          customize_box_button: "Customize My Box",
          save_success_title: "Selection Saved",
          save_success_desc: "Your choices for this month have been updated.",
          error_title: "Error",
          save_error_desc: "We couldn't save your selection. Please try again.",
          popper_desc: "Choose an aroma",
          accessory_desc: "Choose an accessory",
          select_dialog_title: "Select {type}",
          select_button: "Select",
          change_selection_button: "Change Selection",
          choose_product_button: "Choose Product",
          surprise_gift_title: "Surprise Gift",
          surprise_gift_desc: "Included in every monthly box."
        }
    },
    popups: {
      age_verification_title: 'Age Verification',
      age_verification_subtitle: 'Please confirm you are over 18 years old to access our premium selection.',
      age_verification_exit_button: 'Exit',
      age_verification_enter_button: 'Enter',
      age_verification_error_invalid: 'Invalid date. Please check your input.',
      age_verification_error_underage: 'You must be 18+ to enter this website.',
      welcome_title: 'Welcome Offer!',
      welcome_subtitle_part1: 'Subscribe to our newsletter and get a',
      welcome_subtitle_discount: '10% discount',
      welcome_subtitle_part2: 'on your first purchase.',
      welcome_open_offer_aria: "Open welcome offer",
      cookies_banner_text: 'We use cookies to improve your experience and analyze traffic.',
      cookies_customize: 'Customize',
      cookies_reject: 'Only necessary',
      cookies_accept: 'Accept All',
      cookies_save: 'Save Preferences',
      cookies_preferences_title: "Cookie Preferences",
      cookies_preferences_desc: "Select which cookies you want to allow.",
      cookies_technical: "Necessary Cookies",
      cookies_analytics: "Analytics Cookies",
      cookies_marketing: "Marketing Cookies",
    },
    notifications: {
      recent_purchase_title: 'Recent Purchase!',
      recent_purchase_desc: '{name} from {location} bought {quantity} x {product_name}.',
      real_order_title: 'Order Confirmed!',
      a_city: 'a city'
    },
    footer: {
      slogan: 'The finest selection of premium quality aromas.',
      column_info: 'Information',
      column_guides: 'Guides',
      column_legal: 'Legal',
      column_help: 'Help',
      link_legal_info: 'Legal Info',
      link_terms: 'Terms & Conditions',
      link_popper_sale: 'Aroma Sale',
      link_secure_payments: 'Secure Payments',
      link_popper_info: 'What is an Aroma?',
      link_leather_cleaners: 'Leather Cleaners',
      link_popper_shop: 'Aroma Shop',
      link_privacy: 'Privacy Policy',
      link_disputes: 'Dispute Resolution',
      link_cookies: 'Cookies Policy',
      link_shipping: 'Shipping & Rates',
      link_contact: 'Contact Us',
      link_blog: 'Our Blog',
      link_docs: 'Developer Docs',
      copyright: 'All rights reserved.'
    },
    products: {
      title: "Our Premium Collection",
      subtitle: "The finest selection of pure and potent aromas.",
    },
    product_card: {
      add_to_cart: "Add to Cart",
      sold_out: "Sold Out",
      offer: "Sale",
      notify_me: "Notify Me"
    },
    product_details: {
      description_tab: "Description",
      details_tab: "Details"
    },
    product_info: {
      secure_payment: "100% Secure Payment",
      fast_shipping: "Fast Shipping (24/48h)",
      discreet_packaging: "Fully Discreet Packaging"
    },
    related_products: {
      title: "You May Also Like"
    },
    filters: {
      title: "Filter by",
      clear: "Clear All",
      search: "Search",
      search_placeholder: "Search products...",
      sort_by: "Sort By",
      sort_placeholder: "Select sorting",
      categories: "Categories",
      brands: "Brands",
      size: "Size",
      composition: "Composition",
      sort_options: {
        name_asc: "Name: A-Z",
        name_desc: "Name: Z-A",
        price_asc: "Price: Low to High",
        price_desc: "Price: High to Low"
      },
      category_options: {
        novedad: "New Arrivals",
        oferta: "On Sale",
        'mas-vendido': "Best Sellers",
        pack: "Packs",
        accesorio: "Accessories",
        juguete: "Toys"
      }
    },
    pack_builder: {
      page_title: "Custom Pack Builder",
      page_subtitle: "Mix and match your favorite products to unlock exclusive volume discounts.",
      step1_title: "1. Select Your Products",
      step2_title: "2. Review Your Selection",
      summary_title: "Custom Pack Summary",
      add_button: "Add to Pack",
      buy_now_button: "Buy This Pack",
      products_in_pack: "Products in pack",
      total_units: "Total units",
      calculating_discount: "Calculating discount...",
      original_price: "Standard Price",
      your_savings: "Your Savings",
      pack_total: "Pack Total",
      unlock_discount_message: "Add more items to unlock deeper volume discounts.",
      empty_pack_message: "Your pack is currently empty. Start adding products to see your savings!",
      redirect_title: "Redirecting...",
      redirect_desc: "Preparing your custom pack for secure checkout.",
      product_limit_desc: "You can add a maximum of {max} units per product.",
      pack_limit_desc: "Your pack has reached the limit of {max} items.",
      empty_pack_title: "Empty Pack",
      empty_pack_desc: "Please add products to your pack before proceeding to checkout.",
      redirecting_button: "Redirecting...",
      sold_out_title: "Out of Stock",
      sold_out_desc: "{name} is currently unavailable.",
      stock_insufficient_title: "Insufficient Stock",
      stock_insufficient_desc: "Only {stock} units of {name} are available.",
      processing_payment: "Processing..."
    },
    auth: {
      login_title: "Login",
      login_subtitle: "Access your account to manage your orders and addresses.",
      email_label: "Email Address",
      password_label: "Password",
      forgot_password_link: "Forgot your password?",
      login_button: "Login",
      logging_in_button: "Logging in...",
      no_account_prompt: "Don't have an account?",
      register_link: "Register here",
      register_title: "Create Account",
      register_subtitle: "Join us to enjoy a personalized shopping experience and earn points.",
      confirm_password_label: "Confirm Password",
      register_button: "Register",
      registering_button: "Creating account...",
      have_account_prompt: "Already have an account?",
      login_link: "Login here",
      register_success_title: "Registration Successful!",
      register_success_subtitle: "Welcome to PuroRush, {name}.",
      register_success_description: "We have sent a verification link to your email. Please verify your account to unlock all features.",
      go_to_account_button: "My Account",
      continue_shopping_button: "Continue Shopping",
      forgot_password_title: "Reset Password",
      forgot_password_subtitle: "Enter your email and we will send you a recovery link.",
      forgot_password_success_subtitle: "Check your inbox.",
      send_recovery_link_button: "Send Link",
      back_to_login_button: "Back to Login",
      sending_button: "Sending...",
      password_strength_8_chars: "At least 8 characters",
      password_strength_uppercase: "One uppercase letter",
      password_strength_lowercase: "One lowercase letter",
      password_strength_number: "One number",
      password_strength_special: "One special character",
      back_to_login_link: "Back to login"
    },
    stock_notification: {
      dialog_title: "Notify Me",
      dialog_description: "We will send you a one-time email when {product_name} is back in stock.",
      email_label: "Email Address",
      cancel_button: "Cancel",
      submit_button: "Notify Me",
      sending_button: "Processing...",
      success_title: "Request Received",
      success_description: "We'll email {email} as soon as {product_name} is available again.",
      error_title: "Error",
      error_missing_info: "Missing information. Please try again.",
      error_generic: "We couldn't process your request.",
      error_unexpected: "An unexpected error occurred.",
      error_invalid_email: "Please enter a valid email."
    },
    contact_page: {
      title: "Contact Us",
      subtitle: "Have questions? Our support team is here to help.",
      email_card_title: "Email Support",
      email_card_description: "Typical response time is within 24 hours.",
      legal_card_title: "Legal Information",
      legal_owner: "Owner:",
      legal_address: "Address:",
      form_card_title: "Send us a Message",
      form_name: "Full Name",
      form_email: "Email Address",
      form_subject: "Subject",
      form_message: "Your Message",
      form_name_placeholder: "John Doe",
      form_email_placeholder: "john@example.com",
      form_subject_placeholder: "Question about an order",
      form_message_placeholder: "How can we help you?",
      form_submit_button: "Send Message",
      form_sending_button: "Sending...",
      success_toast_title: "Message Sent",
      success_toast_description: "Thank you for contacting us. We will get back to you shortly."
    },
    blog_page: {
      comments_title: "Comments",
      no_comments: "No comments yet. Be the first to share your thoughts!",
      leave_comment_title: "Leave a Comment",
      form_name_placeholder: "Your name",
      form_comment_placeholder: "Your thoughts...",
      form_submit_button: "Post Comment"
    },
    leather_cleaners_page: {
      title: "Leather Cleaners Information",
      subtitle: "Professional use and technical specifications.",
      philosophy_title: "Product Use",
      philosophy_p1: "Our products are technical solvents intended exclusively for cleaning and maintaining leather goods and other specific industrial applications.",
      philosophy_p2: "We prioritize purity and effectiveness in cleaning, ensuring that your leather items remain in top condition.",
      quality_alert_title: "Quality Standard",
      quality_alert_p: "All our cleaners undergo rigorous quality control to ensure maximum efficiency.",
      recreational_use_alert_title: "Strict Warning",
      recreational_use_alert_p: "These products are NOT for human consumption. Inhalation or ingestion is strictly prohibited and can be dangerous to your health.",
      commitment_title: "Our Commitment",
      commitment_p: "We are committed to providing safe and effective solutions:",
      commitment_item1: "High-purity technical formulas.",
      commitment_item2: "Clear usage labeling.",
      commitment_item3: "<strong>Responsible sales:</strong> sold only to adults (18+).",
      commitment_item4: "Fast and discreet delivery.",
      commitment_p2: "By purchasing these products, you agree to use them solely for their intended cleaning purposes.",
      policy_title: "Safety Policies",
      logistics_title: "Logistics",
      logistics_p: "Orders are shipped in neutral packaging to ensure your privacy.",
      cancellation_alert_title: "Important Note",
      cancellation_alert_p1: "We reserve the right to cancel any order if we suspect misuse of our products.",
      cancellation_alert_p2: "Safe use is paramount. Always read the safety instructions on the label.",
      explore_button: "Explore Cleaners"
    },
    secure_payments_page: {
      title: "Secure & Discreet Payments",
      subtitle: "Multiple ways to pay with total peace of mind.",
      philosophy_title: "Privacy First",
      philosophy_p: "We understand the importance of discretion. That's why we ensure your billing statement remains private and secure.",
      protected_info_title: "Data Protection",
      protected_info_p: "Your payment information is encrypted and handled by professional gateways. We do not store sensitive credit card details on our servers.",
      methods_title: "Payment Methods",
      methods_p: "Choose the option that best fits your needs:",
      cod_title: "Cash on Delivery",
      cod_p: "Pay the courier directly when you receive your package.",
      prepaid_title: "Prepaid Options",
      prepaid_p: "Pay via secure credit card or mobile payment apps.",
      discretion_alert_title: "Total Discretion",
      discretion_alert_p: "No references to the content of your order or our store name will appear on your bank statement.",
      explore_button: "Start Shopping"
    },
    cookies_page: {
      title: "Cookies Policy",
      subtitle: "How we use technologies to enhance your experience.",
      what_is_title: "What are cookies?",
      what_is_p1: "Cookies are small text files stored on your device when you visit a website.",
      what_is_p2: "They help us remember your preferences, provide security, and analyze how our site is used.",
      types_title: "Types of Cookies we use",
      technical_title: "Technical (Necessary)",
      technical_p: "Essential for the website to function properly, such as cart management and login.",
      examples: "Examples:",
      technical_examples: "Session ID, Cart state, Security tokens.",
      analytics_title: "Analytics",
      analytics_p: "Help us understand how visitors interact with the site by collecting anonymous info.",
      analytics_examples: "Pages visited, Time spent, Traffic sources.",
      marketing_title: "Marketing",
      marketing_p: "Used to track visitors across websites to display relevant ads.",
      marketing_examples: "Ad targeting, Social media integration.",
      manage_title: "Managing Cookies",
      manage_p1: "You can change your preferences at any time using the settings button in the banner.",
      manage_p2: "Most browsers also allow you to block or delete cookies through their settings.",
      manage_p3: "Note that disabling necessary cookies may affect the site's functionality."
    },
    popper_info_page: {
      title: "Information about Aromas",
      subtitle: "Learn about the characteristics and safe handling of technical aromas.",
      what_is_title: "What are Alky Nitrites?",
      what_is_p1: "Commonly known as aromas or cleaners, these are volatile chemical compounds that evaporate quickly at room temperature.",
      what_is_p2: "In a professional context, they are used for specialized cleaning and as air fresheners in specific environments.",
      types_alert_title: "Variety of Formulas",
      types_alert_p: "There are different types like Amyl, Pentyl, and Propyl, each with distinct properties and evaporation rates.",
      form_title: "Physical State",
      form_p1: "They are typically translucent liquids with a characteristic chemical smell.",
      form_p2: "They are highly flammable and should be stored in a cool, dry place away from direct sunlight.",
      effects_title: "Technical Properties",
      effects_p: "When used as air fresheners or cleaners, these compounds exhibit:",
      effect1: "Rapid evaporation.",
      effect2: "High cleaning power for leather.",
      effect3: "Intense aroma release.",
      effect4: "Sensitivity to heat and light.",
      effect5: "High volatility.",
      effect6: "Degradation over time if exposed to air.",
      effect7: "Reaction with moisture.",
      addiction_title: "Safety & Misuse",
      addiction_p: "Misuse of these products (human consumption) is dangerous and can lead to severe health issues. They are strictly for technical and environmental use.",
      safety_warning_title: "Safety Warnings",
      safety_warning1: "<strong>FLAMMABLE:</strong> Keep away from heat and open flames.",
      safety_warning2: "<strong>DO NOT INGEST:</strong> Poisonous if swallowed.",
      safety_warning3: "<strong>SKIN IRRITANT:</strong> Avoid direct contact with skin and eyes.",
      mixing_title: "Dangerous Combinations",
      mixing_viagra_title: "NO VIAGRA",
      mixing_viagra_p: "Combining these products with ED medications like Viagra can cause a fatal drop in blood pressure.",
      mixing_speed_title: "NO STIMULANTS",
      mixing_speed_p: "Use in conjunction with stimulants is highly dangerous.",
      long_term_title: "Storage & Disposal",
      long_term_p: "To maintain quality and safety:",
      long_term1: "Store in original tightly closed bottles.",
      long_term2: "Keep out of reach of children and pets.",
      long_term3: "Store in a dark, cool environment.",
      long_term4: "Do not mix different cleaners.",
      long_term5: "Dispose of contents according to local regulations.",
      explore_button: "View Collection"
    },
    privacy_page: {
      title: "Privacy Policy",
      subtitle: "Your data security and privacy are our top priority.",
      commitment_title: "Our Commitment",
      commitment_p1: "We are dedicated to protecting the personal data of our customers and users.",
      commitment_p2: "This policy explains what data we collect, why we collect it, and how we protect it.",
      who_is_responsible_title: "Data Controller",
      who_is_responsible_p: "The entity responsible for your data is <strong>MARY AND POPPER</strong> (ABN: 37 588 057 135).",
      what_data_title: "What data we collect",
      what_data_p: "We only collect data necessary to provide our services:",
      what_data_item1: "<strong>Identification:</strong> Name, email, phone number.",
      what_data_item2: "<strong>Delivery:</strong> Shipping and billing addresses.",
      what_data_item3: "<strong>Payment:</strong> Transaction IDs (we do not store full card numbers).",
      what_data_item4: "<strong>Browsing:</strong> Anonymous analytics and cookie preferences.",
      what_for_title: "Why we use your data",
      what_for_p1: "To process and ship your orders accurately.",
      what_for_p2: "To communicate important order status updates.",
      what_for_p3: "To provide customer support and handle inquiries.",
      what_for_p4: "To improve our website based on user behavior.",
      share_data_title: "Sharing with Third Parties",
      share_data_p: "We share data only with essential service providers:",
      stripe_title: "Payment Processors",
      stripe_p: "Gateway services like Hilow process your payments securely.",
      klaviyo_title: "Communication",
      klaviyo_p: "Klaviyo handles our transactional and marketing emails.",
      firebase_title: "Infrastructure",
      firebase_p: "Google Firebase provides our secure database and hosting.",
      clarity_title: "Analytics",
      clarity_p: "Microsoft Clarity helps us understand site usage anonymously.",
      share_data_p2: "We never sell your personal data to advertisers.",
      your_rights_title: "Your Rights",
      your_rights_p: "You have full control over your information:",
      your_rights_item1: "<strong>Access:</strong> request a copy of your data.",
      your_rights_item2: "<strong>Rectification:</strong> correct inaccurate information.",
      your_rights_item3: "<strong>Erasure:</strong> request deletion of your account.",
      your_rights_item4: "<strong>Objection:</strong> opt-out of marketing communications.",
      your_rights_item5: "<strong>Portability:</strong> transfer your data to another service.",
      your_rights_item6: "<strong>Restriction:</strong> limit how we process your data.",
      your_rights_p2: "To exercise these rights, contact us at <strong>info@comprarpopperonline.com</strong>.",
      explore_button: "Continue Browsing"
    },
    legal_info: {
      title: "Legal Information",
      owner_label: "Legal Owner",
      abn_label: "Registration",
      address_label: "Address",
      contact_label: "Contact",
      logistics_label: "Logistics",
      logistics_value: "International shipping with discrete packaging.",
      usage_warning_title: "Safety Warning",
      usage_warning_desc: "Products are for technical cleaning use only. Misuse is dangerous.",
      cancellation_right_title: "Order Cancellation",
      cancellation_right_desc: "We reserve the right to cancel orders suspected of improper use.",
      explore_button: "View Catalog"
    },
    disputes_page: {
      subtitle: "Fair resolution and consumer rights information.",
      right_of_withdrawal_title: "Right of Withdrawal",
      right_of_withdrawal_p1: "You have the right to withdraw from this contract within 14 days without giving any reason.",
      right_of_withdrawal_p2: "The withdrawal period will expire after 14 days from the day on which you acquire physical possession of the goods.",
      right_of_withdrawal_p3: "To exercise the right, you must inform us via email: info@comprarpopperonline.com.",
      right_of_withdrawal_p4: "Items must be unopened and in their original packaging due to health and safety reasons.",
      exclusion_title: "Exclusion of Right",
      exclusion_p1: "The right of withdrawal does not apply to:",
      exclusion_item1: "<strong>Sealed goods:</strong> which are not suitable for return due to health protection or hygiene reasons and were unsealed after delivery.",
      exclusion_item2: "<strong>Perishable goods:</strong> items that can deteriorate or expire rapidly.",
      exclusion_item3: "<strong>Custom items:</strong> products made to your specifications.",
      exclusion_item4: "<strong>Used items:</strong> any cleaner that has been opened or used.",
      law_title: "Applicable Law",
      law_p1: "These conditions are governed by the laws of Australia. Any disputes will be subject to the jurisdiction of the courts in Western Australia.",
      adr_title: "Online Dispute Resolution (ODR)",
      adr_p1: "The European Commission provides a platform for online dispute resolution, which you can access here:",
      adr_p2: "For our customers in the EU, we are committed to fair resolution through these platforms.",
      odr_platform_button: "EU ODR Platform",
      mediators_button: "Consumer Mediators",
      mediation_steps_title: "Steps for Mediation",
      mediation_step1: "Contact our customer support first.",
      mediation_step2: "If unresolved, submit a formal complaint via email.",
      mediation_step3: "Use the ODR platform if a solution is not reached within 30 days.",
      mediation_p_final: "We aim to resolve all issues amicably and efficiently."
    },
    popper_shop_page: {
      subtitle: "Your trusted destination for high-purity technical aromas.",
      who_we_are_title: "Who We Are",
      who_we_are_subtitle: "Commitment to quality and discretion.",
      who_we_are_p: "We are a leading distributor of specialized cleaning aromas, serving professionals and collectors globally with the highest standards of service.",
      quality_alert_title: "Premium Selection",
      quality_alert_p: "We only work with established brands to ensure the purity of every bottle.",
      how_to_buy_title: "How to Choose",
      how_to_buy_subtitle: "Understanding the different technical formulas.",
      propyl_title: "Nitrite Propyl",
      propyl_p: "Classic formulas, known for their <strong>fresh aroma</strong> and balanced evaporation. Great for regular maintenance.",
      amyl_title: "Nitrite Amyl",
      amyl_p: "The choice for <strong>professional deep cleaning</strong>. Highly potent and pure.",
      pentyl_title: "Nitrite Pentyl",
      pentyl_p: "Known for its <strong>stability and longevity</strong>. Ideal for collectors.",
      best_brands_title: "Featured Brands",
      shipping_title: "Shipping & Privacy",
      shipping_subtitle: "Safe and fast delivery to your door.",
      fast_shipping_title: "Fast Delivery",
      fast_shipping_p: "We ship orders within 24 hours of confirmation.",
      secure_payment_title: "Safe Checkout",
      secure_payment_p: "All transactions are encrypted and processed by secure gateways.",
      payment_methods_p: "We accept credit cards, cash on delivery, and mobile payments.",
      doubts_title: "Still have questions?",
      doubts_subtitle: "Our experts are ready to assist you.",
      contact_email: "info@comprarpopperonline.com",
      explore_button: "Start Exploring"
    },
    venta_popper_page: {
      title: "Premium Aroma Sale",
      subtitle: "The best brands at competitive prices.",
      what_is_title: "Technical Specifications",
      definition_title: "What are they?",
      definition_p: "Technical aromas are <strong>chemical solvents</strong> designed for cleaning leather, removing residues, and environmental scenting.",
      uses_title: "Intended Applications",
      uses_p: "Our products are specifically formulated for:",
      use_item1: "Cleaning and conditioning <strong>premium leather</strong>.",
      use_item2: "Industrial solvent applications.",
      use_item3: "Professional <strong>scenting</strong> of large spaces.",
      warning_title: "Handling Warning",
      warning_p: "Highly flammable. Use only in well-ventilated areas. Not for human consumption.",
      variety_title: "Formula Comparison",
      variety_p: "Each formula offers different technical benefits:",
      table_header_variety: "Variety",
      table_header_description: "Characteristics",
      table_header_application: "Best Use",
      amyl_description: "Maximum potency, deep cleaning action.",
      amyl_application: "Heavy-duty leather restoration.",
      propyl_description: "Fast evaporation, lighter scent profile.",
      propyl_application: "Daily maintenance and fine leather.",
      pentyl_description: "Long-lasting, stable formula.",
      pentyl_application: "High-end goods and collectibles.",
      services_title: "Our Services",
      services_p: "Why customers choose us for their professional supplies:",
      fast_shipping_title: "Express Logistics",
      fast_shipping_p: "Most orders arrive within 48 hours.",
      legality_title: "Compliant & Legal",
      legality_p: "All products are fully compliant with EU and local regulations.",
      prices_title: "Value for Money",
      prices_p: "Wholesale prices available for retail customers.",
      legal_title: "Legal Disclaimer",
      legal_p1: "These products are sold as technical solvents and aromas only. By purchasing, you confirm you are 18+ and will use them responsibly.",
      import_warning_title: "Important Notice",
      import_warning_use: "<strong>Technical Use Only:</strong> Inhalation or ingestion is strictly forbidden.",
      import_warning_responsibility: "<strong>User Responsibility:</strong> The buyer assumes all liability for any use other than cleaning.",
      import_warning_cancellation: "<strong>Monitoring:</strong> Orders with signs of misuse will be canceled immediately.",
      explore_button: "See All Brands"
    },
    shipping_page: {
      title: "Shipping & Rates",
      subtitle: "Fast, safe, and 100% discreet delivery.",
      policy_title: "Shipping Policy",
      policy_desc: "We prioritize your privacy and speed of delivery. All orders are processed same-day if placed before 2:00 PM.",
      policy_item1: "Discrete packaging with no external markings.",
      policy_item2: "Real-time tracking for every shipment.",
      policy_item3: "Multiple courier options to suit your needs.",
      rates_alert_title: "Free Shipping",
      rates_alert_desc: "Get FREE standard shipping on all orders over €40!",
      rates_title: "Standard Rates",
      rates_subtitle: "Estimated costs and delivery times.",
      domestic_title: "Spain (Peninsula)",
      home_delivery: "Home Delivery",
      carrier: "Courier",
      rate: "Rate",
      delivery_time: "Est. Time",
      pickup_points: "Pickup Points",
      islands_title: "Balearic & Canary Islands",
      islands_desc: "Additional customs fees may apply for Canary Islands.",
      europe_title: "European Union",
      europe_desc: "Fast delivery to all EU member states.",
      world_title: "Worldwide Shipping",
      zone: "Zone",
      world_rate: "Flat Rate",
      additional_info_title: "Additional Information",
      tracking_title: "Order Tracking",
      tracking_desc: "You will receive a tracking number via email once your order is dispatched.",
      customs_title: "Customs & Duties",
      customs_desc: "For international orders outside the EU, the buyer is responsible for any import duties.",
      final_note: "Delivery times are estimates and may vary during peak seasons.",
      explore_button: "Continue Shopping"
    },
    terms_page: {
      title: "Terms and Conditions",
      welcome: "Welcome to PuroRush. These terms govern your use of our website and purchase of our products.",
      acceptance: "By accessing this site, you agree to be bound by these terms. If you do not agree, please do not use our services.",
      section1_title: "1. Professional Use and Age",
      section1_1: "<strong>Technical Use Only:</strong> Our products (aromas/cleaners) are sold exclusively for cleaning leather and as environmental scenting solvents.",
      section1_2: "<strong>Misuse Warning:</strong> Human consumption, including inhalation or ingestion, is strictly prohibited and dangerous.",
      section1_3: "<strong>Age Requirement:</strong> You must be at least 18 years old to purchase any item from this store.",
      section1_4: "<strong>Suspected Misuse:</strong> We reserve the right to cancel any order if we suspect the products will be used for purposes other than their intended technical use.",
      section2_title: "2. Privacy and Discretion",
      section2_p1: "All orders are shipped in discreet packaging. No mention of the store name or contents will appear on the outside or your bank statement.",
      section3_title: "3. Product Information",
      section3_p1: "We strive for accuracy in product descriptions and images. However, actual colors and packaging may vary slightly.",
      section4_title: "4. Pricing and Availability",
      section4_p1: "All prices are in Euros and include VAT where applicable. Shipping costs are added at checkout. Stock levels are updated in real-time.",
      section5_title: "5. Order Acceptance",
      section5_p1: "An order is considered accepted only after we send a confirmation email and receive payment.",
      section6_title: "6. Shipping and Delivery",
      section6_p1: "We ship to many countries. Delivery times are estimates. We are not responsible for delays caused by couriers or customs.",
      section9_title: "9. Loyalty Program",
      section9_1: "<strong>Earning:</strong> You earn 1 point for every €10 spent.",
      section9_2: "<strong>Redemption:</strong> Points can be used for discounts on future orders. Points have no cash value.",
      section11_title: "11. Liability Limitation",
      section11_1: "<strong>Misuse:</strong> MARY AND POPPER is not liable for any injury or damage resulting from the misuse of its products.",
      section11_2: "<strong>Cleaning Results:</strong> We are not liable for damage to items caused by improper cleaning techniques.",
      section12_title: "12. Intellectual Property",
      section12_p1: "All content on this site is the property of MARY AND POPPER and is protected by copyright laws.",
      section14_title: "14. Dispute Resolution",
      section14_1: "<strong>Law:</strong> These terms are governed by Australian law.",
      section14_2: "<strong>ODR:</strong> The European Commission provides a platform for online dispute resolution.",
      section15_title: "15. Modifications",
      section15_p1: "We reserve the right to update these terms at any time without prior notice.",
      section16_title: "16. Contact",
      section16_p1: "For any questions regarding these terms, please email info@comprarpopperonline.com.",
      explore_button: "Back to Shop"
    },
    docs: {
      title: "System Documentation",
      subtitle1: "Architecture and implementation guide for the e-commerce platform.",
      subtitle2: "This guide serves as a technical map for developers.",
      style_guide_title: "Style Guide",
      colors_title: "Colors",
      colors_desc: "Standard HSL variables for theming.",
      typography_title: "Typography",
      typography_desc: "Inter font family via next/font.",
      icons_title: "Icons",
      icons_desc: "Lucide React icon library.",
      brand_assets_title: "Brand Assets",
      logo_title: "Official Logo",
      logo_desc: "Multi-layer SVG logo with stickers effect.",
      data_arch_title: "Data Architecture",
      data_flow_title: "Direct Data Flow",
      data_flow_desc: "Direct browser-to-database communication model.",
      business_logic_title: "Business Logic",
      age_gate_title: "Age Verification",
      age_gate_desc: "Birthday-based entry system.",
      sales_notifications_title: "Sales Notifications",
      sales_notifications_desc: "Hybrid real and simulated notifications.",
      welcome_popup_title: "Welcome Popup",
      welcome_popup_desc: "Newsletter subscription with discount.",
      volume_discounts_title: "Volume Discounts",
      volume_discounts_desc: "Automatic cart savings based on quantity.",
      loyalty_points_title: "Loyalty Points",
      loyalty_points_desc: "Point-based reward system.",
      main_pages_title: "Main Pages",
      home_page_title: "Home Page",
      home_page_desc: "Dynamic sections with real-time updates.",
      products_page_title: "Catalog Page",
      products_page_desc: "Advanced filtering and sorting.",
      product_detail_page_title: "Product Detail",
      product_detail_page_desc: "Gallery and technical specifications.",
      ecommerce_features_title: "E-commerce Features",
      pack_builder_title: "Custom Pack Builder",
      pack_builder_desc: "AI-powered dynamic pricing for packs.",
      cart_title: "Shopping Cart",
      cart_desc: "Real-time updates and saving estimates.",
      checkout_title: "Checkout Flow",
      checkout_desc: "Multi-step payment process.",
      subscription_title: "Club Subscription",
      subscription_start_title: "Joining the Club",
      subscription_start_desc: "Onboarding and payment flow.",
      subscription_management_title: "Managing the Club",
      subscription_management_desc: "Customization and cancellation.",
      subscription_webhook_title: "Webhooks",
      subscription_webhook_desc: "Server-to-server notifications.",
      auth_title: "Authentication",
      login_title: "Login",
      login_desc: "Session-based secure authentication.",
      register_title: "Register",
      register_desc: "New user account creation.",
      account_dashboard_title: "User Dashboard",
      account_dashboard_desc: "Profile and points management.",
      orders_title: "My Orders",
      orders_desc: "Real-time order tracking.",
      addresses_title: "My Addresses",
      addresses_desc: "Address book management.",
      admin_panel_title: "Admin Panel",
      admin_dashboard_title: "Admin Dashboard",
      admin_dashboard_desc: "Sales analytics and site metrics.",
      admin_orders_title: "Order Management",
      admin_orders_desc: "Full order processing lifecycle.",
      admin_products_crud_title: "Catalog Management",
      admin_products_crud_desc: "Deep dive into product CRUD flow.",
      admin_products_fields_title: "Product Editor",
      admin_products_fields_desc: "Rich text editing and price logic.",
      admin_web_customization_title: "Web Settings",
      admin_web_customization_desc: "Site-wide feature flags.",
      info_pages_title: "Content Pages",
      info_blog_title: "Blog",
      info_blog_desc: "Articles and comments system.",
      info_contact_title: "Contact",
      info_contact_desc: "Customer support form.",
      info_shipping_title: "Shipping Info",
      info_shipping_desc: "Rates and zones table.",
      info_terms_title: "Legal Info",
      info_terms_desc: "Terms and privacy policies.",
      try_it_button: "View Page",
      implementation_details_button: "See Details",
      download_svg_button: "Download SVG",
      download_png_button: "Download PNG"
    },
    invalid_date: "Invalid Date",
    date_unavailable: "N/A"
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const getNestedTranslation = (obj: Translations, key: string): string | Translations | undefined => {
  return key.split('.').reduce<string | Translations | undefined>((acc, part) => {
    if (acc && typeof acc === 'object' && part in acc) {
      return (acc as Translations)[part];
    }
    return undefined;
  }, obj);
}

const translations: Record<Language, Translations> = {
  en: enTranslations,
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const setLanguageCallback = useCallback((lang: Language) => {
    setLanguage('en');
  }, []);

  const t = useCallback((key: string, replacements: Record<string, string | number> = {}): string => {
    const selectedLanguageTranslations = translations.en;
    let translation = getNestedTranslation(selectedLanguageTranslations, key);

    if (typeof translation !== 'string') {
        return key;
    }

    let strResult = translation;
    for (const placeholder in replacements) {
        strResult = strResult.replace(`{${placeholder}}`, String(replacements[placeholder]));
    }
    return strResult;

  }, []);


  const value = useMemo(() => ({
    language,
    setLanguage: setLanguageCallback,
    t,
  }), [language, setLanguageCallback, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const useTranslation = useLanguage;
