
'use client';

import React, { createContext, useContext, useState, ReactNode, useMemo, useCallback } from 'react';

type Language = 'es' | 'en' | 'fr' | 'de' | 'it' | 'pt';

// Define a nested structure for translations
type Translations = {
  [key: string]: string | Translations;
};

// --- SPANISH (BASE) ---
const esTranslations: Translations = {
    home: {
      hero_title: "Calidad Premium, Sensaciones Únicas",
      hero_subtitle: "Explora nuestra cuidada selección de poppers y descubre una pureza y potencia que redefine la experiencia.",
      section_title_new: "Novedades",
      section_title_offers: "Ofertas Especiales",
      section_title_bestsellers: "Lo Más Vendido",
      feature_secure_title: "Sítio Web 100% Seguro",
      feature_secure_desc: "Tu seguridad es nuestra prioridad.",
      feature_discreet_payment_title: "Pago Discreto",
      feature_discreet_payment_desc: "Sin referencias en tu extracto.",
      feature_discreet_packaging_title: "Embalaje Discreto",
      feature_discreet_packaging_desc: "Paquetes sin marcas ni logos.",
      feature_fast_shipping_title: "Entrega Rápida",
      feature_fast_shipping_desc: "Recibe tu pedido en 24/48h.",
      subscribe_title: "Suscríbete a nuestro boletín",
      subscribe_desc: "Puede cancelar su suscripción en cualquier momento. Para ello, consulte nuestra información de contacto en la declaración legal.",
      subscribe_placeholder: "Introduce tu email...",
      subscribe_button: "Suscribirse",
      subscribe_button_loading: "Suscribiendo...",
      subscribe_success: "¡Gracias por suscribirte!",
      subscribe_success_desc: "Pronto recibirás nuestras mejores ofertas.",
      subscribe_error: "Error en la suscripción",
      subscribe_error_desc: "No se pudo completar la suscripción. Por favor, inténtalo de nuevo.",
      subscribe_error_email: "Por favor, introduce tu dirección de email.",
    },
    header: {
      free_shipping: 'GRATIS +40€',
      fast_delivery: '24/48h',
      nav_menu: 'Menú de Navegación',
      products: 'Productos',
      create_pack: 'Crea tu Pack',
      monthly_dose: 'Dosis Mensual',
      product_links: {
        all: "TODOS LOS PRODUCTOS",
        small: "POPPERS PEQUEÑOS (10ML)",
        medium: "POPPERS MEDIOS (15ML)",
        large: "POPPERS GRANDES (25ML)",
        packs: "PACKS DE POPPERS",
        accessories: "ACCESORIOS PARA POPPERS",
        toys: "JUGUETES ERÓTICOS",
      },
      composition_links: {
        title: "COMPOSICIÓN",
        amyl: "POPPERS DE AMILO",
        pentyl: "POPPERS DE PENTILO",
        propyl: "POPPERS DE PROPILO",
        cbd: "POPPERS AL CBD",
        mix: "MIX DE NITRITOS",
      }
    },
    cart: {
        title: "Carrito de la Compra",
        empty_title: "Tu carrito está vacío",
        empty_subtitle: "Parece que aún no has añadido nada.",
        subtotal: "Subtotal",
        volume_discount: "Descuento por volumen",
        shipping_estimate: "Envío (estimado)",
        total_estimate: "Total Estimado:",
        free_shipping_banner: "¡Disfrutas de Envío GRATIS!",
        free_shipping_threshold: "Envío gratis en pedidos superiores a {price}",
        checkout_button: "Finalizar Compra y Pagar",
        discreet_packaging: "Embalaje 100% discreto.",
        notes: "El descuento por volumen y los gastos de envío finales se aplicarán en la pantalla de pago según el método elegido.",
        item_added: "Añadido al carrito",
        item_removed: "Producto eliminado",
        item_unavailable: "Agotado",
        stock_limit_reached: "Límite de stock alcanzado",
    },
    account: {
        layout_title: "Mi Cuenta",
        layout_description: "Gestiona tu información personal, pedidos y direcciones.",
        sidebar_admin_panel: "Panel de Admin",
        sidebar_dashboard: "Panel de Usuario",
        sidebar_orders: "Pedidos",
        sidebar_addresses: "Direcciones",
        sidebar_subscription: "Dosis Mensual",
        sidebar_logout: "Cerrar Sesión",
        dashboard_title: "Panel de Usuario",
        dashboard_welcome: "Bienvenido de nuevo, {name}.",
        dashboard_profile_title: "Información de Perfil",
        dashboard_profile_subtitle: "Tus datos personales.",
        dashboard_profile_name: "Nombre:",
        dashboard_profile_email: "Email:",
        dashboard_loyalty_title: "Puntos de Fidelidad",
        dashboard_loyalty_subtitle: "Gana puntos con cada compra.",
        dashboard_loyalty_points: "Puntos Acumulados",
        dashboard_loyalty_value: "Tu saldo equivale a un descuento de {price}.",
        orders_title: "Mis Pedidos",
        orders_subtitle: "Aquí puedes ver el historial de todas tus compras.",
        orders_empty_title: "Aún no tienes pedidos",
        orders_empty_subtitle: "Tu historial de compras aparecerá aquí.",
        orders_table_order_no: "Pedido Nº",
        orders_table_date: "Fecha",
        orders_table_status: "Estado",
        orders_table_total: "Total",
        orders_table_actions: "Acciones",
        orders_view_details_button: "Ver Detalles",
        order_details_title: "Detalles del Pedido",
        order_details_subtitle: "Pedido #{orderId}",
        order_details_back_button: "Volver a Pedidos",
        order_details_items_title: "Artículos del Pedido",
        order_details_summary_title: "Resumen",
        order_details_summary_date: "Realizado el {date}",
        order_details_summary_status: "Estado del pedido:",
        order_details_summary_subtotal: "Subtotal:",
        order_details_summary_total: "TOTAL:",
        order_details_shipping_address_title: "Dirección de Envío",
        order_details_not_found_title: "Pedido no encontrado",
        order_details_not_found_subtitle: "No hemos podido encontrar este pedido o no tienes permiso para verlo.",
        addresses_title: "Mis Direcciones",
        addresses_subtitle: "Gestiona tus direcciones de envío y facturación.",
        addresses_add_button: "Añadir Dirección",
        addresses_edit_button: "Editar",
        addresses_delete_button: "Eliminar",
        addresses_default_badge: "Por defecto",
        addresses_dialog_edit_title: "Editar Dirección",
        addresses_dialog_add_title: "Añadir Nueva Dirección",
        addresses_dialog_alias_label: "Alias de la dirección (ej. Casa, Trabajo)",
        addresses_dialog_name_label: "Nombre completo (Destinatario)",
        addresses_dialog_phone_label: "Teléfono",
        addresses_dialog_street_label: "Calle y número",
        addresses_dialog_city_label: "Ciudad",
        addresses_dialog_state_label: "Estado / Provincia",
        addresses_dialog_zip_label: "Código Postal",
        addresses_dialog_country_label: "País",
        addresses_dialog_default_label: "Establecer como dirección por defecto",
        addresses_dialog_cancel_button: "Cancelar",
        addresses_dialog_save_button: "Guardar",
        addresses_toast_save_success_title: "Dirección guardada",
        addresses_toast_save_success_desc: "Tu lista de direcciones ha sido actualizada.",
        addresses_toast_save_error_title: "Error",
        addresses_toast_save_error_desc: "No se pudo guardar la dirección.",
        addresses_toast_delete_success_title: "Dirección eliminada",
        addresses_toast_delete_success_desc: "La dirección ha sido eliminada.",
        addresses_toast_delete_error_desc: "No se pudo eliminar la dirección.",
        addresses_delete_confirm_title: "¿Estás seguro?",
        addresses_delete_confirm_desc: "Esta acción no se puede deshacer. Esto eliminará permanentemente esta dirección.",
        addresses_delete_confirm_continue: "Continuar",
        addresses_empty_placeholder: "Aún no tienes ninguna dirección guardada.",
        menu: {
          admin_title: "Cuenta de Admin",
          user_title: "Mi Cuenta",
          admin_panel: "Panel de Admin",
          user_dashboard: "Panel de Usuario",
          orders: "Pedidos",
          addresses: "Direcciones",
          logout: "Cerrar Sesión"
        },
        invalid_date: "Fecha inválida",
        date_unavailable: "Fecha no disponible",
        subscription: {
          title: "Personaliza tu Dosis Mensual",
          subtitle_open: "Elige tus productos favoritos para la caja de este mes.",
          subtitle_closed: "La ventana de selección está cerrada. Revisa el estado de tu envío.",
          timeline_info_title: "Ciclo de Suscripción",
          timeline_note: "Nota: Si no realizas ningún cambio, te enviaremos la misma selección que el mes anterior. Si es tu primer mes, te enviaremos una selección sorpresa de nuestros productos más vendidos.",
          loading_products: "Cargando productos...",
          error_title: "Error",
          products_load_error: "No se pudieron cargar los productos para la selección.",
          no_subscription_found: "No se encontró una suscripción activa para gestionar.",
          cancellation_success_title: "Suscripción Cancelada",
          cancellation_error_title: "Error al Cancelar",
          cancelling_button: "Cancelando...",
          manage_button: "Gestionar mi Suscripción",
          manage_dialog_title: "Gestionar Suscripción",
          manage_dialog_desc: "Actualmente, la gestión de la suscripción (como cambiar el método de pago) debe hacerse contactando a soporte. Sin embargo, puedes cancelar tu suscripción inmediatamente si lo deseas. ¿Estás seguro de que quieres cancelar tu suscripción?",
          manage_dialog_close: "Cerrar",
          manage_dialog_confirm: "Sí, cancelar suscripción",
          selected_badge: "Seleccionado",
          not_chosen_yet: "Aún no has elegido",
          change_selection_button: "Cambiar Selección",
          choose_product_button: "Elegir Producto",
          select_dialog_title: "Selecciona tu {type}",
          popper: "Popper",
          accessory: "Accesorio",
          select_button: "Seleccionar",
          save_success_title: "Selección Guardada",
          save_success_desc: "Hemos guardado tus preferencias para la caja de este mes.",
          save_error_desc: "No se pudo guardar tu selección. Inténtalo de nuevo.",
          box_on_its_way_title: "¡Tu caja está en camino!",
          box_on_its_way_desc: "Estamos preparando y enviando su pedido. En breves podrás disfrutar de él y del regalito. La próxima ventana de selección empieza el día 4.",
          popper_desc: "Elige tu aroma favorito.",
          accessory_desc: "Mejora tu experiencia.",
          surprise_gift_title: "Regalo Sorpresa",
          surprise_gift_desc: "Cada mes incluimos un detalle extra solo para miembros del club. ¡Déjate sorprender!",
          confirm_selection_button: "Confirmar mi selección para este mes",
          timeline_step1: "Inicio del Ciclo",
          timeline_step2: "Selección Abierta",
          timeline_step3: "Preparando Envío",
          failed_title: "Pago Fallido",
          failed_subtitle: "Lo sentimos, {name}, no hemos podido procesar tu suscripción.",
          user_placeholder: "usuario",
          failed_desc: "El pago no se pudo completar. Por favor, vuelve a intentarlo o prueba con otro método de pago. Si el problema persiste, no dudes en contactar con nosotros.",
          retry_button: "Reintentar Suscripción",
          contact_support_button: "Contactar Soporte",
          partial_title: "Pago Parcial Detectado",
          partial_subtitle: "Hemos recibido solo una parte del pago total.",
          partial_desc: "Tu suscripción no se activará hasta que se complete el pago total. Por favor, contacta con nuestro equipo de soporte para resolver esta incidencia y completar el pago restante.",
          success_title: "¡Suscripción Confirmada!",
          success_subtitle: "¡Felicidades, {name}! Ya eres parte del Club Dosis Mensual.",
          new_member_placeholder: "nuevo miembro",
          success_desc: "Hemos recibido tu primer pago correctamente. Tu primera caja se está preparando y pronto podrás personalizarla.",
          customize_box_button: "Personalizar mi Caja"
        }
    },
    subscription_page: {
        title: "Club Dosis Mensual",
        subtitle: "Accede a nuestro club exclusivo y recibe tus poppers favoritos en casa cada mes, ahorrando dinero y sin preocupaciones. ¡La forma más inteligente de disfrutar!",
        plan_title: "Tu Plan de Placer Mensual",
        plan_desc: "Una experiencia completa, entregada discretamente en tu puerta cada mes.",
        per_month: "/mes",
        price_desc: "Ahorra más de un 35%. Cancela cuando quieras, sin compromiso.",
        join_button: "Unirme al Club",
        processing_button: "Procesando...",
        howitworks_title: "¿Cómo Funciona el Club?",
        howitworks_subtitle: "Unirse es fácil y rápido. En solo tres pasos estarás disfrutando de tus beneficios exclusivos.",
        howitworks1_title: "1. Suscríbete",
        howitworks1_desc: "Únete al club con un pago seguro con tarjeta o criptomonedas. Es rápido y 100% fiable.",
        howitworks2_title: "2. Personaliza tu Caja",
        howitworks2_desc: "Desde tu panel de usuario, elige los poppers y el accesorio que quieres recibir cada mes.",
        howitworks3_title: "3. Disfruta y Ahorra",
        howitworks3_desc: "Recibe tu caja discretamente en casa y disfruta del mejor precio garantizado.",
        includes_title: "Tu Dosis Mensual Incluye",
        benefit1_title: "5 Poppers a tu Elección",
        benefit1_desc: "Explora nuestro catálogo y elige tus 5 aromas favoritos cada mes. ¡Ideal para descubrir novedades o asegurar tus clásicos!",
        benefit2_title: "1 Accesorio Práctico",
        benefit2_desc: "Recibe un accesorio útil para mejorar tu experiencia, como inhaladores, limpiadores o tapones especiales.",
        benefit3_title: "1 Regalo Sorpresa",
        benefit3_desc: "Nos encanta sorprenderte. Cada mes incluiremos un pequeño detalle extra solo para los miembros del club.",
        join_button_price: "Unirme al Club por {price}/mes",
        redirect_message: "Ya eres miembro. Redirigiendo a tu panel...",
        login_required_title: "Necesitas iniciar sesión",
        login_required_desc: "Por favor, inicia sesión para unirte al club.",
        redirecting_toast_title: "Redirigiendo a la pasarela de pago...",
        redirecting_toast_desc: "Completa el pago para activar tu suscripción.",
        start_error_generic: "No se pudo iniciar el proceso de suscripción.",
        start_error_title: "Error al suscribirse",
    },
    products: {
        title: "Nuestro Catálogo",
        subtitle: "Encuentra tu aroma perfecto. Usa los filtros para descubrir nuestra selección."
    },
    filters: {
        title: "Filtros",
        clear: "Limpiar",
        search: "Búsqueda",
        search_placeholder: "Buscar productos...",
        sort_by: "Ordenar por",
        sort_placeholder: "Seleccionar orden",
        sort_options: {
            name_asc: "Nombre (A-Z)",
            name_desc: "Nombre (Z-A)",
            price_asc: "Precio (Menor a Mayor)",
            price_desc: "Precio (Mayor a Menor)"
        },
        categories: "Categorías",
        category_options: {
            novedad: "Novedades",
            oferta: "Ofertas",
            "mas-vendido": "Más Vendidos",
            pack: "Packs",
            accesorio: "Accesorios"
        },
        brands: "Marcas",
        size: "Tamaño",
        composition: "Composición"
    },
    product_card: {
        sold_out: "Agotado",
        offer: "OFERTA",
        notify_me: "Avísame",
        add_to_cart: "Añadir"
    },
    product_info: {
        secure_payment: "Compra segura y pago discreto garantizado.",
        fast_shipping: "Envío rápido en 24/48h a toda la península.",
        discreet_packaging: "Embalaje 100% discreto sin marcas externas."
    },
    product_details: {
        description_tab: "Descripción",
        details_tab: "Detalles del producto"
    },
    related_products: {
        title: "Productos Relacionados"
    },
    stock_notification: {
        dialog_title: "Notificación de Stock",
        dialog_description: "Recibirás un único correo cuando {product_name} vuelva a estar disponible.",
        error_title: "Error",
        error_missing_info: "Falta información del producto o el email. Inténtalo de nuevo.",
        error_generic: "No se pudo procesar tu solicitud.",
        error_unexpected: "Ocurrió un error inesperado.",
        success_title: "¡Te avisaremos!",
        success_description: "Recibirás un email en {email} en cuanto {product_name} vuelva a estar disponible.",
        cancel_button: "Cancelar",
        submit_button: "Solicitar Notificación",
        sending_button: "Enviando..."
    },
    auth: {
      login_title: "Iniciar Sesión",
      login_subtitle: "Accede a tu cuenta para ver tus pedidos.",
      login_button: "Iniciar Sesión",
      logging_in_button: "Iniciando...",
      forgot_password_link: "¿Has olvidado tu contraseña?",
      no_account_prompt: "¿No tienes una cuenta?",
      register_link: "Regístrate",
      email_label: "Email",
      password_label: "Contraseña",
      register_title: "Crear Cuenta",
      register_subtitle: "Regístrate para una experiencia de compra más rápida.",
      register_button: "Registrarse",
      registering_button: "Creando cuenta...",
      confirm_password_label: "Confirmar Contraseña",
      password_strength_8_chars: "Al menos 8 caracteres",
      password_strength_uppercase: "Una letra mayúscula",
      password_strength_lowercase: "Una letra minúscula",
      password_strength_number: "Un número",
      password_strength_special: "Un carácter especial (!@#$...)",
      have_account_prompt: "¿Ya tienes una cuenta?",
      login_link: "Inicia Sesión",
      forgot_password_title: "Recuperar Contraseña",
      forgot_password_subtitle: "Introduce tu email y te enviaremos un enlace para restablecer tu contraseña.",
      forgot_password_success_subtitle: "Revisa tu bandeja de entrada (y la carpeta de spam).",
      send_recovery_link_button: "Enviar enlace de recuperación",
      sending_button: "Enviando...",
      back_to_login_button: "Volver a Iniciar Sesión",
      register_success_title: "¡Registro Completado!",
      register_success_subtitle: "¡Bienvenido/a, {name}! Tu cuenta ha sido creada con éxito.",
      register_success_description: "¿Qué te gustaría hacer ahora?",
      go_to_account_button: "Ir a mi Cuenta",
      continue_shopping_button: "Seguir Comprando"
    },
    pack_builder: {
      page_title: 'Crea tu Pack Personalizado',
      page_subtitle: 'Elige tus aromas favoritos de nuestro catálogo y construye el pack perfecto para ti.',
      step1_title: '1. Elige tus productos',
      products_in_pack: 'productos en tu pack',
      add_button: 'Añadir',
      step2_title: '2. Revisa tu pack',
      summary_title: 'Resumen del Pack',
      empty_pack_message: 'Selecciona productos de la izquierda para empezar a crear tu pack.',
      total_units: 'Unidades Totales',
      calculating_discount: 'Calculando descuento...',
      processing_payment: 'Procesando pago...',
      original_price: 'Precio Original',
      your_savings: 'Tu Ahorro',
      pack_total: 'Total del Pack',
      unlock_discount_message: 'Añade productos hasta superar 70€ para desbloquear descuentos.',
      buy_now_button: 'Comprar Pack Ahora',
      redirecting_button: 'Redirigiendo...',
      product_limit_title: 'Límite por producto',
      product_limit_desc: 'No puedes añadir más de {max} unidades del mismo producto.',
      sold_out_title: 'Producto Agotado',
      sold_out_desc: '{name} no está disponible actualmente.',
      stock_insufficient_title: 'Stock insuficiente',
      stock_insufficient_desc: 'Solo quedan {stock} unidades de {name}.',
      pack_limit_title: 'Límite del pack alcanzado',
      pack_limit_desc: 'No puedes añadir más de {max} productos a tu pack.',
      empty_pack_title: 'Pack vacío',
      empty_pack_desc: 'Añade al menos un producto para crear tu pack.',
      redirect_title: 'Redirigiendo al pago...',
      redirect_desc: 'Por favor, espera mientras preparamos tu compra segura.',
      checkout_error_title: 'Error en el Pago',
      checkout_error_desc: 'Ocurrió un error. Por favor, inténtalo de nuevo.',
    },
    popups: {
      age_verification_title: 'Verificación de Edad',
      age_verification_subtitle: 'Introduce tu fecha de nacimiento para continuar.',
      age_verification_exit_button: 'Salir',
      age_verification_enter_button: 'Entrar',
      age_verification_error_invalid: 'Por favor, introduce una fecha válida.',
      age_verification_error_underage: 'Debes ser mayor de {min_age} años para entrar.',
      welcome_title: '¡Bienvenido/a!',
      welcome_subtitle_part1: 'Suscríbete a nuestro boletín y obtén un',
      welcome_subtitle_discount: '10% de descuento',
      welcome_subtitle_part2: 'en tu primera compra.',
      welcome_open_offer_aria: 'Abrir oferta de suscripción',
      cookies_banner_text: 'Utilizamos cookies para mejorar tu experiencia. Puedes gestionar tus preferencias.',
      cookies_customize: 'Personalizar',
      cookies_reject: 'Rechazar',
      cookies_accept: 'Aceptar Todas',
      cookies_preferences_title: 'Preferencias de Cookies',
      cookies_preferences_desc: 'Gestiona qué cookies permites en nuestro sitio. Las cookies necesarias no se pueden desactivar.',
      cookies_technical: 'Técnicas (Siempre activas)',
      cookies_analytics: 'Análisis',
      cookies_marketing: 'Marketing',
      cookies_save: 'Guardar Preferencias',
    },
    notifications: {
      recent_purchase_title: '¡Compra Reciente!',
      recent_purchase_desc: '{name} de {location} acaba de comprar {quantity} x {product_name}.',
      real_order_title: '¡Pedido Real Confirmado!',
      a_city: 'una ciudad'
    },
    footer: {
      slogan: 'Tu tienda de confianza para aromas de calidad superior.',
      column_info: 'Información',
      column_guides: 'Guías',
      column_legal: 'Legal',
      column_help: 'Ayuda',
      link_legal_info: 'Información legal',
      link_terms: 'Términos y Condiciones',
      link_popper_sale: 'Venta de Popper',
      link_secure_payments: 'Pagos seguros',
      link_popper_info: 'Popper: todo lo que debes saber',
      link_leather_cleaners: 'Leather Cleaners Información',
      link_popper_shop: 'Tienda Popper',
      link_privacy: 'Privacidad y protección de datos',
      link_disputes: 'Resolución de litigios',
      link_cookies: 'Política de cookies',
      link_shipping: 'Envío y tarifas',
      link_contact: 'Contacte con nosotros',
      link_blog: 'Blog',
      link_docs: 'Docs del Sitio',
      copyright: 'Todos los derechos reservados.'
    },
    contact_page: {
        title: "Contacta con Nosotros",
        subtitle: "¿Tienes alguna pregunta o necesitas ayuda? Rellena el formulario y nuestro equipo se pondrá en contacto contigo.",
        email_card_title: "Email de Contacto",
        email_card_description: "Para consultas generales, envíanos un correo a:",
        legal_card_title: "Información Legal",
        legal_owner: "Titular",
        legal_address: "Dirección",
        form_card_title: "Enviar un mensaje",
        form_name: "Tu Nombre",
        form_name_placeholder: "John Doe",
        form_email: "Tu Email",
        form_email_placeholder: "tu@email.com",
        form_subject: "Asunto",
        form_subject_placeholder: "Consulta sobre un pedido",
        form_message: "Mensaje",
        form_message_placeholder: "Escribe tu consulta aquí...",
        form_submit_button: "Enviar Mensaje",
        form_sending_button: "Enviando...",
        success_toast_title: "¡Mensaje Enviado!",
        success_toast_description: "Gracias por contactarnos. Te responderemos lo antes posible.",
    },
    blog_page: {
      comments_title: 'Comentarios',
      no_comments: 'Sé el primero en comentar.',
      leave_comment_title: 'Deja un comentario',
      form_name_placeholder: 'Tu nombre',
      form_comment_placeholder: 'Escribe tu comentario...',
      form_submit_button: 'Enviar comentario'
    },
    shipping_page: {
      title: 'Envío y Tarifas',
      subtitle: 'En Popper Online, nos esforzamos para que recibas tu pedido lo antes posible, con la máxima discreción y seguridad.',
      policy_title: 'Envío de tu Paquete',
      policy_desc: 'Hacemos todo lo posible para que recibas tu pedido rápidamente. Ten en cuenta los siguientes puntos:',
      policy_item1: 'Los pedidos realizados antes de las 12:00h se expiden el mismo día (excepto en periodos promocionales, festivos en Francia o alto volumen de pedidos).',
      policy_item2: 'Todos los pedidos se envían en un plazo de 24 horas laborables (L-V), excluyendo festivos.',
      policy_item3: 'Nuestros envíos son siempre discretos y anónimos, sin ninguna referencia al contenido o a nuestra tienda en el exterior del paquete.',
      rates_alert_title: 'Aviso Importante Sobre las Tarifas',
      rates_alert_desc: 'Las tarifas y transportistas que se muestran a continuación son orientativos y se basan en nuestros socios logísticos de referencia. El coste final del envío se calculará durante el proceso de pago y puede variar según las condiciones específicas del transportista en el momento de la compra.',
      rates_title: 'Tarifas de Envío',
      rates_subtitle: 'Gratis a partir de 39€ para Península Ibérica, Francia, Portugal, Alemania, Italia, Bélgica, Luxemburgo y Países Bajos.',
      domestic_title: 'España (Península), Francia, Portugal, Alemania, Italia, etc.',
      home_delivery: 'Envío a domicilio:',
      carrier: 'Transportista',
      rate: 'Tarifa',
      delivery_time: 'Plazo de Entrega',
      pickup_points: 'A puntos de recogida:',
      islands_title: 'Islas Baleares, Canarias, Ceuta y Melilla',
      islands_desc: 'Plazos sujetos a procedimientos aduaneros.',
      europe_title: 'Resto de Europa',
      europe_desc: 'A domicilio y puntos de recogida.',
      world_title: 'Envíos al Resto del Mundo',
      zone: 'Zona',
      world_rate: 'Tarifa (a domicilio con Chrono Express)',
      additional_info_title: 'Información Adicional',
      tracking_title: 'Seguimiento y Aviso de Entrega',
      tracking_desc: 'Recibirás un email con el número de seguimiento cuando tu pedido sea enviado. Si no estás en casa, el transportista dejará un aviso para organizar una nueva entrega o indicará el punto de recogida más cercano.',
      customs_title: 'Envíos Internacionales y Aduanas',
      customs_desc: 'Para pedidos fuera de la UE, es posible que se apliquen costes aduaneros. Popper Online no se hace responsable de estas tarifas, impuestos o derechos adicionales. Como cliente, actúas como importador y asumes la responsabilidad de estos costes.',
      final_note: 'Atención: Los plazos son indicativos y dependen del transportista. Direcciones incorrectas o causas de fuerza mayor (huelgas, etc.) pueden causar retrasos. Los costes de reenvío por dirección incorrecta o no recogida del paquete correrán a cargo del cliente.',
      explore_button: 'Explorar Catálogo'
    },
    legal_info: {
      title: "Información Legal",
      owner_label: "Titular del Sitio Web:",
      abn_label: "ABN:",
      address_label: "Dirección:",
      contact_label: "Contacto:",
      logistics_label: "Logística y Distribución:",
      logistics_value: "Los pedidos se gestionan y envían desde Francia. Para cumplir con los máximos estándares regulatorios de la Unión Europea, solo se envían a países cuyo uso es legal.",
      usage_warning_title: "Advertencia sobre el Uso",
      usage_warning_desc: "Venta para usos técnicos, cosméticos o aromáticos. El consumo humano y el uso recreativo están estrictamente prohibidos y son desaconsejados.",
      cancellation_right_title: "Derecho de Cancelación",
      cancellation_right_desc: "Nos reservamos el derecho a cancelar cualquier pedido si se realiza desde una ubicación cuya legalidad es cuestionable o si sospechamos que se omitirá un uso legal del producto.",
      explore_button: "Explorar Catálogo"
    },
    terms_page: {
        title: "Términos y Condiciones Generales",
        welcome: "Bienvenido a www.comprarpopperonline.com. Le pedimos que lea atentamente las Condiciones Generales, nuestra Política de Cookies y nuestra Política de Privacidad, ya que éstas regulan su acceso y uso de este sitio.",
        acceptance: "Tanto el uso como las ventas realizadas a través de la tienda online suponen la aceptación por parte del Cliente de los Términos y Condiciones, nuestra Política de Cookies y nuestra Política de Privacidad que se establecen en cumplimiento de la legislación aplicable.",
        explore_button: "Explorar Catálogo",
        section1_title: "1. Partes implicadas",
        section1_1: "<strong>1.1. Identificación del Vendedor:</strong> La venta de productos a través de este sitio web es realizada por la entidad registrada bajo la marca comercial MARY AND POPPER (ABN 37 588 057 135), con domicilio social en U 2 58 MAIN ST, OSBORNE PARK WA 6017, AUSTRALIA. Esta entidad opera como Vendedor a consumidores mayores de 18 años.",
        section1_2: "<strong>1.2. Logística y Suministro:</strong> Las presentes Condiciones regulan la compra de productos, cuya gestión logística y expedición (fulfillment) se realiza a través de un socio colaborador con sede en Francia. El Vendedor no es responsable del suministro de bienes o servicios por parte de entidades distintas al Vendedor o su socio logístico.",
        section1_3: "La información o los datos personales facilitados serán tratados de acuerdo con nuestra Política de Privacidad. Al utilizar este sitio, usted acepta el tratamiento de la información y los datos y declara que toda la información y los datos proporcionados son verdaderos y exactos.",
        section1_4: "El Cliente se identificará a través de los datos facilitados en el Pedido. Está prohibido proporcionar datos falsos y/o inventados: el Vendedor queda exento de cualquier responsabilidad al respecto.",
        section2_title: "2. Alcance del contrato",
        section2_p1: "La información a la que se refieren las presentes Condiciones Generales en línea y los datos contenidos en el Sitio Web no constituyen una oferta al público, sino una invitación a realizar un Pedido. Tras el envío de la Propuesta de Pedido, el Cliente recibirá un correo electrónico de confirmación de recepción (\"Confirmación de Pedido\"). Este correo electrónico no constituye la aceptación del Pedido, que sólo se considerará aceptado cuando el Cliente reciba un correo electrónico confirmando que el Pedido ha sido aceptado y que el Pago ha sido aceptado (\"Pago Aceptado\"). El contrato de compra en línea (\"Contrato\") sólo se considerará concluido cuando el Cliente reciba la Confirmación de Pedido y Envío.",
        section3_title: "3. Precio",
        section3_p1: "Los precios que figuran en el catálogo de este sitio web incluyen el IVA al tipo legal vigente y pueden variar sin previo aviso. Es responsabilidad del Vendedor comprobar la exactitud de los Precios antes de enviar la Confirmación de Pedido. En caso de error, el Cliente será contactado para confirmar si desea proceder con el precio correcto o cancelar el pedido. Los pagos se realizan siempre en euros (€).",
        section4_title: "4. Métodos de Pago",
        section4_p1: "El Vendedor utiliza servicios de pago seguros y certificados. Toda la información personal de pago es encriptada mediante una conexión SSL (Secure Sockets Layer). El Vendedor no almacena ni tiene acceso a los datos sensibles de las tarjetas de crédito o débito del Cliente. Al utilizar un proveedor de servicios de pago externo, el Cliente acepta que el procesamiento de su pago estará sujeto a los términos, condiciones y políticas de privacidad de dicho proveedor, y que cualquier responsabilidad relacionada con la transacción de pago recae sobre esa entidad. Aceptamos pagos a través de Tarjeta de crédito/débito (Visa, Mastercard, Amex) y Transferencia Bancaria.",
        section5_title: "5. Pedidos y Envíos",
        section5_p1: "Los pedidos pagados antes de las 12:00 (hora española) en día hábil (de lunes a viernes, exceptuando festivos nacionales y locales de Francia) se envían generalmente el mismo día. Los productos se envían en un paquete discreto sin referencias al contenido. En caso de falta de stock, contactaremos al cliente para ofrecer una solución. Los plazos de entrega son indicativos y pueden variar.",
        section6_title: "6. Cambios, Devoluciones y Anulaciones",
        section6_p1: "El cliente dispone de 14 DÍAS NATURALES desde la recepción para solicitar un cambio o devolución, siempre que los productos no hayan sido utilizados, lavados o dañados y conserven su embalaje original. Para ejercer este derecho, debe contactar con nuestro Servicio de Atención al Cliente.",
        section9_title: "9. Información Adicional y Advertencias de Producto",
        section9_1: "<strong>9.1. Usos Permitidos y Advertencia Sanitaria:</strong> El Cliente acepta que la finalidad de los productos vendidos por MARY AND POPPER es estrictamente para usos técnicos, cosméticos, o aromáticos externos. El Cliente se compromete a no ingerir, inhalar con fines recreativos, inyectar, o aplicar en mucosas o heridas cualquiera de los productos. El Vendedor queda exento de cualquier responsabilidad por daños a la salud derivados del incumplimiento de esta advertencia o de un uso distinto al declarado.",
        section9_2: "<strong>9.2.</strong> La información y servicios proporcionados en este sitio son solo con fines informativos y no sustituyen el consejo de un profesional de la salud. Consulte siempre a su médico o farmacéutico antes de utilizar cualquier producto.",
        section11_title: "11. Legalidad y Conformidad del Cliente",
        section11_1: "<strong>11.1. Riesgo y Responsabilidad de la Importación:</strong> El Cliente actúa como IMPORTADOR FINAL de los productos. El Vendedor no garantiza la legalidad del producto en el país de destino. Cualquier coste aduanero, arancel, impuesto de importación, o la confiscación del paquete por parte de autoridades locales será asumido única y exclusivamente por el Cliente, sin derecho a reembolso del Vendedora.",
        section11_2: "<strong>11.2. Confirmación del Cliente:</strong> Al realizar un pedido usted confirma tener como mínimo 18 años de edad. Usted conoce el uso y los posibles efectos secundarios del producto, y antes de adquirirlo se ha informado adecuadamente. Usted libera de cualquier responsabilidad a MARY AND POPPER, sus empleados, proveedores y todas las personas asociadas por daños resultantes del mal uso de nuestros artículos.",
        section12_title: "12. Derecho de Rescisión y Plazo Legal (UE)",
        section12_p1: "De acuerdo con la reglamentación europea aplicable a la Ley Francesa, el consumidor dispone de 14 DÍAS CORRIDOS a contar desde la recepción de los bienes para ejercer el derecho de rescisión del contrato. Para ello, debe comunicar su decisión a MARY AND POPPER a través de una declaración inequívoca. Los gastos de devolución de los bienes son asumidos por el consumidor. El derecho de rescisión no se aplica, en ninguna circunstancia, al suministro de productos sellados que no sean aptos para ser devueltos por razones de protección de la salud o de higiene si han sido abiertos tras la entrega. Esto incluye expresamente aceites, flores, e-líquidos o cualquier producto de CBD/aromático cuyo embalaje o sello de seguridad haya sido abierto o manipulado.",
        section14_title: "14. Ley Aplicable, Resolución de Conflictos y Jurisdicción",
        section14_1: "<strong>14.1. Ley Aplicable:</strong> Este contrato se rige, en primer lugar, por la Ley Francesa, en virtud de la localización de expedición de los bienes, y de forma supletoria, por la legislación de Australia.",
        section14_2: "<strong>14.2. Jurisdicción:</strong> Para la resolución de cualquier disputa, la jurisdicción del Distrito de Perpiñán es competente, con renuncia a cualquier otra.",
        section15_title: "15. Contactos",
        section15_p1: "MARY AND POPPER (ABN 37 588 057 135)<br/>U 2 58 MAIN ST<br/>OSBORNE PARK WA 6017<br/>AUSTRALIA<br/>Contacto para Reclamaciones/Apoyo: info@comprarpopperonline.com<br/>Contacto para Notificaciones Legales (Ejercicio del Derecho de Rescisión, etc.): Cualquier comunicación de naturaleza legal o ejercicio de derechos contractuales deberá realizarse por correo electrónico al contacto de apoyo e, idealmente, ser respaldada por correo certificado al domicilio social en Australia.",
        section16_title: "16. Nulidad Parcial",
        section16_p1: "Si alguna cláusula de las presentes Condiciones es declarada nula o inaplicable por una autoridad competente o tribunal, la validez de las restantes cláusulas no se verá afectada, manteniéndose el Contrato en vigor en sus restantes términos. El Vendedor se compromete a sustituir la cláusula nula o inaplicable por otra de efecto legal y económico equivalente.",
    },
    venta_popper_page: {
      "title": "Venta de Poppers: Calidad, Seguridad y Legislación",
      "subtitle": "Nuestra tienda online de referencia se dedica a ofrecer Poppers de alta calidad para usos técnicos, cosméticos y aromáticos, asegurando que cada producto cumpla con la legislación vigente.",
      "what_is_title": "¿Qué es el Popper y cuáles son sus usos legales?",
      "definition_title": "Definición Detallada",
      "definition_p": "El término \"popper\" se refiere popularmente a los nitritos de alquilo (amilo, pentilo o propilo). Son compuestos químicos volátiles que en nuestra tienda se comercializan exclusivamente como <strong>limpiadores de cuero, solventes o ambientadores técnicos</strong>. Su función es la de un solvente y no están diseñados ni deben ser utilizados para el consumo humano.",
      "uses_title": "Usos Oficiales Permitidos (¡No Recreativos!)",
      "uses_p": "Para garantizar el cumplimiento de nuestras condiciones de venta, todos nuestros productos tienen las siguientes aplicaciones legales:",
      "use_item1": "<strong>Uso Técnico/Ambientador:</strong> Para la limpieza profesional de superficies o cuero.",
      "use_item2": "<strong>Uso Cosmético/Aromaterapia:</strong> Como esencia para perfumería o aromatización de ambientes.",
      "use_item3": "<strong>Coleccionismo:</strong> Para fines de estudio o colección.",
      "warning_title": "Aviso Crucial: Uso Recreativo Prohibido",
      "warning_p": "El consumo humano o el uso recreativo de cualquiera de nuestros productos está expresamente prohibido y desaconsejado. El incumplimiento de este aviso es de exclusiva responsabilidad del cliente. Dicho uso viola nuestras Condicones Generales de Venta y puede ser perjudicial para la salud.",
      "variety_title": "Nuestra Variedad: Un Catálogo para Cada Necesidad Técnica",
      "variety_p": "Ponemos a tu disposición una rigurosa selección de Poppers clasificados por su composición y finalidad técnica:",
      "table_header_variety": "Variedad o Fórmula",
      "table_header_description": "Descripción Detallada",
      "table_header_application": "Aplicación Técnica Sugerida",
      "amyl_description": "Considerado uno de los más potentes, ofrece una acción de limpieza profunda y un aroma intenso. Ideal para uso profesional por su alta pureza.",
      "amyl_application": "Limpieza de cuero muy envejecido o curtido, ambientación de grandes espacios.",
      "propyl_description": "Más suaves y de acción rápida. Frecuentes en marcas de uso general. Buena opción para quienes buscan un resultado rápido y un aroma más ligero.",
      "propyl_application": "Mantenimiento diario de cuero, limpieza de superficies delicadas.",
      "pentyl_description": "Famosos por la durabilidad de su efecto. Excelentes para fines donde se requiere un resultado sostenido y una evaporación más controlada.",
      "pentyl_application": "Limpieza de objetos de coleccionismo, uso en marroquinería de alta gama.",
      "services_title": "Servicios de la Tienda: Confidencialidad y Eficiencia",
      "services_p": "Te garantizamos una experiencia de compra sencilla y segura, respaldada por nuestro compromiso con la discreción y la rapidez:",
      "fast_shipping_title": "Envío Rápido y Totalmente Discreto",
      "fast_shipping_p": "Todos los productos se envían en un embalaje sin referencias externas. Los pedidos pagados antes de las 12:00h en día hábil se expiden el mismo día.",
      "legality_title": "Legalidad y Logística",
      "legality_p": "Solo vendemos artículos que cumplen la normativa. Tu pedido se gestiona desde Francia para garantizar una logística eficiente en la UE.",
      "prices_title": "Precios Competitivos",
      "prices_p": "Gracias a la relación directa con los fabricantes, ofrecemos precios imbatibles, descuentos por volumen y packs de ahorro.",
      "legal_title": "Legalidad, Envío y Responsabilidad del Cliente",
      "legal_p1": "Nuestros productos se gestionan y envían desde Francia, donde la venta de poppers como limpiadores de cuero o ambientadores es legal. Esto nos permite asegurar una logística eficiente dentro de la Unión Europea. Sin embargo, es fundamental que como cliente conozcas tus responsabilidades.",
      "import_warning_title": "Aviso sobre el Uso y la Responsabilidad de Importación",
      "import_warning_use": "<strong>Uso Previsto:</strong> La venta de nuestros productos es exclusively para usos técnicos, cosméticos o aromáticos. El consumo humano y el uso recreativo están terminantemente prohibidos.",
      "import_warning_responsibility": "<strong>Responsabilidad del Cliente como Importador:</strong> Tú, como cliente, actúas como el importador final del producto. Es tu responsabilidad asegurarte de que el producto es legal en tu país de destino. Cualquier coste aduanero, tasa, impuesto de importación o la incautación del paquete serán asumidos exclusivamente por ti, sin derecho a reembolso por nuestra parte.",
      "import_warning_cancellation": "<strong>Derecho de Cancelación:</strong> Nos reservamos el derecho de cancelar cualquier pedido si sospechamos que se le dará un uso indebido o si se envía a un lugar donde su legalidad sea cuestionable.",
      "explore_button": "Explorar Catálogo Completo"
    },
    secure_payments_page: {
        "title": "Pagos Seguros y Discretos",
        "subtitle": "Tu seguridad y privacidad son nuestra máxima prioridad. Aquí te explicamos cómo gestionamos tus transacciones.",
        "philosophy_title": "Nuestra Filosofía de Pagamento",
        "philosophy_p": "Para ofrecerte una experiencia de compra sencilla y accesible, hemos optado por métodos de pago manuales. Esto nos permite mantener la máxima discreción y evitar las complejidades de las pasarelas de pago automáticas.",
        "protected_info_title": "Tus Informaciones están Protegidas",
        "protected_info_p": "Tus datos de pago nunca se almacenan en nuestros servidores. Las transacciones se gestionan offline (pago contra reembolso) o a través de plataformas seguras como la de tu banco, garantizando tu privacidad.",
        "methods_title": "Métodos de Pago Aceptados",
        "methods_p": "Ofrecemos varias opciones para tu comodidad:",
        "cod_title": "Pago Contra Reembolso",
        "cod_p": "Paga en efectivo, con tarjeta o Bizum directamente al repartidor cuando recibas tu pedido.",
        "prepaid_title": "Pago Anticipado",
        "prepaid_p": "Realiza el pago a través de Bizum o transferencia bancaria. Recibirás las instrucciones por email al confirmar tu reserva.",
        "discretion_alert_title": "Nota sobre la Discreción",
        "discretion_alert_p": "Para proteger tu privacidad, el concepto que aparecerá en tus extractos bancarios o en Bizum será genérico y no hará referencia a este sitio web ni a los productos comprados.",
        "explore_button": "Explorar Catálogo"
    },
    popper_info_page: {
        "title": "Popper: todo lo que debes saber",
        "subtitle": "Una guía completa sobre su composición, efectos, riesgos y las mejores prácticas de seguridad.",
        "what_is_title": "¿Qué son exactamente los Poppers?",
        "what_is_p1": "\"Popper\" es el término coloquial para los <strong>nitritos de alquilo</strong>. Es un líquido químico volátil clasificado como depresor, lo que significa que ralentiza la comunicación between el cerebro y el cuerpo.",
        "what_is_p2": "Su característica principal es que son <strong>vasodilatadores</strong>: dilatan los vasos sanguíneos y relajan los músculos lisos (los que no controlamos voluntariamente), lo que provoca una bajada temporal de la presión arterial.",
        "types_alert_title": "Tipos de Nitritos Comunes",
        "types_alert_p": "Existen diversas fórmulas, como el nitrito de amilo, el nitrito de pentilo, el nitrito de propilo y el nitrito de isopropilo. Cada una tiene matices diferentes en su efecto y duración.",
        "form_title": "Forma, Olor y Uso Histórico",
        "form_p1": "Se presentan como un líquido incoloro o amarillento en pequeñas botellas de cristal (generalmente de 9 a 30ml). Su olor es muy característico y a menudo descrito como fuerte y químico, similar a disolventes o \"calcetines sucios\".",
        "form_p2": "Originalmente, el nitrito de amilo se usaba en medicina para tratar la angina de pecho. Su uso recreativo se popularizó posteriormente, especialmente en la cultura de club y entre hombres que tienen sexo con hombres, por su capacidad para desinhibir y relajar los músculos, facilitando el sexo anal. Hoy en día, su uso se ha extendido como \"droga de fiesta\".",
        "effects_title": "Efectos Inmediatos y Duración",
        "effects_p": "Los efectos son casi instantáneos, pero muy breves, durando entre <strong>2 y 5 minutos</strong>. El cuerpo de cada persona reacciona de manera diferente dependiendo de su salud, peso, cantidad inhalada y si se combina con otras sustancias. Los efectos más comunes incluyen:",
        "effect1": "Euforia inicial y sensación de calor.",
        "effect2": "Enrojecimiento del rostro y aumento del ritmo cardíaco.",
        "effect3": "Mareos y, a veces, dolores de cabeza.",
        "effect4": "Relajación involuntaria de los músculos lisos (esfínter anal y vaginal).",
        "effect5": "Disminución de las inhibiciones y alteración del juicio.",
        "effect6": "Posibles distorsiones visuales y aumento de la conciencia sensual.",
        "effect7": "Náuseas, visión borrosa o hemorragias nasales en algunos casos.",
        "addiction_title": "¿Los Poppers son Adictivos?",
        "addiction_p": "El uso de poppers <strong>no se considera físicamente adictivo</strong>, ya que no genera síndrome de abstinencia. Sin embargo, puede crear una <strong>dependencia psicológica</strong>, especialmente vinculada al sexo. Algunos usuarios pueden sentir que no pueden disfrutar de las relaciones sexuales de la misma manera sin su efecto.",
        "safety_warning_title": "Salud y Seguridad: Advertencias Cruciales",
        "safety_warning1": "<strong>¡NUNCA INGERIR!</strong> El líquido es altamente tóxico si se ingiere. Puede causar ceguera, daño cerebral, fallo orgánico y la muerte.",
        "safety_warning2": "<strong>CONTACTO CON LA PIEL:</strong> El líquido es un irritante fuerte. Evita el contacto directo con la piel, ya que puede causar quemaduras químicas. Si ocurre, lava la zona con abundante agua.",
        "safety_warning3": "<strong>GRUPOS DE RIESGO:</strong> Personas con anemia, problemas cardíacos, presión arterial alta o baja, glaucoma o que hayan sufrido un traumatismo craneoencefálico deben evitar su uso.",
        "mixing_title": "Riesgos al Mezclar con Otras Drogas",
        "mixing_viagra_title": "Popper + Viagra (o similar)",
        "mixing_viagra_p": "Caída extrema y peligrosa de la presión arterial, riesgo de desmayo y emergencia médica.",
        "mixing_speed_title": "Popper + Anfetaminas (Speed)",
        "mixing_speed_p": "Aumento drástico de la presión sobre el corazón, sometiendo el cuerpo a estrés adicional.",
        "long_term_title": "Efectos a Largo Plazo",
        "long_term_p": "Aunque no se han demostrado efectos graves a largo plazo con un uso esporádico y correcto, el uso frecuente y prolongado puede conllevar riesgos:",
        "long_term1": "Irritación de la piel (sarpullido) alrededor de la boca, nariz y ojos con uso frecuente.",
        "long_term2": "Quemaduras en la piel si el líquido entra en contacto directo.",
        "long_term3": "Riesgo de maculopatía (pérdida de visión), asociado principalmente al nitrito de isopropilo.",
        "long_term4": "Aumento de la presión ocular, peligroso para personas con glaucoma.",
        "long_term5": "Posible afectación a largo plazo del suministro sanguíneo con un uso abusivo y continuado.",
        "explore_button": "Ver Nuestro Catálogo"
    },
    privacy_page: {
        "title": "Privacidad y Protección de Datos",
        "subtitle": "Descubre cómo protegemos y gestionamos tus datos personales en nuestra tienda. Tu seguridad y confianza son nuestra prioridad.",
        "commitment_title": "Nuestro Compromiso",
        "commitment_p1": "Esta política de privacidad está diseñada para ayudarte a entender qué información recopilamos, por qué la recopilamos y cómo puedes gestionarla. Estamos sujetos a las regulaciones más estrictas y solo utilizaremos tus datos personales para fines claramente identificados y de acuerdo con tus derechos.",
        "commitment_p2": "Dado que las leyes de tecnología y protección de datos están en constante evolución, esta Política puede ser actualizada. Al utilizar nuestro sitio web, aceptas esta política. Todos los datos serán conservados durante el periodo legalmente requerido, respetando las garantías de confidencialidad del RGPD (Reglamento General sobre la Protección de Datos).",
        "who_is_responsible_title": "1. ¿Quién es el responsable del tratamiento de tus datos?",
        "who_is_responsible_p": "El responsable del tratamiento de los datos es <strong>MARY AND POPPER</strong> (ABN 37 588 057 135), con domicilio social en U 2 58 MAIN ST, OSBORNE PARK WA 6017, AUSTRALIA. Puedes contactarnos en cualquier momento en: <a href=\"mailto:info@comprarpopperonline.com\" class=\"text-primary font-semibold hover:underline\">info@comprarpopperonline.com</a>.",
        "what_data_title": "2. ¿Qué datos recopilamos de ti?",
        "what_data_p": "Dependiendo de tu interacción con nosotros, podemos recopilar:",
        "what_data_item1": "<strong>Datos de Identificación y Cuenta:</strong> Nombre, email, contraseña, fecha de nacimiento, número de teléfono.",
        "what_data_item2": "<strong>Datos para Pedidos:</strong> Dirección de envío, NIF y datos de facturación.",
        "what_data_item3": "<strong>Historial de Cliente:</strong> Compras realizadas, estado de los pedidos, carritos abandonados, reclamaciones, etc.",
        "what_data_item4": "<strong>Datos de Navegación:</strong> Dirección IP, navegador, sistema operativo y páginas visitadas. Utilizamos <strong>Microsoft Clarity</strong> para entender cómo interactúas con el sitio y mejorar tu experiencia.",
        "what_for_title": "3. ¿Para qué se utilizan tus datos?",
        "what_for_p1": "<strong>Compra y gestión de pedidos:</strong> Para procesar tus compras, gestionar los envíos, la facturación y los pagos.",
        "what_for_p2": "<strong>Atención al cliente:</strong> Para responder a tus preguntas y ayudarte con cualquier necesidad.",
        "what_for_p3": "<strong>Envío de newsletters (Marketing):</strong> Con tu consentimiento, te enviamos promociones y novedades a través de nuestro proveedor <strong>Klaviyo</strong>.",
        "what_for_p4": "<strong>Elaboración de perfiles:</strong> Analizamos hábitos de consumo de forma agregada para mejorar nuestros productos y personalizar ofertas, siempre respetando tu privacidad.",
        "share_data_title": "4. ¿Compartimos tus datos con terceros?",
        "share_data_p": "Para poder ofrecerte nuestros servicios, necesitamos compartir tus datos con socios de confianza, siempre con la máxima seguridad y solo la información estrictamente necesaria:",
        "stripe_title": "Procesadores de Pago (Stripe)",
        "stripe_p": "Tus datos de pago (tarjeta de crédito/débito) se envían de forma encriptada directamente a <strong>Stripe</strong>. Nunca vemos ni almacenamos esta información sensible.",
        "klaviyo_title": "Marketing y Comunicaciones (Klaviyo)",
        "klaviyo_p": "Si te suscribes a nuestra newsletter, tu email será gestionado a través de <strong>Klaviyo</strong> para el envío de comunicaciones.",
        "firebase_title": "Infraestructura y Base de Datos (Firebase)",
        "firebase_p": "Los datos de tu cuenta (perfil, pedidos, direcciones) se almacenan de forma segura en <strong>Firebase</strong>, la plataforma de Google que utilizamos para el funcionamiento de la aplicación.",
        "clarity_title": "Análisis de Uso (Microsoft Clarity)",
        "clarity_p": "Compartimos datos de interacción anónimos con <strong>Microsoft Clarity</strong> para analizar el uso del sitio y mejorarlo.",
        "share_data_p2": "Además, compartimos datos con las empresas de logística para poder entregarte tus pedidos.",
        "your_rights_title": "5. ¿Cuáles son tus derechos?",
        "your_rights_p": "Tienes derecho a:",
        "your_rights_item1": "<strong>Acceder</strong> a tus datos y obtener una copia de los mismos.",
        "your_rights_item2": "<strong>Rectificar</strong> tus datos si son incorrectos o están incompletos.",
        "your_rights_item3": "<strong>Suprimir</strong> tus datos cuando ya no sean necesarios.",
        "your_rights_item4": "<strong>Limitar</strong> el tratamiento de tus datos en determinadas circunstancias.",
        "your_rights_item5": "<strong>Oponerte</strong> al tratamiento de tus datos para fines de marketing.",
        "your_rights_item6": "Solicitar la <strong>portabilidad</strong> de tus datos.",
        "your_rights_p2": "Puedes ejercer estos derechos en cualquier momento contactándonos en <a href=\"mailto:info@comprarpopperonline.com\" class=\"text-primary font-semibold hover:underline\">info@comprarpopperonline.com</a>.",
        "explore_button": "Explorar Catálogo"
    },
    leather_cleaners_page: {
        "title": "Limpadores de Couro: Informações Essenciais",
        "subtitle": "Um guia claro sobre o propósito, venda e uso dos nossos produtos para garantir uma compra segura e informada.",
        "philosophy_title": "A Nossa Filosofia: \"Limpadores de Couro\"",
        "philosophy_p1": "Na nossa loja, os produtos coloquialmente conhecidos como \"poppers\" são comercializados sob o seu propósito técnico e legal: <strong>Limpadores de Couro</strong>. Entendemos que muitos clientes conhecem estes produtos pelo seu nome popular, e o nosso marketing visa facilitar a sua pesquisa.",
        "philosophy_p2": "No entanto, o nosso objetivo é ser transparentes e rigorosos. Todos os produtos líquidos que oferecemos são especificamente concebidos e fabricados para a <strong>limpeza e condicionamento de roupa erótica, brinquedos e acessórios de couro</strong>.",
        "quality_alert_title": "Qualidade e Regulamentos Europeus",
        "quality_alert_p": "Os nossos produtos são fabricados de acordo com os regulamentos europeus, garantindo a sua pureza e segurança para os usos técnicos previstos. Não são adequados nem fabricados para consumo humano.",
        "recreational_use_alert_title": "Uso Recreativo Estritamente Proibido",
        "recreational_use_alert_p": "Distanciamo-nos completamente do abuso dos nossos produtos como afrodisíacos, produtos de estimulação sexual ou qualquer outro uso indevido. A inalação direta do frasco é proibida. O consumo humano é perigoso e viola os nossos termos de venda.",
        "commitment_title": "O Seu Compromisso e Responsabilidade como Cliente",
        "commitment_p": "Ao efetuar uma encomenda, confirma e aceita as seguintes condições:",
        "commitment_item1": "Declara ter <strong>mais de 18 anos</strong>.",
        "commitment_item2": "Confirma conhecer o <strong>uso técnico e os possíveis efeitos secundários</strong> do produto, e que se informou adequadamente antes da compra.",
        "commitment_item3": "Leu e aceita os nossos <a href=\"/terminos-y-condiciones\" class=\"text-primary hover:underline font-semibold\">Termos e Condições Gerais</a>.",
        "commitment_item4": "Atua como <strong>importador final</strong> do produto, assumindo a responsabilidade pela legalidade do produto no seu país de destino e por quaisquer procedimentos ou custos alfandegários.",
        "commitment_p2": "Isenta a empresa proprietária, os seus funcionários e fornecedores de qualquer responsabilidade por danos resultantes do uso indevido dos nossos artigos.",
        "policy_title": "A Nossa Política de Venda e Envio",
        "logistics_title": "Logística a partir da União Europeia",
        "logistics_p": "Todos os nossos produtos são enviados a partir de França, dentro da União Europeia, garantindo uma gestão logística eficiente e o cumprimento dos regulamentos do país de origem para a venda destes produtos técnicos.",
        "cancellation_alert_title": "Direito de Cancelamento e Responsabilidade de Importação",
        "cancellation_alert_p1": "Reservamo-nos o direito de <strong>cancelar qualquer encomenda</strong> se suspeitarmos que será utilizada indevidamente ou se for destinada a um local onde a sua legalidade seja questionável.",
        "cancellation_alert_p2": "O cliente, na qualidade de <strong>importador final</strong>, é o único responsável por garantir que o produto é legal no seu país. Os custos alfandegários, taxas ou apreensões são da exclusiva responsabilidade do cliente, sem direito a reembolso da nossa parte.",
        "explore_button": "Explorar Catálogo"
    },
    popper_shop_page: {
        "title": "Loja de Poppers – Venda dos Melhores Aromas",
        "subtitle": "Bem-vindo à melhor loja de poppers em Espanha. Descubra uma grande variedade de poppers, com as melhores ofertas e os preços mais baixos.",
        "who_we_are_title": "Quem Somos",
        "who_we_are_subtitle": "A sua loja de confiança com mais de 30 anos de experiência.",
        "who_we_are_p": "Somos uma das melhores lojas de poppers online, e na nossa loja pode encontrar os melhores poppers do mercado atual aos preços mais competitivos. Temos uma equipa altamente qualificada e especializada, à sua disposição 5 dias por semana para lhe dar o apoio necessário ou fornecer-lhe qualquer tipo de informação.",
        "quality_alert_title": "Qualidade e Legalidade Garantidas",
        "quality_alert_p": "Ao comprar na nossa loja, tem acesso a uma vasta gama de poppers, todos eles originais, de alta qualidade e fabricados apenas com nitritos legais como o nitrito de amilo, pentilo e isopropilo.",
        "how_to_buy_title": "Como Comprar na Nossa Loja? Guia de Produtos",
        "how_to_buy_subtitle": "Ajudamo-lo a escolher o aroma perfeito para as suas necessidades.",
        "propyl_title": "Poppers de Propilo: Ideal para Principiantes",
        "propyl_p": "Muito popular pelos seus efeitos mais suaves, é ideal para se iniciar no mundo dos poppers. Encontrá-lo-á em marcas famosas como <span class=\"font-semibold\">Rush, Platinum e Blue Lad</span>. Aqui pode comprar Popper online com total segurança.",
        "amyl_title": "Poppers de Amilo: O Mais Forte e Potente",
        "amyl_p": "Recomendamos os poppers à base de amilo para utilizadores experientes que procuram uma experiência intensa. O <span class=\"font-semibold\">Popper Rise Up</span>, com uma concentração de mais de 98% de amilo, é especialmente apreciado para práticas intensas. Se procura venda de Popper de alta qualidade, esta é a sua melhor opção.",
        "pentyl_title": "Poppers de Pentilo: Efeitos Prolongados e Intensos",
        "pentyl_p": "Um dos mais potentes, o popper de pentilo é muito procurado pela durabilidade dos seus efeitos. Fórmulas como <span class=\"font-semibold\">Extreme Ultra Strong</span> são perfeitas para quem procura experiências mais fortes e é um formato muito solicitado na venda online de poppers para festas.",
        "best_brands_title": "As Melhores Marcas para os Melhores Clientes",
        "shipping_title": "Rapidez e Segurança em Cada Envio",
        "shipping_subtitle": "A sua privacidade e satisfação são a nossa prioridade.",
        "fast_shipping_title": "Envio Rápido e Discreto",
        "fast_shipping_p": "Serviço de entrega em 24/48 horas para a Península Ibérica. As encomendas feitas antes das 16h são expedidas no mesmo dia. A embalagem é sempre neutra, sem nenhuma marca que identifique o conteúdo.",
        "secure_payment_title": "Pagamento 100% Seguro",
        "secure_payment_p": "Não verá nenhuma referência à nossa loja no seu extrato bancário. Além disso, as suas informações pessoais estão protegidas com encriptação SSL para impedir o acesso não autorizado.",
        "payment_methods_p": "Aceitamos transferência bancária, cartão de crédito/débito e pagamento na entrega.",
        "doubts_title": "Tem Dúvidas?",
        "doubts_subtitle": "Contacte a nossa equipa de especialistas.",
        "contact_email": "info@comprarpopperonline.com",
        "explore_button": "Explorar Catálogo"
    },
    cookies_page: {
        "title": "Política de Cookies",
        "subtitle": "Na Popper Online, utilizamos cookies e tecnologias semelhantes para melhorar a sua experiência, garantir a segurança e analisar a utilização do nosso site. Explicamos aqui como e porquê.",
        "what_is_title": "1. O que é um cookie?",
        "what_is_p1": "Um cookie é um pequeno ficheiro de texto que um site armazena no seu computador ou dispositivo móvel quando o visita. Permite que o site se lembre das suas ações e preferências (como login, idioma, tamanho da fonte e outras preferências de visualização) durante um período de tempo, para que não tenha de as reintroduzir sempre que volta ao site ou navega de uma página para outra.",
        "what_is_p2": "Também utilizamos o `localStorage` e o `sessionStorage` do navegador, que são tecnologias semelhantes que nos permitem armazenar informações sem depender exclusivamente de cookies.",
        "types_title": "2. Que tipos de cookies utilizamos?",
        "technical_title": "Cookies Técnicos (Estritamente Necessários)",
        "technical_p": "Estes cookies são essenciais para o funcionamento correto do site. Não podem ser desativados nos nossos sistemas. São definidos em resposta a ações que realiza, como iniciar sessão, adicionar produtos ao carrinho ou preencher formulários. Sem eles, os serviços que solicitou não podem ser fornecidos.",
        "examples": "Exemplos:",
        "technical_examples": "Cookie de sessão do utilizador, cookie do carrinho de compras, cookies de segurança da Stripe.",
        "analytics_title": "Cookies de Análise ou de Desempenho",
        "analytics_p": "Estes cookies permitem-nos contar as visitas e as fontes de tráfego para que possamos medir e melhorar o desempenho do nosso site. Ajudam-nos a saber quais as páginas mais e menos populares e a ver como os visitantes se movem no site. Todas as informações que estes cookies recolhem são agregadas e, portanto, anónimas.",
        "analytics_examples": "Utilizamos o Microsoft Clarity para compreender como interage com o site e melhorar a experiência.",
        "marketing_title": "Cookies de Marketing",
        "marketing_p": "Estes cookies podem ser definidos através do nosso site pelos nossos parceiros de publicidade. Podem ser utilizados por essas empresas para criar um perfil dos seus interesses e mostrar-lhe anúncios relevantes noutros sites. Não armazenam diretamente informações pessoais, mas baseiam-se na identificação única do seu navegador e dispositivo de internet.",
        "marketing_examples": "Cookies da Klaviyo para gerir as nossas subscrições de newsletter e notificações.",
        "manage_title": "3. Como gerir as suas preferências de cookies",
        "manage_p1": "Tem controlo total sobre os seus cookies. Quando visita o nosso site pela primeira vez, mostramos-lhe um banner onde pode aceitar todos os cookies, rejeitar os não essenciais ou personalizar as suas preferências.",
        "manage_p2": "Pode mudar de ideias a qualquer momento. Além disso, a maioria dos navegadores web permite-lhe gerir os cookies através das definições do navegador. Pode configurar o seu navegador para o avisar antes de aceitar cookies ou pode configurá-lo para os rejeitar diretamente.",
        "manage_p3": "Tenha em atenção que se decidir bloquear os cookies técnicos, algumas partes do nosso site podem não funcionar corretamente."
    },
    disputes_page: {
        "subtitle": "Aqui encontrará toda a informação sobre os seus direitos e os procedimentos a seguir se precisar de resolver um contrato ou gerir uma disputa.",
        "right_of_withdrawal_title": "Direito de Rescisão",
        "right_of_withdrawal_p1": "De acordo com o Real Decreto Legislativo 1/2007, dispõe de <strong>14 dias de calendário</strong> a contar da receção da sua encomenda para rescindir o contrato e devolver a mercadoria. Para tal, deve comunicar-nos a sua decisão através de uma declaração inequívoca (por exemplo, uma carta ou um e-mail para <a href=\"mailto:info@comprarpopperonline.com\" class=\"text-primary font-semibold hover:underline\">info@comprarpopperonline.com</a>).",
        "right_of_withdrawal_p2": "Uma vez comunicada a sua decisão, dispõe de mais 14 dias para devolver os produtos. É importante salientar que <strong>os custos de devolução da mercadoria são inteiramente da sua responsabilidade.</strong>",
        "right_of_withdrawal_p3": "Deve conservar os bens para os poder devolver em condições de utilização adequadas. Para que uma devolução seja aceite, os produtos devem ser devolvidos <strong>perfeitamente selados, por abrir, não utilizados, com todos os selos de segurança intactos e na sua embalagem original.</strong> É responsável por qualquer diminuição de valor se o manuseamento dos produtos exceder o necessário para uma mera inspeção visual da sua natureza.",
        "right_of_withdrawal_p4": "Uma vez recebida a mercadoria devolvida e verificado o seu estado, reembolsaremos todos os pagamentos recebidos, com exceção dos custos adicionais se escolheu uma modalidade de envio mais cara do que a padrão que oferecemos. Reservamo-nos o direito de reter o reembolso até termos recebido os produtos e verificado que cumprem as condições de devolução.",
        "exclusion_title": "Exclusão do Direito de Rescisão",
        "exclusion_p1": "Não serão aceites devoluções nas seguintes situações, de acordo com a lei:",
        "exclusion_item1": "Fornecimento de bens selados que não são adequados para devolução por razões de <strong>proteção da saúde ou de higiene</strong> e que tenham sido abertos após a entrega.",
        "exclusion_item2": "Fornecimento de bens como cosméticos, artigos de higiene pessoal, <strong>roupa interior ou qualquer produto de uso íntimo</strong> cuja embalagem tenha sido comprometida.",
        "exclusion_item3": "Gravações sonoras/vídeo ou de programas informáticos aos quais tenha sido retirado o selo de inviolabilidade.",
        "exclusion_item4": "O cliente, na qualidade de <strong>importador final</strong>, é o único responsável por garantir que o produto é legal no seu país. Os custos alfandegários, taxas ou apreensões são da exclusiva responsabilidade do cliente e não darão direito a reembolso.",
        "law_title": "Lei Aplicável, Mediação e Jurisdição",
        "law_p1": "Este contrato rege-se pela <strong>lei francesa</strong>. Para a resolução de qualquer litígio, é competente a jurisdição do <strong>Distrito de Perpignan</strong>, com renúncia a qualquer outra.",
        "adr_title": "Resolução Alternativa de Litígios (RAL)",
        "adr_p1": "Em caso de litígio, pode recorrer a uma Entidade de Resolução Alternativa de Litígios de Consumo. A mediação é um processo gratuito e confidencial para resolver desacordos de forma amigável com a ajuda de um terceiro imparcial.",
        "adr_p2": "Para litígios de consumo online, pode utilizar a plataforma ODR (Online Dispute Resolution) da União Europeia, que facilita a resolução de litígios transfronteiriços.",
        "odr_platform_button": "Plataforma ODR da UE",
        "mediators_button": "Mediadores Oficiais (França)",
        "mediation_steps_title": "Passos para a Mediação",
        "mediation_step1": "Antes de qualquer mediação, deve enviar-nos uma reclamação por escrito (preferencialmente por e-mail para ter um registo).",
        "mediation_step2": "Se não receber uma resposta satisfatória da nossa parte num prazo razoável, pode iniciar o procedimento de mediação através do site do mediador.",
        "mediation_step3": "O mediador informá-lo-á da receção do seu processo e terá 90 dias para propor uma solução. Ambas as partes são livres de a aceitar ou rejeitar.",
        "mediation_p_final": "Para qualquer reclamação ou consulta inicial, pode contactar-nos em <a href=\"mailto:info@comprarpopperonline.com\" class=\"text-primary font-semibold hover:underline\">info@comprarpopperonline.com</a>."
      },
  checkout: {
    "title": "Finalizar Compra",
    "stepper": {
        "cart": "Carrinho",
        "details": "Os Seus Dados",
        "payment": "Pagamento",
        "review": "Revisão"
    },
    "confirm_cart_title": "1. Confirme o Seu Carrinho",
    "user_details_title": "2. Os Seus Dados",
    "user_details_subtitle": "Confirme os seus dados de envio.",
    "user_details_not_logged_in": "Inicie sessão para continuar.",
    "login_required_alert_title": "Início de Sessão Necessário",
    "login_required_alert_desc": "Tem de iniciar sessão ou registar-se para continuar com a sua encomenda.",
    "login_button": "Iniciar Sessão",
    "register_button": "Registar",
    "use_new_address": "Usar nova morada",
    "shipping_address_title": "Morada de Envio",
    "fullname_label": "Nome Completo",
    "email_label": "Email",
    "phone_label": "Telefone",
    "street_label": "Rua e número",
    "street_placeholder": "Rua Fictícia 123, 4º B",
    "city_label": "Cidade",
    "state_label": "Estado / Província",
    "zip_label": "Código Postal",
    "country_label": "País",
    "save_address_label": "Guardar esta morada para compras futuras",
    "use_different_billing_label": "Usar uma morada de faturação diferente",
    "use_different_billing_desc": "Ative esta opção se os seus dados de faturação não coincidirem com os de envio.",
    "billing_address_title": "Morada de Faturação",
    "payment_method_title": "3. Método de Pagamento",
    "cod_label": "Pagamento na Entrega",
    "cod_desc": "(Pague ao receber)",
    "prepaid_label": "Pagamento Antecipado",
    "prepaid_desc": "(Desconto + Presente + Envio Grátis!)",
    "launch_promo_title": "Promoção de Lançamento!",
    "launch_promo_desc": "Ao escolher o pagamento antecipado, beneficia de um <span class=\"font-bold\">desconto de volume, envio gratuito e um presente surpresa</span> na sua encomenda.",
    "payment_options": {
        "cod_cash": "Pagar em dinheiro ao estafeta",
        "cod_card": "Pagar com cartão ao estafeta",
        "cod_bizum": "Pagar com Bizum ao estafeta",
        "prepaid_bizum": "Pagamento antecipado com Bizum",
        "prepaid_transfer": "Pagamento antecipado por Transferência Bancária",
        "crypto": "Pagar com Criptomoedas"
    },
    "review_title": "4. Reveja e Confirme a Sua Encomenda",
    "order_summary_title": "Resumo da Encomenda",
    "coupon_placeholder": "Código de Desconto",
    "apply_button": "Aplicar",
    "applied_button": "Aplicado",
    "subtotal": "Subtotal",
    "volume_discount": "Desconto de volume",
    "coupon_discount": "Desconto do cupão",
    "shipping": "Envio",
    "free_shipping": "Grátis",
    "total_payable": "Total a Pagar",
    "products_title": "Produtos:",
    "billing_address_same": "Igual à morada de envio.",
    "payment_method": "Método de Pagamento:",
    "payment_instructions_prepaid": "Receberá as instruções de pagamento por email.",
    "payment_instructions_cod": "O pagamento será efetuado no momento da entrega.",
    "payment_instructions_email": "Verifique o seu email para mais detalhes.",
    "continue_shopping": "Continuar a Comprar",
    "next_button": "Seguinte",
    "previous_button": "Anterior",
    "processing_button": "A processar...",
    "confirm_order_button": "Confirmar Encomenda",
    "confirming_button": "A confirmar...",
    "form_errors": {
        "name_required": "O nome é obrigatório.",
        "email_invalid": "Por favor, introduza um email válido.",
        "phone_required": "O telefone é obrigatório.",
        "street_required": "A rua é obrigatória.",
        "city_required": "A cidade é obrigatória.",
        "state_required": "O estado/província é obrigatório/a.",
        "zip_required": "O código postal é obrigatório.",
        "country_required": "O país é obrigatório.",
        "payment_method_required": "Deve selecionar um método de pagamento.",
        "billing_field_required": "Obrigatório."
    },
    "toasts": {
        "login_required_title": "Início de sessão necessário",
        "login_required_desc": "Por favor, inicie sessão ou registe-se para continuar.",
        "address_saved_title": "Morada Guardada",
        "address_saved_desc": "A sua nova morada foi guardada no seu perfil.",
        "address_save_error_title": "Erro",
        "address_save_error_desc": "Não foi possível guardar a morada, mas pode continuar com a encomenda.",
        "crypto_error_title": "Erro no Pagamento com Cripto",
        "crypto_error_desc": "Não foi possível criar o link de pagamento com criptomoedas.",
        "order_error_title": "Erro ao Criar Encomenda",
        "order_error_desc": "Ocorreu um erro ao guardar a sua encomenda.",
        "order_success_title": "Reserva Confirmada!",
        "order_success_desc": "A sua encomenda #{orderId} foi recebida.",
        "view_order_button": "Ver Encomenda",
        "continue_shopping_button": "Continuar a Comprar",
        "points_earned_title": "Pontos Ganhos!",
        "points_earned_desc": "Ganhou {points} pontos de fidelidade com esta compra.",
        "coupon_applied_title": "Cupão Aplicado",
        "coupon_applied_desc": "Foi aplicado um desconto de {discount}.",
        "coupon_error_title": "Erro no Cupão",
        "coupon_error_invalid": "O código do cupão não é válido.",
        "coupon_error_inactive": "Este cupão não está ativo.",
        "coupon_error_not_yet_valid": "Este cupão ainda não é válido.",
        "coupon_error_expired": "Este cupão expirou.",
        "coupon_error_limit_reached": "Este cupão atingiu o seu limite de utilizações.",
        "coupon_error_min_purchase": "É necessária uma compra mínima de {price} para usar este cupão.",
        "coupon_error_already_used": "Este cupão só pode ser usado uma vez."
    }
  },
  docs: {
    "title": "Documentação do Site",
    "subtitle1": "Esta página é um <strong>manual de identidade e arquitetura</strong> do site, concebido para ser a fonte de verdade para programadores, designers e gestores de conteúdo. O seu objetivo é garantir a consistência, facilitar a manutenção e orientar a implementação de novas funcionalidades.",
    "subtitle2": "Para os <strong>designers</strong>, define o sistema de design visual: a paleta de cores, a tipografia e os componentes da interface. Para os <strong>programadores</strong>, atua como um mapa da arquitetura técnica, detalhando o stack tecnológico (Next.js, Firebase, Genkit), os principais padrões de código e exemplos de implementação para as funcionalidades mais importantes.",
    "style_guide_title": "Guia de Estilo e Sistema de Design",
    "colors_title": "Paleta de Cores",
    "colors_desc": "A paleta de cores principal definida em `globals.css` usando variáveis CSS HSL.",
    "typography_title": "Tipografia",
    "typography_desc": "A fonte principal do site é a Inter, configurada em `src/app/layout.tsx`.",
    "icons_title": "Iconografia e Gráficos",
    "icons_desc": "A biblioteca `lucide-react` é usada para ícones e um SVG personalizado é usado para o logótipo.",
    "brand_assets_title": "Ativos de Marca e Recursos Visuais",
    "logo_title": "Logótipo Principal",
    "logo_desc": "O logótipo oficial \"Popper Online\" em formato SVG e PNG, otimizado para web e design gráfico.",
    "data_arch_title": "Arquitetura de Dados e Comunicação",
    "data_flow_title": "Comunicação Cliente-Servidor para Produtos (Leitura/Escrita)",
    "data_flow_desc": "Explicação técnica de como o painel de administração lê e guarda os dados dos produtos sem uma API REST tradicional.",
    "business_logic_title": "Lógica de Negócio e Marketing",
    "age_gate_title": "Verificação de Idade (Popup Modal)",
    "age_gate_desc": "Um popup modal que bloqueia o acesso ao site até o utilizador verificar que tem mais de 18 anos.",
    "sales_notifications_title": "Notificações de Vendas Híbridas (Reais e Simuladas)",
    "sales_notifications_desc": "Popups que mostram compras para gerar confiança. Prioriza compras reais e preenche as lacunas com notificações simuladas.",
    "welcome_popup_title": "Popup de Boas-Vindas com Desconto",
    "welcome_popup_desc": "Um popup que oferece 10% de desconto em troca da subscrição da newsletter. Aparece apenas a novos visitantes ou após 24h.",
    "volume_discounts_title": "Política de Descontos por Volume",
    "volume_discounts_desc": "Sistema de desconto automático no carrinho com base na quantidade de produtos. Não se aplica a pagamentos na entrega.",
    "loyalty_points_title": "Sistema de Pontos de Fidelidade",
    "loyalty_points_desc": "Os utilizadores ganham pontos com cada compra, que podem ser trocados por descontos futuros.",
    "main_pages_title": "Páginas Principais",
    "home_page_title": "Página Inicial",
    "home_page_desc": "A página de boas-vindas com produtos em destaque e acesso às secções principais.",
    "products_page_title": "Catálogo de Produtos",
    "products_page_desc": "Mostra todos os produtos com filtros por marca, tamanho, composição e pesquisa.",
    "product_detail_page_title": "Detalhe do Produto",
    "product_detail_page_desc": "Vista detalhada de um produto com uma galeria, informações e produtos relacionados (exemplo com \"Rush Original\").",
    "ecommerce_features_title": "Funcionalidades de E-commerce",
    "pack_builder_title": "Construtor de Packs",
    "pack_builder_desc": "Uma ferramenta para os clientes criarem o seu próprio pack de produtos com descontos de volume.",
    "cart_title": "Carrinho de Compras",
    "cart_desc": "O carrinho é um painel lateral. Clique no ícone flutuante do carrinho para o abrir após adicionar um produto.",
    "checkout_title": "Processo de Checkout",
    "checkout_desc": "Um fluxo de checkout de 4 passos. Requer itens no carrinho para funcionar.",
    "subscription_title": "Subscrição \"Dose Mensal\" (com NOWPayments)",
    "subscription_start_title": "Fluxo de Início de Subscrição",
    "subscription_start_desc": "Página de destino e processo de pagamento inicial para aderir ao clube de subscrição.",
    "subscription_management_title": "Gestão e Cancelamento de Subscrição",
    "subscription_management_desc": "Um painel para os subscritores personalizarem a sua caixa e gerirem a sua adesão.",
    "subscription_webhook_title": "Webhook de Notificações (IPN)",
    "subscription_webhook_desc": "Endpoint que a NOWPayments usa para notificar o servidor sobre eventos de subscrição.",
    "auth_title": "Conta de Utilizador e Autenticação",
    "login_title": "Iniciar Sessão",
    "login_desc": "Formulário para utilizadores existentes acederem à sua conta, com lógica de redirecionamento baseada no papel.",
    "register_title": "Registo de Novo Utilizador",
    "register_desc": "Formulário para novos utilizadores criarem uma conta.",
    "account_dashboard_title": "Painel de Controlo da Conta",
    "account_dashboard_desc": "O painel principal do utilizador com um resumo da sua atividade. Requer início de sessão.",
    "orders_title": "As Minhas Encomendas",
    "orders_desc": "Histórico de todas as encomendas feitas pelo utilizador.",
    "addresses_title": "As Minhas Moradas",
    "addresses_desc": "Gestão de moradas de envio e faturação guardadas.",
    "admin_panel_title": "Painel de Administração",
    "admin_dashboard_title": "Painel de Administração",
    "admin_dashboard_desc": "Painel principal com estatísticas. Requer início de sessão como administrador (maryandpopper@gmail.com).",
    "admin_orders_title": "Gestão de Encomendas",
    "admin_orders_desc": "Ver e gerir todas as encomendas da loja.",
    "admin_products_crud_title": "Gestão de Produtos: \"Adicionar\" e \"Editar\" em detalhe",
    "admin_products_crud_desc": "Fluxo técnico completo sobre como os produtos são criados e editados a partir do painel de administração.",
    "admin_products_fields_title": "Guia de Campos de Produto e Lógica de Preços",
    "admin_products_fields_desc": "Adicionar, editar, arquivar e eliminar produtos do catálogo.",
    "admin_web_customization_title": "Personalização Web",
    "admin_web_customization_desc": "Ativar ou desativar funcionalidades chave, como a subscrição.",
    "info_pages_title": "Páginas Informativas e Legais",
    "info_blog_title": "Blog",
    "info_blog_desc": "Lista de artigos e notícias.",
    "info_contact_title": "Contacto",
    "info_contact_desc": "Formulário de contacto e informações legais da empresa.",
    "info_shipping_title": "Envio e Tarifas",
    "info_shipping_desc": "Detalhes sobre as políticas e custos de envio.",
    "info_terms_title": "Termos e Condições",
    "info_terms_desc": "Termos e condições gerais de contrato e venda.",
    "try_it_button": "Experimentar",
    "implementation_details_button": "Ver detalhes de implementação",
    "download_svg_button": "Descarregar Logótipo (SVG)",
    "download_png_button": "Descarregar Logótipo (PNG)"
  }
};

const enTranslations: Translations = {};
const frTranslations: Translations = {};
const deTranslations: Translations = {};
const itTranslations: Translations = {};
const ptTranslations: Translations = {};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Helper function to get nested property safely
const getNestedTranslation = (obj: Translations, key: string): string | Translations | undefined => {
  return key.split('.').reduce<string | Translations | undefined>((acc, part) => {
    if (acc && typeof acc === 'object' && part in acc) {
      return (acc as Translations)[part];
    }
    return undefined;
  }, obj);
}

const translations: Record<Language, Translations> = {
  es: esTranslations,
  en: enTranslations,
  fr: frTranslations,
  de: deTranslations,
  it: itTranslations,
  pt: ptTranslations,
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguage] = useState<Language>('es');

  const setLanguageCallback = useCallback((lang: Language) => {
    setLanguage(lang);
  }, []);

  const t = useCallback((key: string, replacements: Record<string, string | number> = {}): string => {
    const selectedLanguageTranslations = translations[language] || translations.es;
    
    let translation = getNestedTranslation(selectedLanguageTranslations, key);

    // Fallback to Spanish if translation not found in the current language
    if (typeof translation !== 'string' && language !== 'es') {
        const fallbackTranslation = getNestedTranslation(translations.es, key);
        if (typeof fallbackTranslation === 'string') {
            translation = fallbackTranslation;
        }
    }
    
    // If still not found, return the key itself as a last resort
    if (typeof translation !== 'string') {
        console.warn(`Translation key not found in any language: ${key}`);
        return key;
    }

    let strResult = translation;
    for (const placeholder in replacements) {
        strResult = strResult.replace(`{${placeholder}}`, String(replacements[placeholder]));
    }
    return strResult;

  }, [language]);


  const value = useMemo(() => ({
    language,
    setLanguage: setLanguageCallback,
    t,
  }), [language, setLanguageCallback, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Alias for useLanguage for convenience in components
export const useTranslation = useLanguage;
